import type { ElementSeed, SectionKey } from '@/content/subjects/chemistry/elementSeeds';
import {
  appliedSection,
  classificationSection,
  electronicSection,
  isotopeSection,
  occurrenceSection,
  physicalSection,
  productionSection,
  reactivitySection,
  term,
  type FactSet,
} from '@/content/subjects/chemistry/seedFactories';

type SeedConfig = Omit<ElementSeed, 'sections'> & { sections: Record<SectionKey, FactSet> };

function facts(a: string, b: string, c: string, d: string, e: string): FactSet {
  return [a, b, c, d, e];
}

function makeSeed(config: SeedConfig): ElementSeed {
  return {
    ...config,
    sections: {
      classification: classificationSection(config.name, config.sections.classification),
      electronic: electronicSection(config.name, config.sections.electronic),
      physical: physicalSection(config.name, config.sections.physical),
      reactivity: reactivitySection(config.name, config.sections.reactivity),
      occurrence: occurrenceSection(config.name, config.sections.occurrence),
      isotopes: isotopeSection(config.name, config.sections.isotopes),
      production: productionSection(config.name, config.sections.production),
      applied: appliedSection(config.name, config.sections.applied),
    },
  };
}

export const earlyPeriodSixElementSeeds: ElementSeed[] = [
  makeSeed({
    id: 'cesium',
    name: 'Cesium',
    symbol: 'Cs',
    atomicNumber: 55,
    atomicMass: '132.90545196',
    group: '1',
    period: '6',
    block: 's',
    category: 'Alkali metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]6s1',
    oxidationStates: '+1',
    summaryLine:
      'Cesium is a very heavy alkali metal whose extreme reactivity contrasts with the extraordinary precision of cesium-based frequency standards and atomic measurements.',
    importanceLine:
      'Its chemistry connects the heavy end of group 1 to atomic-clock science, photoemission, specialty fluids, and the handling of one of the most reactive common metals.',
    heroFacts: ['Heaviest stable alkali metal', 'Cs+ dominates chemistry', 'Defines the SI second', 'Extremely reactive metal'],
    glossaryExtras: [
      term('Pollucite', 'A cesium-bearing aluminosilicate mineral and the principal ore of cesium.'),
      term('Cesium standard', 'An atomic frequency standard based on cesium transitions.'),
      term('Cesium formate', 'A dense cesium salt solution used in specialty drilling fluids.'),
    ],
    sections: {
      classification: facts('a very heavy alkali metal with one 6s valence electron', 'group 1, period 6, s-block', '[Xe]6s1', 'it forms strongly ionic Cs+ salts and is among the easiest stable elements to ionize', 'its chemistry represents the extreme soft and reactive end of the stable alkali-metal trend'),
      electronic: facts('a [Xe]6s1 valence shell', 'it forms overwhelmingly ionic compounds stabilized as Cs+ in salts and solutions', '+1 in ordinary compounds', 'CsCl, CsOH, cesium superoxide, and solvated Cs+ ions', 'very low ionization energy and large ionic size strongly shape reactivity and spectroscopy'),
      physical: facts('a very soft pale metallic solid that melts near room temperature', 'it is one of the most easily melted metallic elements and forms dense liquid metal readily', 'weak metallic bonding in a very large alkali lattice explains softness and low melting point', 'sealed cesium ampoules, cesium vapor cells, and dense cesium salt solutions', 'air and moisture exclusion is essential because rapid oxidation and ignition can occur'),
      reactivity: facts('an extremely reactive reducing metal that reacts violently with water and oxygen', 'it forms hydroxide and hydrogen with water and oxidized products in air almost immediately', 'very low ionization energy and strong stabilization of Cs+ drive the chemistry', 'halides, hydroxides, superoxides, vapor-phase alkali systems, and specialized organocesium chemistry', 'metal handling requires rigorous exclusion of air and moisture because fire or explosion can occur'),
      occurrence: facts('pollucite, pegmatites, and mixed alkali mineral systems', 'it is geochemically scarce and economically important mainly in specialty applications', 'pollucite-bearing pegmatites are the main practical reservoir', 'cesium follows heavy-alkali mineral chemistry and is often recovered as a specialty byproduct', 'native cesium does not occur because ionic mineral forms are strongly favored'),
      isotopes: facts('stable cesium-133 together with radioactive cesium-134 and cesium-137', 'cesium-133 is the only stable isotope, while cesium-137 is a major fission product', 'isotope behavior makes cesium central to both precision metrology and radiological monitoring', 'cesium-133 defines the SI second and cesium-137 is important in fallout and industrial sources', 'cesium isotope chemistry spans both the highest precision measurement and major nuclear-environmental concern'),
      production: facts('recovery from pollucite and specialty pegmatite feedstocks', 'industrial supply is niche and depends on separating cesium from related alkali metals rather than on bulk commodity production', 'chemical conversion to high-purity salts and selective refining are common routes', 'purity control is essential for atomic standards and specialty optical or electronic uses', 'supply depends on a small number of mineral sources and specialized demand'),
      applied: facts('atomic clocks, photoemissive devices, specialty drilling fluids, and research optics or quantum systems', 'cesium metal, cesium salts, cesium vapor, and cesium formate solutions', 'cesium is important because no other alkali metal combines such reactivity with such central metrological importance', 'its technological identity is dominated by timekeeping and precision measurement rather than bulk chemistry', 'hazards center on extreme metal reactivity and, for radioisotopes, contamination control'),
    },
  }),
  makeSeed({
    id: 'barium',
    name: 'Barium',
    symbol: 'Ba',
    atomicNumber: 56,
    atomicMass: '137.327',
    group: '2',
    period: '6',
    block: 's',
    category: 'Alkaline earth metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]6s2',
    oxidationStates: '+2',
    summaryLine:
      'Barium is a heavy alkaline-earth metal whose Ba2+ salts are important in drilling, pyrotechnics, medical imaging, and selected electronic ceramics.',
    importanceLine:
      'Its chemistry links heavy group-2 ionic behavior to insoluble sulfates, bright flame colors, toxic soluble salts, and barite-based industrial supply.',
    heroFacts: ['Heavy alkaline earth metal', 'Ba2+ dominates chemistry', 'Barite is the main ore', 'BaSO4 is important in imaging and drilling'],
    glossaryExtras: [
      term('Barite', 'Barium sulfate mineral, BaSO4, and the principal ore of barium.'),
      term('Witherite', 'Barium carbonate mineral used as a secondary source of barium.'),
      term('Radiocontrast agent', 'A compound such as BaSO4 used to improve X-ray imaging contrast.'),
    ],
    sections: {
      classification: facts('a heavy alkaline earth metal with a filled 6s pair', 'group 2, period 6, s-block', '[Xe]6s2', 'it forms Ba2+ readily and shows classic ionic group-2 chemistry at large ionic size', 'its chemistry is more weakly hydrated and often less soluble-patterned than that of lighter alkaline earths'),
      electronic: facts('a [Xe]6s2 valence shell', 'it forms strongly ionic compounds centered on Ba2+ in solids and solutions', '+2 in ordinary compounds', 'BaSO4, BaCO3, BaCl2, BaO, and hydrated Ba2+ species', 'large cation size and low charge density give heavy alkaline-earth behavior distinct from magnesium or calcium'),
      physical: facts('a soft silvery metallic solid', 'it is reactive enough that bulk metal is stored away from air and moisture', 'metallic bonding in the large group-2 lattice supports softness and ready oxidation', 'barium metal, barite powders, and barium-containing ceramic or glass materials', 'soluble barium compounds and reactive metal require more care than the very insoluble sulfate'),
      reactivity: facts('a reactive alkaline-earth metal forming stable ionic oxides, hydroxides, halides, and sulfate salts', 'it reacts with oxygen, water, and acids to produce Ba2+ compounds while some salts remain highly insoluble', 'stabilization of Ba2+ and strong lattice energies in selected salts drive the chemistry', 'barium sulfate, carbonate, oxide, peroxide, nitrates, and ferrite or ceramic materials', 'soluble barium salts are toxic and metallic barium requires dry protected handling'),
      occurrence: facts('barite, witherite, and heavy sulfate mineral deposits', 'it is concentrated enough in sulfate minerals to support large industrial use', 'barite deposits are the dominant practical reservoir', 'barium geochemistry is strongly tied to sulfate precipitation and mineral density', 'native barium does not occur because ionic mineral forms are much more stable'),
      isotopes: facts('multiple stable isotopes including barium-130, 132, 134, 135, 136, 137, and 138', 'natural barium has several stable isotopes, while barium-137m is notable in nuclear decay schemes', 'isotopic composition supports geochemical and nuclear-analytical work', 'barium isotopes are useful in environmental tracing and in understanding cesium-137 decay products', 'routine barium chemistry is dominated more by solubility and toxicity than by isotope effects'),
      production: facts('mining and refining of barite and related barium minerals', 'industrial production is centered on salt and mineral conversion rather than on isolated metal manufacture', 'conversion to carbonate, chloride, nitrate, oxide, or sulfate products are major industrial routes', 'purity control matters for drilling fluids, electronics, and medical-grade materials', 'metallic barium is a niche product compared with the much larger barium-salt market'),
      applied: facts('drilling fluids, radiocontrast imaging, pyrotechnics, ceramics, vacuum technology, and specialty glass', 'barite, barium sulfate, barium carbonate, barium titanate, and selected metallic barium uses', 'barium is important because heavy alkaline-earth chemistry gives useful density, color, dielectric, and imaging behavior', 'its industrial importance grew through barite drilling uses and later through electronic ceramics such as barium titanate', 'hazards center on soluble-salt toxicity and reactive metal handling, whereas BaSO4 is comparatively safe due to insolubility'),
    },
  }),
  makeSeed({
    id: 'lanthanum',
    name: 'Lanthanum',
    symbol: 'La',
    atomicNumber: 57,
    atomicMass: '138.90547',
    group: '3',
    period: '6',
    block: 'f',
    category: 'Rare earth metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]5d1 6s2',
    oxidationStates: '+3',
    summaryLine:
      'Lanthanum is a rare earth metal whose La3+ chemistry, oxide basicity, and catalytic or optical applications make it an important entry point to the lanthanide series.',
    importanceLine:
      'Its chemistry links rare-earth separation, hard trivalent cations, catalyst supports, and advanced glasses or battery materials.',
    heroFacts: ['Rare earth metal', 'La3+ dominates chemistry', 'Recovered with lanthanides', 'Important in optics and catalysts'],
    glossaryExtras: [
      term('Rare earth element', 'An element in the lanthanide series or closely related chemistry, often requiring complex separation.'),
      term('Mischmetal', 'A mixed rare-earth alloy containing substantial lanthanum and cerium.'),
      term('Lanthanide contraction', 'The progressive shrinkage of trivalent lanthanide ions across the series.'),
    ],
    sections: {
      classification: facts('a rare earth metal and the first member of the lanthanide series in practical chemistry', 'period 6, lanthanide series, f-block', '[Xe]5d1 6s2', 'it forms hard trivalent La3+ compounds and shows chemistry dominated by oxides and salts', 'its chemistry is simpler and more uniformly trivalent than that of cerium and later redox-flexible lanthanides'),
      electronic: facts('an [Xe]5d1 6s2 valence arrangement', 'it loses three electrons readily to form strongly ionic La3+ compounds', '+3', 'La2O3, LaCl3, lanthanum phosphates, and lanthanum-containing glasses or oxides', 'the chemistry is dominated by a hard trivalent cation with little ordinary multivalent complexity'),
      physical: facts('a soft silvery reactive rare-earth metal', 'it tarnishes readily and is softer than many common transition metals', 'metallic bonding in a large electropositive rare-earth metal explains softness and easy oxidation', 'lanthanum metal, lanthanum oxide powders, and rare-earth alloy materials', 'air exposure, powders, and high-temperature processing require oxidation control'),
      reactivity: facts('a reactive rare-earth metal forming stable La3+ oxides, halides, and salts', 'it oxidizes in air, reacts with acids, and forms strongly ionic trivalent compounds', 'stabilization of La3+ and basic lanthanum oxides drives much of the chemistry', 'oxides, fluorides, chlorides, phosphates, and mixed rare-earth alloys or catalysts', 'powders and hot metal require care, though hazards are more typical rare-earth than exceptionally exotic'),
      occurrence: facts('bastnasite, monazite, and mixed rare-earth mineral concentrates', 'it is one of the more abundant rare earths but still obtained through complex mixed-ore processing', 'rare-earth mineral concentrates are the main practical reservoirs', 'lanthanum occurrence is inseparable from the broader rare-earth ore and separation industry', 'native lanthanum does not occur because oxidized mineral forms are far more stable'),
      isotopes: facts('stable lanthanum-139 together with long-lived lanthanum-138', 'lanthanum-139 dominates natural lanthanum while lanthanum-138 is naturally radioactive but minor', 'isotopes are useful in geochemistry and nuclear studies', 'lanthanum isotope data support analytical and cosmochemical work', 'routine lanthanum chemistry is shaped more by separation and oxide behavior than by isotope complexity'),
      production: facts('recovery and separation from mixed rare-earth concentrates such as bastnasite and monazite', 'industrial supply depends on multistep rare-earth separation rather than simple direct reduction of a single ore', 'solvent extraction and precipitation routes are central to refining', 'purity control matters for optical, catalytic, and battery-related materials', 'supply tracks the economics of the broader rare-earth industry'),
      applied: facts('optical glass, catalysts, battery materials, phosphors, and specialty ceramics', 'lanthanum oxide, lanthanum halides, mischmetal, lanthanum nickel compounds, and catalyst supports', 'lanthanum is important because its basic trivalent oxide chemistry gives useful optical and catalytic properties', 'its industrial identity grew with lighter flints, optical materials, catalysts, and nickel-metal-hydride battery chemistry', 'hazards are moderate and center on dusts, powders, and standard rare-earth process exposure'),
    },
  }),
  makeSeed({
    id: 'cerium',
    name: 'Cerium',
    symbol: 'Ce',
    atomicNumber: 58,
    atomicMass: '140.116',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f1 5d1 6s2',
    oxidationStates: '+3, +4',
    summaryLine:
      'Cerium is a lanthanide notable for accessible Ce3+ and Ce4+ chemistry, oxygen-storage behavior, and widespread use in catalysts, polishing powders, and alloys.',
    importanceLine:
      'Its chemistry connects rare-earth trivalency to one of the most useful multivalent exceptions in the lanthanide series.',
    heroFacts: ['Lanthanide with Ce3+/Ce4+ chemistry', 'Important in catalysts', 'Used in glass polishing', 'Common in mischmetal'],
    glossaryExtras: [
      term('Ceria', 'Cerium dioxide, CeO2, a major catalytic and polishing material.'),
      term('Oxygen storage capacity', 'Ability of a material such as ceria to reversibly exchange oxygen during catalytic operation.'),
      term('Mischmetal', 'A mixed rare-earth alloy rich in cerium and lanthanum.'),
    ],
    sections: {
      classification: facts('a lanthanide rare-earth metal with unusually accessible +4 chemistry in addition to the usual +3 state', 'period 6, lanthanide series, f-block', '[Xe]4f1 5d1 6s2', 'it forms Ce3+ salts and Ce4+ oxides or oxidizing compounds that distinguish it from many lanthanides', 'its chemistry is the clearest practical bridge between ordinary lanthanide trivalency and useful higher oxidation states'),
      electronic: facts('an [Xe]4f1 5d1 6s2 valence arrangement', 'it forms hard rare-earth compounds but can also stabilize Ce4+ under oxidizing conditions', '+3 and +4', 'Ce2O3, CeO2, cerium salts, and mixed rare-earth alloys or catalysts', 'the accessibility of Ce4+ makes cerium redox chemistry especially important within the lanthanide series'),
      physical: facts('a soft silvery rare-earth metal that oxidizes readily', 'it is relatively easy to oxidize and is often handled through its oxide or alloy forms rather than as bare metal', 'reactive rare-earth metallic bonding and strong oxide formation shape its physical behavior', 'cerium metal, ceria powders, polishing compounds, and mischmetal', 'powders and fresh surfaces oxidize readily and require standard rare-earth handling control'),
      reactivity: facts('a reactive lanthanide whose chemistry is dominated by trivalent salts and redox-active cerium oxides', 'it forms oxides, halides, and catalytic oxide systems while undergoing Ce3+/Ce4+ interconversion', 'strong stabilization of cerium oxides and the unusual accessibility of Ce4+ drive much of the chemistry', 'ceria, cerium salts, polishing compounds, catalysts, and pyrophoric alloy systems', 'powders and some alloy forms can be more reactive than bulk oxide materials'),
      occurrence: facts('bastnasite, monazite, and other mixed rare-earth minerals', 'it is among the more abundant lanthanides and a major component of many rare-earth concentrates', 'rare-earth mineral concentrates are the dominant practical reservoir', 'cerium occurrence and supply are tied to the rare-earth separation industry and often exceed demand relative to some heavier lanthanides', 'native cerium is absent because oxidized mineral forms dominate naturally'),
      isotopes: facts('multiple stable isotopes including cerium-136, 138, 140, and 142', 'natural cerium contains several stable isotopes, with cerium-140 most abundant', 'isotope chemistry is useful in geochemistry and cosmochemistry', 'cerium isotopes support tracing and high-precision analytical work', 'ordinary cerium chemistry is driven mainly by Ce3+/Ce4+ behavior rather than isotope effects'),
      production: facts('separation from bastnasite and monazite concentrates followed by purification to oxides or salts', 'industrial supply depends on large-scale rare-earth separation and oxide processing', 'cerium is often separated as oxide because Ce4+ chemistry can be exploited industrially', 'purity control is critical for catalytic and polishing applications', 'supply is tied to broader rare-earth mining and refinement rather than to dedicated cerium-only deposits'),
      applied: facts('automotive catalysts, glass polishing, lighter flints, oxide abrasives, and specialty alloys', 'ceria, cerium salts, mischmetal, polishing powders, and catalyst materials', 'cerium is important because Ce3+/Ce4+ redox chemistry gives the rare-earth series a major catalytic workhorse', 'its industrial prominence grew through polishing compounds, flints, and oxygen-buffer catalysts', 'hazards are moderate and center on dusts, powders, and standard rare-earth process exposure'),
    },
  }),
  makeSeed({
    id: 'praseodymium',
    name: 'Praseodymium',
    symbol: 'Pr',
    atomicNumber: 59,
    atomicMass: '140.90766',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f3 6s2',
    oxidationStates: '+3, +4',
    summaryLine:
      'Praseodymium is a lanthanide whose Pr3+ chemistry dominates, but whose optical, magnetic, and occasional Pr4+ behavior make it useful in glasses, magnets, and ceramics.',
    importanceLine:
      'Its chemistry links rare-earth trivalency to color, magnetism, and selected higher-valent oxide behavior.',
    heroFacts: ['Lanthanide metal', 'Pr3+ dominates chemistry', 'Used in magnets and glasses', 'Recovered with rare earths'],
    glossaryExtras: [
      term('Praseodymia', 'Praseodymium oxide materials used in pigments, ceramics, and specialty chemistry.'),
      term('Didymium glass', 'A glass coloration historically associated with mixed neodymium and praseodymium.'),
      term('Rare-earth magnet', 'A high-performance permanent magnet built from rare-earth-containing materials.'),
    ],
    sections: {
      classification: facts('a lanthanide rare-earth metal whose chemistry is dominated by the trivalent state', 'period 6, lanthanide series, f-block', '[Xe]4f3 6s2', 'it forms hard Pr3+ compounds and selected Pr4+ oxides under oxidizing conditions', 'its chemistry is more strongly optical and magnetic in application than bulk-redox diverse'),
      electronic: facts('an [Xe]4f3 6s2 valence arrangement', 'it forms mainly Pr3+ salts with occasional higher-valent oxide chemistry', '+3 and +4', 'praseodymium oxides, halides, glass colorants, and magnet-related materials', '4f electrons shape optical spectra and magnetic behavior more than ordinary directional bonding'),
      physical: facts('a soft silvery rare-earth metal', 'it tarnishes readily and is often encountered as oxide, salt, or alloy forms rather than naked metal', 'reactive rare-earth metallic bonding explains softness and oxidation tendency', 'praseodymium metal, oxide powders, colored glasses, and magnetic materials', 'fresh surfaces and powders oxidize readily and require controlled handling'),
      reactivity: facts('a reactive lanthanide forming stable Pr3+ oxides, halides, and salts', 'it oxidizes in air and reacts with acids while supporting selected mixed-valent oxide chemistry', 'stabilization of hard trivalent praseodymium and oxide formation dominate the chemistry', 'oxides, fluorides, chlorides, glass colorants, and magnet or ceramic materials', 'hazards are moderate and center on powders and high-temperature rare-earth processing'),
      occurrence: facts('bastnasite, monazite, and mixed rare-earth mineral concentrates', 'it is obtained as part of the broader rare-earth separation industry rather than through dedicated major praseodymium ores', 'mixed rare-earth concentrates are the practical reservoir', 'praseodymium supply depends on rare-earth separations and magnet-related demand', 'native praseodymium does not occur because oxidized mineral forms are far more stable'),
      isotopes: facts('stable praseodymium-141 together with selected radioisotopes', 'praseodymium-141 is the only stable isotope', 'isotope work is specialized and less central than for medically important rare earths', 'radioisotopes of praseodymium are used mainly in research and tracing', 'ordinary praseodymium chemistry is dominated by 4f-electron properties rather than isotope complexity'),
      production: facts('separation from bastnasite and monazite concentrates into purified rare-earth salts or oxides', 'industrial production depends on difficult lanthanide separations from chemically similar neighbors', 'solvent extraction and precipitation routes are standard refining methods', 'high purity matters for magnet, optical, and ceramic applications', 'supply is tightly coupled to rare-earth mining and separation economics'),
      applied: facts('magnets, glass colorants, ceramics, alloys, and specialty optical materials', 'praseodymium oxide, praseodymium halides, rare-earth magnet materials, and mixed rare-earth alloys', 'praseodymium is important because its electronic structure gives distinctive color and magnetic contributions in materials', 'its technological use expanded with high-performance magnets and specialty optical products', 'hazards are moderate and center on rare-earth dusts, powders, and process chemicals'),
    },
  }),
  makeSeed({
    id: 'neodymium',
    name: 'Neodymium',
    symbol: 'Nd',
    atomicNumber: 60,
    atomicMass: '144.242',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f4 6s2',
    oxidationStates: '+3',
    summaryLine:
      'Neodymium is a lanthanide best known for strong Nd3+ chemistry, intense optical transitions, and its central role in the highest-performance permanent magnets.',
    importanceLine:
      'Its chemistry links rare-earth trivalency to lasers, magnets, and the strategic supply questions surrounding advanced energy and electronics materials.',
    heroFacts: ['Lanthanide metal', 'Nd3+ dominates chemistry', 'Key to Nd-Fe-B magnets', 'Important laser ion'],
    glossaryExtras: [
      term('Nd-Fe-B magnet', 'A high-performance permanent magnet containing neodymium, iron, and boron.'),
      term('Nd:YAG', 'A laser host crystal containing neodymium ions in yttrium aluminum garnet.'),
      term('Rare-earth separation', 'Industrial separation of chemically similar lanthanide ions into purified products.'),
    ],
    sections: {
      classification: facts('a lanthanide rare-earth metal whose chemistry is dominated by the trivalent state', 'period 6, lanthanide series, f-block', '[Xe]4f4 6s2', 'it forms hard Nd3+ compounds with strong optical and magnetic consequences in materials', 'its chemistry is less redox-flexible than cerium but far more important in magnets and laser media'),
      electronic: facts('an [Xe]4f4 6s2 valence arrangement', 'it forms mainly Nd3+ salts and solids in which 4f electrons shape spectra and magnetism', '+3', 'neodymium oxides, halides, Nd:YAG, and Nd-Fe-B-related materials', '4f electrons are shielded enough that optical and magnetic signatures remain sharp in many host materials'),
      physical: facts('a soft silvery rare-earth metal', 'it tarnishes readily and is usually handled as oxide, salt, alloy, or protected metal', 'reactive rare-earth metallic bonding explains softness and fast oxidation', 'neodymium metal, oxide powders, laser crystals, and magnet precursor materials', 'powders and fresh surfaces oxidize readily and require controlled handling'),
      reactivity: facts('a reactive lanthanide forming stable Nd3+ oxides, halides, and salts', 'it reacts with oxygen, acids, and halogens in the usual trivalent rare-earth pattern', 'stabilization of Nd3+ and oxide formation drives the chemistry', 'oxides, fluorides, chlorides, magnet precursor materials, and optical host systems', 'hazards are moderate and tied mainly to powders, oxidation, and industrial rare-earth processing'),
      occurrence: facts('bastnasite, monazite, and mixed rare-earth mineral concentrates', 'it is one of the more commercially important lanthanides because of magnet demand rather than unique ore abundance', 'mixed rare-earth concentrates are the main practical reservoir', 'neodymium supply is strongly shaped by magnet manufacturing and rare-earth separation capacity', 'native neodymium does not occur because oxidized mineral forms dominate naturally'),
      isotopes: facts('multiple stable isotopes including neodymium-142, 143, 144, 145, 146, 148, and 150', 'natural neodymium contains several stable isotopes', 'isotopic composition is important in geochronology, cosmochemistry, and planetary science', 'neodymium isotopes are central in Sm-Nd dating and isotopic tracing', 'few rare-earth elements have isotope systems as geochemically influential as neodymium'),
      production: facts('separation from bastnasite and monazite concentrates followed by oxide or salt refining', 'industrial production depends on multistage lanthanide separations rather than simple direct extraction', 'solvent extraction and precipitation dominate purification', 'high purity is essential for magnets, lasers, and optical materials', 'supply depends strongly on the broader rare-earth market and strategic materials demand'),
      applied: facts('permanent magnets, lasers, glass coloration, audio devices, and optical materials', 'neodymium oxide, neodymium salts, Nd:YAG, and Nd-Fe-B magnets', 'neodymium is important because its electronic structure makes it one of the defining rare-earth materials for high-field magnets and lasers', 'its technological significance expanded dramatically with compact motors, electronics, and solid-state lasers', 'hazards are moderate and center on rare-earth powders, process dusts, and strategic-supply constraints rather than unusual bulk toxicity'),
    },
  }),
  makeSeed({
    id: 'promethium',
    name: 'Promethium',
    symbol: 'Pm',
    atomicNumber: 61,
    atomicMass: '[145]',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f5 6s2',
    oxidationStates: '+3',
    summaryLine:
      'Promethium is a radioactive lanthanide with no stable isotopes, known mainly through nuclear production, tracer uses, and historical luminous or power applications.',
    importanceLine:
      'Its chemistry links lanthanide trivalency to radiochemistry, fission-product science, and niche applications where controlled radioactivity is useful.',
    heroFacts: ['No stable isotopes', 'Lanthanide metal', 'Pm3+ dominates chemistry', 'Produced in nuclear systems'],
    glossaryExtras: [
      term('Fission product', 'A nuclide formed during splitting of heavy nuclei such as uranium.'),
      term('Radioisotope battery', 'A device that derives energy from radioactive decay.'),
      term('Lanthanide series', 'A sequence of rare-earth elements dominated by 4f-electron chemistry.'),
    ],
    sections: {
      classification: facts('a radioactive lanthanide whose ordinary chemistry is that of a trivalent rare-earth ion', 'period 6, lanthanide series, f-block', '[Xe]4f5 6s2', 'it forms Pm3+ compounds similar to neighboring lanthanides but is never encountered as a stable natural element', 'its chemical identity is lanthanide-like while its practical identity is radiochemical'),
      electronic: facts('an [Xe]4f5 6s2 valence arrangement', 'it forms mainly hard Pm3+ compounds analogous to samarium and neodymium salts', '+3', 'promethium oxides, halides, and radiochemical tracer compounds', '4f-electron behavior resembles nearby lanthanides while radioactivity determines practical use'),
      physical: facts('a silvery radioactive rare-earth metal known mainly in small controlled quantities', 'its physical handling is dominated by shielding and contamination control rather than bulk-metallurgical use', 'reactive rare-earth metallic bonding exists, but most work is done on salts or radioisotope preparations', 'promethium sources, promethium salts, and isotope devices', 'radiological control and decay management are essential in all handling'),
      reactivity: facts('a reactive lanthanide forming stable Pm3+ oxides, halides, and salts', 'chemically it follows normal lanthanide trivalent behavior even though applications are dictated by radioactivity', 'stabilization of hard trivalent promethium compounds drives the chemistry', 'oxides, halides, tracer salts, and radioisotope source materials', 'the dominant hazards are radiological rather than unusual chemical violence'),
      occurrence: facts('trace natural formation in uranium fission environments and deliberate nuclear production streams', 'it is effectively absent as a stable crustal element because all isotopes are radioactive', 'reactor fuel and nuclear-fission products are the main practical reservoir', 'promethium occurrence is a nuclear process problem rather than a mineral-resource problem', 'native promethium is not encountered in ordinary natural systems'),
      isotopes: facts('radioisotopes such as promethium-145 and promethium-147', 'promethium has no stable isotopes', 'its isotope chemistry determines essentially all scientific and technological relevance', 'promethium-147 has been used in luminous paints, gauges, and small power applications', 'all promethium chemistry requires radiological controls and decay-aware logistics'),
      production: facts('nuclear-fission recovery and isotope production routes', 'supply depends entirely on radiochemical production rather than mining', 'separation from fission-product mixtures is the core industrial challenge', 'high radiochemical purity is essential for source applications', 'availability is limited by nuclear infrastructure and isotope-handling economics'),
      applied: facts('radiochemical tracing, historical luminous devices, thickness gauges, and small nuclear-power concepts', 'promethium radioisotopes, promethium salts, and sealed source materials', 'promethium is important because it is the only lanthanide with no stable isotope and therefore sits at the boundary between lanthanide chemistry and applied radiochemistry', 'its use remained niche because radioactivity brings utility together with strict handling burden', 'hazards are inseparable from radiation exposure, contamination control, and isotope-specific decay behavior'),
    },
  }),
  makeSeed({
    id: 'samarium',
    name: 'Samarium',
    symbol: 'Sm',
    atomicNumber: 62,
    atomicMass: '150.36',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f6 6s2',
    oxidationStates: '+2, +3',
    summaryLine:
      'Samarium is a lanthanide whose Sm3+ chemistry dominates, while Sm2+ and selected isotopes make it important in magnets, absorbers, and geochronology.',
    importanceLine:
      'Its chemistry links rare-earth trivalency to redox-active Sm(II), neutron absorption, and the powerful Sm-Nd isotope system.',
    heroFacts: ['Lanthanide metal', 'Sm3+ dominates chemistry', 'Used in Sm-Co magnets', 'Important in Sm-Nd dating'],
    glossaryExtras: [
      term('Samarium-cobalt magnet', 'A high-performance permanent magnet based on samarium and cobalt compounds.'),
      term('Sm-Nd dating', 'A geochronological method based on decay of samarium isotopes to neodymium.'),
      term('Lanthanide contraction', 'Gradual decrease in lanthanide ionic size across the series.'),
    ],
    sections: {
      classification: facts('a lanthanide rare-earth metal whose chemistry is mostly trivalent but with useful divalent exceptions', 'period 6, lanthanide series, f-block', '[Xe]4f6 6s2', 'it forms hard Sm3+ salts while Sm2+ can appear in more reducing environments', 'its chemistry is more redox-flexible than many neighboring lanthanides and especially important in isotope geochemistry'),
      electronic: facts('an [Xe]4f6 6s2 valence arrangement', 'it forms mainly Sm3+ compounds with selected Sm2+ chemistry in strongly reducing systems', '+2 and +3', 'samarium oxides, halides, Sm-Co magnet phases, and reducing Sm2+ reagents or salts', '4f-electron structure gives magnetic and spectroscopic behavior while rare Sm2+ adds chemical contrast'),
      physical: facts('a silvery rare-earth metal', 'it oxidizes in air and is more often handled as oxide, salt, or alloy than as exposed bulk metal', 'reactive rare-earth metallic bonding explains softness and oxidation tendency', 'samarium metal, oxide powders, magnet materials, and neutron-absorber compounds', 'powders and fresh surfaces require controlled handling because of oxidation and dust concerns'),
      reactivity: facts('a reactive lanthanide forming stable Sm3+ oxides, halides, and salts with selected Sm2+ reducing chemistry', 'it reacts like a typical rare-earth metal while some compounds can act as reductants or specialized magnetic materials', 'stabilization of Sm3+ dominates, but partial access to Sm2+ broadens the chemistry', 'oxides, halides, magnet phases, neutron absorbers, and reductive samarium compounds', 'hazards are moderate and centered on powders, rare-earth processing, and specialized reducing compounds'),
      occurrence: facts('bastnasite, monazite, and mixed rare-earth concentrates', 'it is a moderately abundant lanthanide obtained through rare-earth separation rather than distinct major ores', 'mixed rare-earth mineral concentrates are the practical reservoir', 'samarium supply follows the economics of rare-earth separation and magnet materials', 'native samarium does not occur because oxidized mineral forms dominate'),
      isotopes: facts('multiple isotopes including samarium-147, 148, 149, 150, 152, and 154', 'natural samarium contains several isotopes, with samarium-147 especially important because it is long lived and radioactive', 'isotopes make samarium central to geochronology and neutron-capture science', 'Sm-Nd dating and reactor-neutron studies are major isotope applications', 'samarium isotope chemistry gives the element importance beyond ordinary materials use'),
      production: facts('separation from bastnasite and monazite concentrates followed by oxide or salt purification', 'production depends on standard rare-earth separation rather than on standalone samarium mines', 'solvent extraction and precipitation dominate refining', 'purity matters for magnets, absorbers, and isotope-related applications', 'supply is linked to the broader rare-earth market and specialized high-performance materials'),
      applied: facts('samarium-cobalt magnets, neutron absorbers, catalysts, and isotope geochronology', 'samarium oxides, samarium halides, Sm-Co magnets, and samarium-containing absorber materials', 'samarium is important because it combines rare-earth magnet chemistry with an unusually valuable isotope system', 'its technological role grew through high-temperature magnets and geochronological science', 'hazards are moderate and tied to powders, process chemicals, and neutron or isotope applications where relevant'),
    },
  }),
  makeSeed({
    id: 'europium',
    name: 'Europium',
    symbol: 'Eu',
    atomicNumber: 63,
    atomicMass: '151.964',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f7 6s2',
    oxidationStates: '+2, +3',
    summaryLine:
      'Europium is a lanthanide famous for intense luminescence and for the unusual accessibility of both Eu2+ and Eu3+ chemistry in phosphors and advanced optical materials.',
    importanceLine:
      'Its chemistry links half-filled 4f stability to redox contrast, phosphor performance, and selected neutron-related applications.',
    heroFacts: ['Lanthanide phosphor element', 'Eu2+ and Eu3+ are both important', 'Strong red and blue luminescence', 'Recovered with rare earths'],
    glossaryExtras: [
      term('Phosphor', 'A material that emits light after excitation, often relying on rare-earth activator ions.'),
      term('Activator ion', 'A dopant ion such as europium that creates luminescent centers in a host lattice.'),
      term('Half-filled shell', 'A comparatively stable electron configuration, relevant to europium and gadolinium chemistry.'),
    ],
    sections: {
      classification: facts('a lanthanide rare-earth metal whose chemistry prominently features both +2 and +3 states', 'period 6, lanthanide series, f-block', '[Xe]4f7 6s2', 'it forms hard Eu3+ salts and unusually accessible Eu2+ compounds important in luminescent materials', 'its chemistry is more redox-flexible and optically important than that of many neighboring lanthanides'),
      electronic: facts('an [Xe]4f7 6s2 valence arrangement', 'it forms both Eu2+ and Eu3+ compounds because the half-filled 4f7 configuration stabilizes divalent europium', '+2 and +3', 'europium oxides, halides, phosphor-doped host lattices, and specialized luminescent materials', '4f-electron transitions and the stability of Eu2+ or Eu3+ create unusually useful optical behavior'),
      physical: facts('a soft reactive rare-earth metal', 'it oxidizes readily and is generally encountered through compounds, doped materials, and oxide forms rather than exposed metal', 'reactive rare-earth metallic bonding and rapid oxide formation govern handling', 'europium metal, europium oxide, and europium-doped phosphor hosts', 'powders and fresh surfaces require controlled handling because oxidation is rapid'),
      reactivity: facts('a reactive lanthanide forming stable Eu3+ salts and notable Eu2+ compounds under reducing conditions', 'it participates in oxide, halide, and host-lattice chemistry strongly shaped by redox state', 'stabilization of Eu2+ by the half-filled 4f shell and of Eu3+ in oxidizing settings drives the chemistry', 'phosphor hosts, oxides, halides, and redox-sensitive luminescent materials', 'hazards are moderate and mainly associated with powders, process chemicals, and rare-earth manufacturing'),
      occurrence: facts('bastnasite, monazite, and mixed rare-earth mineral concentrates', 'it is less abundant than some light rare earths but commercially important because of phosphor and optical demand', 'mixed rare-earth concentrates are the practical reservoir', 'europium supply depends on difficult rare-earth separation and demand for display or lighting materials', 'native europium does not occur because oxidized mineral-bound forms dominate'),
      isotopes: facts('stable europium-151 and europium-153', 'both principal naturally occurring isotopes are stable', 'isotopic composition is useful in analytical chemistry and nuclear-related studies', 'europium isotopes support tracing and specialized materials analysis', 'ordinary europium chemistry is defined more by luminescence and redox state than by isotope complexity'),
      production: facts('separation from mixed rare-earth concentrates followed by purification into oxides, salts, or dopant-grade materials', 'industrial production depends on demanding rare-earth separations and high-purity finishing', 'solvent extraction and precipitation remain the dominant refining strategies', 'extreme purity is critical because phosphor performance is sensitive to contamination', 'supply is closely tied to rare-earth separation economics and phosphor demand'),
      applied: facts('phosphors, display and lighting materials, anti-counterfeiting markers, and specialized nuclear or optical systems', 'europium oxides, europium halides, Eu-doped phosphors, and luminescent host materials', 'europium is important because its redox states and sharp 4f emissions make it one of the signature luminescent rare earths', 'its technological prominence rose with color television, fluorescent lighting, and later advanced optical materials', 'hazards are moderate and center on powders, dopant processing, and standard rare-earth industrial exposure'),
    },
  }),
];
