import type { ElementSeed, SectionKey } from '@/content/subjects/chemistry/elementSeeds';
import {
  appliedSection,
  classificationSection,
  electronicSection,
  isotopeSection,
  occurrenceSection,
  physicalSection,
  productionSection,
  reactivitySection,
  term,
  type FactSet,
} from '@/content/subjects/chemistry/seedFactories';

type SeedConfig = Omit<ElementSeed, 'sections'> & { sections: Record<SectionKey, FactSet> };

function facts(a: string, b: string, c: string, d: string, e: string): FactSet {
  return [a, b, c, d, e];
}

function makeSeed(config: SeedConfig): ElementSeed {
  return {
    ...config,
    sections: {
      classification: classificationSection(config.name, config.sections.classification),
      electronic: electronicSection(config.name, config.sections.electronic),
      physical: physicalSection(config.name, config.sections.physical),
      reactivity: reactivitySection(config.name, config.sections.reactivity),
      occurrence: occurrenceSection(config.name, config.sections.occurrence),
      isotopes: isotopeSection(config.name, config.sections.isotopes),
      production: productionSection(config.name, config.sections.production),
      applied: appliedSection(config.name, config.sections.applied),
    },
  };
}

export const latePeriodSixElementSeeds: ElementSeed[] = [
  makeSeed({
    id: 'gadolinium',
    name: 'Gadolinium',
    symbol: 'Gd',
    atomicNumber: 64,
    atomicMass: '157.25',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f7 5d1 6s2',
    oxidationStates: '+3',
    summaryLine:
      'Gadolinium is a lanthanide distinguished by strong magnetism, useful Gd3+ chemistry, and exceptional neutron-absorption behavior that supports medical and nuclear technologies.',
    importanceLine:
      'Its chemistry links rare-earth trivalency to MRI contrast agents, neutron capture, phosphors, and high-moment magnetic materials.',
    heroFacts: ['Lanthanide metal', 'Gd3+ dominates chemistry', 'Strong magnetic behavior', 'Important neutron absorber'],
    glossaryExtras: [
      term('MRI contrast agent', 'A compound that alters magnetic relaxation properties to improve magnetic resonance imaging.'),
      term('Neutron capture', 'Absorption of a neutron by a nucleus, important in gadolinium applications.'),
      term('Scintillator', 'A material that emits light when exposed to ionizing radiation.'),
    ],
    sections: {
      classification: facts('a lanthanide rare-earth metal with strongly trivalent chemistry and unusual magnetic prominence', 'period 6, lanthanide series, f-block', '[Xe]4f7 5d1 6s2', 'it forms hard Gd3+ compounds while the half-filled 4f shell gives especially notable magnetic behavior', 'its chemistry is more magnetically distinctive than that of many neighboring lanthanides'),
      electronic: facts('an [Xe]4f7 5d1 6s2 valence arrangement', 'it forms mainly Gd3+ compounds in which the half-filled 4f shell dominates magnetic properties', '+3', 'gadolinium oxides, halides, chelates, phosphor hosts, and neutron-absorbing materials', 'the half-filled 4f shell gives particularly strong paramagnetism and helps define its applications'),
      physical: facts('a silvery reactive rare-earth metal', 'it is best known physically for strong paramagnetism and use in magnetic or neutron-sensitive materials', 'rare-earth metallic bonding and 4f-electron magnetism shape its physical profile', 'gadolinium metal, chelate complexes, phosphor materials, and shielding additives', 'powders and reactive surfaces require the same oxidation control common to rare-earth metals'),
      reactivity: facts('a reactive lanthanide forming stable Gd3+ oxides, halides, and coordination compounds', 'it behaves chemically like a hard trivalent rare earth while its complexes can be functionally important in medicine', 'stabilization of Gd3+ and hard-donor coordination drives the chemistry', 'oxides, halides, chelates, phosphor hosts, and neutron-absorbing compounds', 'gadolinium chemistry is ordinarily moderate in hazard, but complex stability matters greatly in biomedical use'),
      occurrence: facts('bastnasite, monazite, and mixed rare-earth concentrates', 'it is a middle lanthanide obtained through the general rare-earth separation industry', 'mixed rare-earth mineral concentrates are the practical reservoir', 'supply depends on rare-earth separations rather than dedicated gadolinium ores', 'native gadolinium does not occur because oxidized mineral-bound forms dominate'),
      isotopes: facts('multiple stable isotopes including gadolinium-155 and gadolinium-157', 'natural gadolinium contains several isotopes, with 155 and 157 especially notable for very high neutron capture', 'isotopes strongly influence nuclear and imaging applications', 'gadolinium isotopes are important in reactor control, neutron detection, and isotopic science', 'gadolinium isotope behavior is unusually consequential for an otherwise trivalent rare-earth element'),
      production: facts('separation from mixed rare-earth concentrates followed by purification to oxide, salt, or metal forms', 'industrial production depends on difficult lanthanide separations and high-purity finishing', 'solvent extraction and precipitation dominate the refining routes', 'purity control is critical for medical, optical, and nuclear applications', 'supply is tied to the broader rare-earth market and specialized demand'),
      applied: facts('MRI contrast chemistry, neutron absorbers, phosphors, magnets, and scintillator materials', 'gadolinium chelates, gadolinium oxide, phosphor hosts, and neutron-sensitive compounds', 'gadolinium is important because its 4f-electron magnetism and isotope behavior create applications unmatched by most lanthanides', 'its modern significance rose through imaging, nuclear technology, and luminescent materials', 'hazards are moderate in industrial use but biomedical safety depends on keeping gadolinium in stable chelated form'),
    },
  }),
  makeSeed({
    id: 'terbium',
    name: 'Terbium',
    symbol: 'Tb',
    atomicNumber: 65,
    atomicMass: '158.92535',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f9 6s2',
    oxidationStates: '+3, +4',
    summaryLine:
      'Terbium is a lanthanide whose Tb3+ chemistry and green luminescence make it valuable in phosphors, magnetostrictive materials, and specialized optical systems.',
    importanceLine:
      'Its chemistry links rare-earth trivalency to phosphor performance, high-field magnetism, and selected Tb4+ oxide chemistry.',
    heroFacts: ['Lanthanide metal', 'Tb3+ dominates chemistry', 'Strong green phosphor ion', 'Used in magnetostrictive alloys'],
    glossaryExtras: [
      term('Magnetostriction', 'A change in dimension of a material in response to magnetization.'),
      term('Terfenol-D', 'A magnetostrictive alloy containing terbium, dysprosium, and iron.'),
      term('Activator ion', 'A dopant ion such as terbium that creates luminescent centers.'),
    ],
    sections: {
      classification: facts('a lanthanide rare-earth metal with mainly trivalent chemistry and useful optical behavior', 'period 6, lanthanide series, f-block', '[Xe]4f9 6s2', 'it forms hard Tb3+ compounds with selected Tb4+ oxide chemistry in strong oxidizing settings', 'its chemistry is especially associated with green emission and magnetic materials'),
      electronic: facts('an [Xe]4f9 6s2 valence arrangement', 'it forms mainly Tb3+ compounds whose 4f electrons give characteristic luminescence and magnetism', '+3 and +4', 'terbium oxides, halides, phosphor hosts, and magnetostrictive alloys', '4f-electron transitions make terbium one of the key green-emitting rare-earth activators'),
      physical: facts('a silvery reactive rare-earth metal', 'it is ordinarily encountered through its compounds and functional materials rather than exposed bulk metal', 'reactive rare-earth metallic bonding and 4f-electron magnetism shape the physical profile', 'terbium metal, oxide powders, phosphor materials, and magnetostrictive alloys', 'powders and fresh metal require controlled handling because oxidation is rapid'),
      reactivity: facts('a reactive lanthanide forming stable Tb3+ salts and oxides with some higher-valent oxide chemistry', 'it reacts like a typical rare earth while also supporting luminescent host-lattice and magnetic-material chemistry', 'stabilization of Tb3+ and oxide formation drives most reactions', 'oxides, halides, phosphor hosts, magnetostrictive materials, and selected Tb4+ compounds', 'hazards are moderate and center on dusts, powders, and standard rare-earth industrial exposure'),
      occurrence: facts('bastnasite, monazite, xenotime, and mixed rare-earth concentrates', 'it is less abundant than the light rare earths and is obtained only through careful lanthanide separation', 'mixed rare-earth mineral concentrates are the practical reservoir', 'terbium supply is constrained by rarity and by phosphor or magnet demand', 'native terbium does not occur because oxidized mineral forms dominate'),
      isotopes: facts('stable terbium-159 together with selected radioisotopes', 'terbium-159 is the only stable isotope', 'isotope work is useful in nuclear research and some specialized medical science', 'radioisotopes of terbium are studied for imaging and therapy applications', 'ordinary terbium chemistry is far more influenced by luminescence than by isotope diversity'),
      production: facts('separation from mixed rare-earth concentrates followed by purification to oxide or salt forms', 'industrial production depends on difficult high-resolution lanthanide separation', 'solvent extraction is the main industrial refining method', 'high purity is essential for phosphors and magnetostrictive materials', 'supply is tightly linked to the economics of scarce heavy rare-earth separation'),
      applied: facts('green phosphors, magnetostrictive alloys, optical materials, and specialized nuclear or medical research', 'terbium oxides, terbium halides, phosphor hosts, and Terfenol-D materials', 'terbium is important because its 4f-electron behavior delivers particularly valuable green emission and magnetic responses', 'its technological prominence rose through display phosphors and smart-material systems', 'hazards are moderate and mostly associated with powders, dopant processing, and rare-earth supply constraints'),
    },
  }),
  makeSeed({
    id: 'dysprosium',
    name: 'Dysprosium',
    symbol: 'Dy',
    atomicNumber: 66,
    atomicMass: '162.500',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f10 6s2',
    oxidationStates: '+3',
    summaryLine:
      'Dysprosium is a lanthanide valued for strong magnetic behavior, neutron absorption, and its role in improving high-temperature permanent magnets.',
    importanceLine:
      'Its chemistry links trivalent rare-earth behavior to strategic magnet supply and specialized control or optical applications.',
    heroFacts: ['Lanthanide metal', 'Dy3+ dominates chemistry', 'Used in high-temperature magnets', 'Strong neutron absorber'],
    glossaryExtras: [
      term('High-coercivity magnet', 'A magnet that resists demagnetization under heat or opposing fields.'),
      term('Heavy rare earth', 'A later lanthanide that is often scarcer and harder to separate than the light rare earths.'),
      term('Neutron absorber', 'A material that captures neutrons efficiently in reactors or detectors.'),
    ],
    sections: {
      classification: facts('a heavy lanthanide rare-earth metal with strongly trivalent chemistry', 'period 6, lanthanide series, f-block', '[Xe]4f10 6s2', 'it forms hard Dy3+ compounds and is especially important in magnetic materials', 'its chemistry is less redox-variable than terbium but highly significant in strategic magnet engineering'),
      electronic: facts('an [Xe]4f10 6s2 valence arrangement', 'it forms mainly Dy3+ compounds whose 4f electrons give strong magnetic anisotropy and optical features', '+3', 'dysprosium oxides, halides, magnet additives, and neutron-absorbing compounds', '4f-electron behavior makes dysprosium valuable in heat-resistant magnetic materials'),
      physical: facts('a silvery reactive rare-earth metal', 'it is usually encountered as oxide, salt, or alloy additive rather than exposed bulk metal', 'reactive rare-earth metallic bonding and 4f-electron magnetism shape the physical profile', 'dysprosium metal, oxide powders, magnet additives, and neutron-control materials', 'powders and fresh surfaces oxidize readily and need controlled handling'),
      reactivity: facts('a reactive lanthanide forming stable Dy3+ oxides, halides, and salts', 'it behaves chemically as a typical trivalent heavy rare earth while contributing to magnetic and nuclear materials', 'stabilization of Dy3+ and oxide formation dominate the chemistry', 'oxides, fluorides, chlorides, magnetic alloys, and neutron-absorbing compounds', 'hazards are moderate and mostly related to dusts, powders, and rare-earth processing'),
      occurrence: facts('xenotime and mixed heavy-rare-earth concentrates together with bastnasite or ion-adsorption clays in some supply chains', 'it is scarcer than the light lanthanides and supply can be strategically constrained', 'heavy rare-earth concentrates are the main practical reservoir', 'dysprosium availability is shaped strongly by separation difficulty and magnet demand', 'native dysprosium does not occur because mineral-bound oxidized forms dominate'),
      isotopes: facts('multiple stable isotopes including dysprosium-156, 158, 160, 161, 162, 163, and 164', 'natural dysprosium contains several stable isotopes', 'isotopic behavior matters in analytical and nuclear science more than in routine materials use', 'dysprosium isotopes support tracing and neutron-related studies', 'ordinary dysprosium chemistry is dominated more by magnetic applications than by isotope effects'),
      production: facts('separation from heavy rare-earth concentrates followed by purification to oxide or metal forms', 'industrial production depends on difficult heavy-lanthanide separation rather than bulk ore abundance', 'solvent extraction and precipitation dominate refining', 'high purity is essential for magnetic applications where small additions matter greatly', 'supply is tied to heavy-rare-earth availability and strategic materials markets'),
      applied: facts('high-temperature permanent magnets, neutron absorbers, lasers, and specialty optical materials', 'dysprosium oxides, halides, magnet additives, and neutron-control materials', 'dysprosium is important because it can stabilize magnet performance under heat and field stress', 'its strategic profile rose with modern motors, wind systems, and advanced electronics', 'hazards are moderate and center on powders, process chemicals, and supply-chain scarcity rather than unusual chemical violence'),
    },
  }),
  makeSeed({
    id: 'holmium',
    name: 'Holmium',
    symbol: 'Ho',
    atomicNumber: 67,
    atomicMass: '164.93033',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f11 6s2',
    oxidationStates: '+3',
    summaryLine:
      'Holmium is a lanthanide known for very high magnetic moment, Ho3+ chemistry, and specialized uses in lasers, magnets, and neutron-related materials.',
    importanceLine:
      'Its chemistry links heavy lanthanide trivalency to magnetic extremes and optical niche applications.',
    heroFacts: ['Lanthanide metal', 'Ho3+ dominates chemistry', 'Very high magnetic moment', 'Used in specialty lasers'],
    glossaryExtras: [
      term('Magnetic moment', 'A measure of magnetic strength arising from electron configuration.'),
      term('Rare-earth laser ion', 'A lanthanide ion used as the active center in solid-state laser materials.'),
      term('Heavy rare earth', 'A later lanthanide often produced through difficult separation from similar ions.'),
    ],
    sections: {
      classification: facts('a heavy lanthanide rare-earth metal with predominantly trivalent chemistry', 'period 6, lanthanide series, f-block', '[Xe]4f11 6s2', 'it forms hard Ho3+ compounds and is especially notable for magnetic strength rather than oxidation-state diversity', 'its chemistry is more niche in application than that of dysprosium or erbium but distinctly magnetic'),
      electronic: facts('an [Xe]4f11 6s2 valence arrangement', 'it forms mainly Ho3+ compounds whose 4f electrons give strong magnetic and optical signatures', '+3', 'holmium oxides, halides, laser-host dopants, and magnetic materials', 'shielded 4f electrons preserve characteristic spectra and magnetic behavior in host lattices'),
      physical: facts('a silvery reactive rare-earth metal', 'it is physically notable for very large magnetic moment and is usually handled via compounds or doped materials', 'rare-earth metallic bonding and 4f-electron magnetism shape the physical profile', 'holmium metal, oxide powders, laser crystals, and specialty magnets', 'powders and fresh metal require controlled handling because oxidation is rapid'),
      reactivity: facts('a reactive lanthanide forming stable Ho3+ oxides, halides, and salts', 'it follows the usual heavy rare-earth trivalent chemistry in air, acids, and salts', 'stabilization of Ho3+ and oxide formation drive its chemistry', 'oxides, fluorides, chlorides, laser dopants, and magnetic materials', 'hazards are moderate and centered on powders, dusts, and rare-earth industrial processing'),
      occurrence: facts('xenotime and mixed heavy-rare-earth concentrates', 'it is relatively scarce and obtained only through specialized heavy-lanthanide separation', 'heavy rare-earth mineral concentrates are the practical reservoir', 'holmium supply follows heavy rare-earth separation economics rather than broad ore abundance', 'native holmium does not occur because oxidized mineral forms dominate'),
      isotopes: facts('stable holmium-165 together with selected radioisotopes', 'holmium-165 is the only stable isotope', 'radioisotopes are useful in specialized medicine and nuclear research', 'holmium radioisotopes are studied for therapy and analytical applications', 'routine holmium chemistry is shaped more by magnetism and optics than by isotope diversity'),
      production: facts('separation from heavy rare-earth concentrates into purified oxide or salt forms', 'industrial production depends on difficult lanthanide separations from similar heavy rare-earth ions', 'solvent extraction is the dominant refining route', 'purity is important for laser, magnetic, and research applications', 'supply is constrained by scarcity and the complexity of heavy-rare-earth separation'),
      applied: facts('specialty lasers, magnetic materials, neutron absorbers, and research optics', 'holmium oxides, holmium halides, and holmium-doped laser hosts', 'holmium is important because its magnetic moment and optical transitions create niche but valuable functions', 'its use remained specialized rather than bulk, centered on precision optical and magnetic systems', 'hazards are moderate and mainly associated with powders, process chemicals, and isotope-specific work'),
    },
  }),
  makeSeed({
    id: 'erbium',
    name: 'Erbium',
    symbol: 'Er',
    atomicNumber: 68,
    atomicMass: '167.259',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f12 6s2',
    oxidationStates: '+3',
    summaryLine:
      'Erbium is a lanthanide whose Er3+ optical transitions make it indispensable in fiber-optic amplification, lasers, and specialty glass coloration.',
    importanceLine:
      'Its chemistry links heavy rare-earth trivalency to one of the most commercially important telecommunications ions.',
    heroFacts: ['Lanthanide metal', 'Er3+ dominates chemistry', 'Critical in fiber amplifiers', 'Important laser dopant'],
    glossaryExtras: [
      term('EDFA', 'Erbium-doped fiber amplifier, a key optical amplifier in telecommunications.'),
      term('Laser dopant', 'A small amount of ion added to a host material to produce laser action.'),
      term('Host lattice', 'A solid material that accommodates dopant ions such as erbium.'),
    ],
    sections: {
      classification: facts('a heavy lanthanide rare-earth metal with strongly trivalent chemistry', 'period 6, lanthanide series, f-block', '[Xe]4f12 6s2', 'it forms hard Er3+ compounds best known for optical rather than redox behavior', 'its chemistry is especially important in photonics rather than bulk magnet applications'),
      electronic: facts('an [Xe]4f12 6s2 valence arrangement', 'it forms mainly Er3+ compounds whose 4f-electron transitions are especially useful in optical hosts', '+3', 'erbium oxides, halides, fiber dopants, and laser-host materials', 'shielded 4f transitions allow sharp optical behavior even inside complex solids'),
      physical: facts('a silvery reactive rare-earth metal', 'it is usually encountered through oxide powders and doped optical materials rather than as exposed metal', 'reactive rare-earth metallic bonding and 4f-electron spectroscopy shape its physical significance', 'erbium metal, erbium oxide, fiber dopants, and laser crystals', 'powders and fresh surfaces require controlled handling because oxidation is rapid'),
      reactivity: facts('a reactive lanthanide forming stable Er3+ oxides, halides, and salts', 'it follows standard heavy rare-earth trivalent chemistry while enabling powerful optical functions in host lattices', 'stabilization of Er3+ and oxide formation dominate the chemistry', 'oxides, fluorides, chlorides, fiber dopants, and laser-host materials', 'hazards are moderate and mostly associated with powders, rare-earth processing, and optical-material manufacture'),
      occurrence: facts('xenotime and mixed heavy-rare-earth concentrates', 'it is obtained through heavy-lanthanide separation rather than dedicated bulk ore extraction', 'heavy rare-earth concentrates are the practical reservoir', 'erbium supply is tied to separation capacity and demand from photonics materials', 'native erbium does not occur because mineral-bound oxidized forms dominate'),
      isotopes: facts('multiple stable isotopes including erbium-162, 164, 166, 167, 168, and 170', 'natural erbium contains several stable isotopes', 'isotopic effects are less central than optical behavior but still useful analytically', 'erbium isotopes support tracing and specialized materials analysis', 'ordinary erbium chemistry is dominated by optical transitions rather than isotope complexity'),
      production: facts('separation from heavy rare-earth concentrates followed by oxide or salt purification', 'industrial production depends on demanding separation from chemically similar heavy lanthanides', 'solvent extraction is the principal industrial refining method', 'high purity is essential because optical amplification is sensitive to contamination', 'supply is tied to heavy-rare-earth processing and telecommunications materials demand'),
      applied: facts('fiber-optic amplifiers, lasers, specialty glasses, and optical materials', 'erbium oxide, erbium halides, erbium-doped fibers, and laser-host materials', 'erbium is important because its 4f-electron transitions match a core telecommunications wavelength window', 'its technological importance rose with long-distance fiber-optic communication', 'hazards are moderate and mainly associated with powders, dopant manufacture, and high-purity materials processing'),
    },
  }),
  makeSeed({
    id: 'thulium',
    name: 'Thulium',
    symbol: 'Tm',
    atomicNumber: 69,
    atomicMass: '168.93422',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f13 6s2',
    oxidationStates: '+2, +3',
    summaryLine:
      'Thulium is a scarce lanthanide whose Tm3+ chemistry and specialized optical transitions support niche lasers, portable X-ray sources, and research materials.',
    importanceLine:
      'Its chemistry links heavy rare-earth trivalency to uncommon divalent behavior and highly specialized optical technology.',
    heroFacts: ['Scarce lanthanide', 'Tm3+ dominates chemistry', 'Specialized laser ion', 'Used in selected X-ray sources'],
    glossaryExtras: [
      term('Portable X-ray source', 'A compact radiation source that can employ certain radioisotopes or rare-earth systems.'),
      term('Heavy rare earth', 'A later lanthanide with comparatively scarce supply and difficult separations.'),
      term('Tm-doped laser', 'A laser system whose active ion is thulium.'),
    ],
    sections: {
      classification: facts('a scarce heavy lanthanide whose chemistry is mainly trivalent with selected divalent exceptions', 'period 6, lanthanide series, f-block', '[Xe]4f13 6s2', 'it forms hard Tm3+ compounds and occasional Tm2+ species in reducing settings', 'its chemistry is more specialized and less bulk-commercial than that of erbium or ytterbium'),
      electronic: facts('an [Xe]4f13 6s2 valence arrangement', 'it forms mainly Tm3+ compounds whose 4f transitions are useful in niche optical systems', '+2 and +3', 'thulium oxides, halides, laser-host dopants, and selected reduced compounds', '4f-electron structure supports characteristic emission behavior and some limited divalent chemistry'),
      physical: facts('a silvery reactive rare-earth metal', 'it is usually encountered in purified compounds or doped host materials rather than bulk-metal articles', 'reactive rare-earth metallic bonding and optical 4f behavior shape its significance', 'thulium metal, oxide powders, and thulium-doped optical materials', 'powders and fresh surfaces require controlled handling because oxidation is rapid'),
      reactivity: facts('a reactive lanthanide forming stable Tm3+ oxides, halides, and salts with selected Tm2+ chemistry', 'it follows standard heavy rare-earth chemistry while supporting specialized optical host-lattice applications', 'stabilization of Tm3+ and oxide formation drive most reactions', 'oxides, halides, laser dopants, and selected reduced thulium compounds', 'hazards are moderate and chiefly associated with powders, process chemicals, and specialized isotope use'),
      occurrence: facts('xenotime and mixed heavy-rare-earth concentrates', 'it is among the scarcer lanthanides and is produced only in small quantities', 'heavy rare-earth concentrates are the practical reservoir', 'supply depends on difficult separation from very similar neighboring lanthanides', 'native thulium does not occur because oxidized mineral forms dominate'),
      isotopes: facts('stable thulium-169 together with radioisotopes such as thulium-170', 'thulium-169 is the only stable isotope', 'radioisotopes contribute to specialized radiation-source and research applications', 'thulium radioisotopes are used in compact X-ray-source and analytical contexts', 'ordinary thulium chemistry is more constrained by scarcity than by isotope diversity'),
      production: facts('separation from heavy rare-earth concentrates into purified oxide or salt forms', 'industrial production depends on high-resolution lanthanide separation rather than direct ore extraction', 'solvent extraction and precipitation dominate refining', 'high purity is essential for optical applications and research materials', 'supply is tightly constrained by rarity and heavy-rare-earth separation economics'),
      applied: facts('specialty lasers, radiation sources, and research optical materials', 'thulium oxides, halides, radioisotopes, and thulium-doped laser hosts', 'thulium is important because it provides niche optical and radiological functions not easily replaced in certain systems', 'its use remained specialized because scarcity and cost limit broad deployment', 'hazards are moderate and mainly associated with powders, isotope-specific work, and high-purity materials processing'),
    },
  }),
  makeSeed({
    id: 'ytterbium',
    name: 'Ytterbium',
    symbol: 'Yb',
    atomicNumber: 70,
    atomicMass: '173.045',
    group: 'Lanthanide series',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 6s2',
    oxidationStates: '+2, +3',
    summaryLine:
      'Ytterbium is a lanthanide whose closed 4f shell makes Yb2+ unusually accessible and whose Yb3+ ions are important in lasers, clocks, and optical materials.',
    importanceLine:
      'Its chemistry links late-lanthanide behavior to divalent rare-earth chemistry, high-performance photonics, and precision metrology.',
    heroFacts: ['Late lanthanide metal', 'Yb2+ and Yb3+ both matter', 'Important in lasers and clocks', 'Recovered with heavy rare earths'],
    glossaryExtras: [
      term('Optical lattice clock', 'A precision clock that can use ytterbium atoms as the frequency reference.'),
      term('Yb-doped fiber', 'An optical fiber containing ytterbium ions for laser or amplifier action.'),
      term('Closed 4f shell', 'The filled 4f14 electron configuration relevant to ytterbium chemistry.'),
    ],
    sections: {
      classification: facts('a late lanthanide rare-earth metal with both +2 and +3 chemistry', 'period 6, lanthanide series, f-block', '[Xe]4f14 6s2', 'it forms hard Yb3+ compounds while the filled 4f shell makes Yb2+ more accessible than in many lanthanides', 'its chemistry is more redox-flexible than erbium and more optically important than many late lanthanides'),
      electronic: facts('an [Xe]4f14 6s2 valence arrangement', 'it forms both Yb2+ and Yb3+ compounds because the filled 4f14 shell stabilizes divalent behavior', '+2 and +3', 'ytterbium oxides, halides, Yb-doped fibers, and clock-related atomic systems', 'the closed 4f shell strongly shapes redox preferences and precision optical behavior'),
      physical: facts('a soft silvery reactive rare-earth metal', 'it is commonly encountered through purified salts, oxides, and optical dopant materials rather than bulk-metal articles', 'reactive rare-earth metallic bonding and late-lanthanide electron structure shape its physical role', 'ytterbium metal, oxide powders, doped fibers, and atomic-vapor systems', 'fresh surfaces and powders require controlled handling because oxidation proceeds readily'),
      reactivity: facts('a reactive lanthanide forming stable Yb3+ salts and useful Yb2+ compounds in reducing environments', 'it follows standard rare-earth oxidation chemistry while supporting redox states valuable in photonics and fundamental studies', 'stabilization of Yb2+ and Yb3+ across different environments drives the chemistry', 'oxides, halides, doped optical hosts, and selected divalent ytterbium compounds', 'hazards are moderate and mainly associated with powders, process chemicals, and high-purity materials work'),
      occurrence: facts('xenotime and mixed heavy-rare-earth concentrates', 'it is obtained through heavy rare-earth separation rather than through large dedicated ores', 'heavy rare-earth concentrates are the practical reservoir', 'ytterbium supply depends on separation capacity and demand from optical technologies', 'native ytterbium does not occur because oxidized mineral forms dominate'),
      isotopes: facts('multiple stable isotopes including ytterbium-168, 170, 171, 172, 173, 174, and 176', 'natural ytterbium contains several stable isotopes', 'isotopes matter in precision metrology, spectroscopy, and analytical chemistry', 'ytterbium isotopes are important in optical clocks, quantum science, and tracing', 'ordinary ytterbium chemistry is notable partly because isotope choice can matter in precision-physics applications'),
      production: facts('separation from heavy rare-earth concentrates followed by purification to oxide, salt, or metal forms', 'industrial production depends on demanding lanthanide separations from chemically similar neighbors', 'solvent extraction and precipitation dominate refining', 'high purity is essential for photonics and precision atomic applications', 'supply is tied to heavy-rare-earth separation economics and specialized optical demand'),
      applied: facts('fiber lasers, optical clocks, quantum systems, specialty alloys, and research materials', 'ytterbium oxides, halides, Yb-doped fibers, and atomic-vapor systems', 'ytterbium is important because it combines useful divalent chemistry with world-class photonic and metrological applications', 'its modern prominence rose through high-power fiber lasers and precision frequency standards', 'hazards are moderate and center on powders, process chemicals, and the demands of high-purity optical manufacture'),
    },
  }),
  makeSeed({
    id: 'lutetium',
    name: 'Lutetium',
    symbol: 'Lu',
    atomicNumber: 71,
    atomicMass: '174.9668',
    group: '3',
    period: '6',
    block: 'f',
    category: 'Lanthanide',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d1 6s2',
    oxidationStates: '+3',
    summaryLine:
      'Lutetium is the final lanthanide, valued for stable Lu3+ chemistry, dense oxide materials, and the medical and detector importance of selected isotopes and compounds.',
    importanceLine:
      'Its chemistry links the end of the lanthanide series to scintillators, radiopharmaceuticals, and the close transition from f-block to hafnium chemistry.',
    heroFacts: ['Final lanthanide', 'Lu3+ dominates chemistry', 'Important in scintillators', 'Lu-177 is medically important'],
    glossaryExtras: [
      term('LSO', 'Lutetium oxyorthosilicate, a scintillator material used in radiation detection.'),
      term('Lu-177 therapy', 'Radiopharmaceutical treatment using lutetium-177.'),
      term('Lanthanide contraction', 'Progressive shrinkage of lanthanide ionic radii across the series, ending near lutetium.'),
    ],
    sections: {
      classification: facts('the final lanthanide rare-earth metal, dominated by hard trivalent chemistry', 'period 6, group 3 / lanthanide series, f-block', '[Xe]4f14 5d1 6s2', 'it forms stable Lu3+ compounds and marks the transition from lanthanide to hafnium chemistry', 'its chemistry is less optically prominent than erbium or ytterbium but very important in dense oxide and isotope applications'),
      electronic: facts('an [Xe]4f14 5d1 6s2 valence arrangement', 'it forms mainly Lu3+ compounds with a filled 4f shell and a compact trivalent ion', '+3', 'lutetium oxides, halides, scintillator hosts, and radiopharmaceutical compounds', 'the compact Lu3+ ion reflects the end of the lanthanide contraction and influences coordination behavior'),
      physical: facts('a dense silvery rare-earth metal', 'it is among the densest lanthanides and is usually encountered through oxides, salts, and specialty materials', 'late-lanthanide metallic bonding and the compact ion size shape its physical profile', 'lutetium metal, oxide powders, scintillators, and isotope-target materials', 'powders and fresh surfaces require controlled handling because oxidation is rapid'),
      reactivity: facts('a reactive lanthanide forming stable Lu3+ oxides, halides, and salts', 'it follows normal trivalent rare-earth chemistry rather than broad redox variation', 'stabilization of the compact Lu3+ ion and oxide formation drive the chemistry', 'oxides, fluorides, chlorides, scintillator hosts, and radiopharmaceutical precursors', 'hazards are moderate and mostly associated with powders, isotope-specific work, and rare-earth processing'),
      occurrence: facts('xenotime and mixed heavy-rare-earth concentrates', 'it is among the scarcer lanthanides and is obtained only through advanced rare-earth separations', 'heavy rare-earth concentrates are the practical reservoir', 'lutetium supply is constrained by rarity and separation difficulty', 'native lutetium does not occur because oxidized mineral-bound forms dominate'),
      isotopes: facts('stable lutetium-175 together with long-lived lutetium-176 and therapeutic lutetium-177', 'natural lutetium contains one stable and one very long-lived isotope, while lutetium-177 is a key radioisotope', 'isotope chemistry gives lutetium strong medical and geochemical importance', 'lutetium isotopes are used in therapy, dating, and detector science', 'lutetium is unusual in combining heavy-rare-earth chemistry with major applied isotope significance'),
      production: facts('separation from heavy rare-earth concentrates followed by purification into oxide, salt, or metal forms', 'industrial production depends on the most demanding parts of lanthanide separation', 'solvent extraction and precipitation are the core refining tools', 'high purity is essential for scintillators and radiopharmaceutical precursors', 'supply is limited by scarcity and the complexity of heavy-rare-earth processing'),
      applied: facts('scintillators, radiopharmaceuticals, catalysts, and specialty research materials', 'lutetium oxides, lutetium halides, LSO scintillators, and lutetium radioisotope compounds', 'lutetium is important because dense Lu-containing materials and Lu isotopes have high value in imaging and therapy', 'its prominence rose with PET detectors and targeted radiopharmaceutical development', 'hazards are moderate for ordinary compounds but higher for isotope-handling and high-purity processing'),
    },
  }),
  makeSeed({
    id: 'hafnium',
    name: 'Hafnium',
    symbol: 'Hf',
    atomicNumber: 72,
    atomicMass: '178.49',
    group: '4',
    period: '6',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d2 6s2',
    oxidationStates: '+4',
    summaryLine:
      'Hafnium is a dense refractory transition metal whose Hf4+ chemistry, oxide stability, and neutron absorption make it important in nuclear and microelectronic materials.',
    importanceLine:
      'Its chemistry parallels zirconium closely while diverging industrially through strong neutron capture and high-k dielectric applications.',
    heroFacts: ['Refractory transition metal', 'Hf4+ dominates chemistry', 'Strong neutron absorber', 'Important in high-k oxides'],
    glossaryExtras: [
      term('High-k dielectric', 'An insulating material with high dielectric constant, such as hafnium oxide in microelectronics.'),
      term('Control rod', 'A neutron-absorbing device used to regulate nuclear reactors.'),
      term('Zirconium-hafnium pair', 'A chemically similar pair of elements that are difficult to separate industrially.'),
    ],
    sections: {
      classification: facts('a refractory group-4 transition metal with strong tetravalent oxide chemistry', 'group 4, period 6, d-block', '[Xe]4f14 5d2 6s2', 'it forms Hf4+ compounds and closely parallels zirconium in most ordinary chemistry', 'its chemistry differs industrially because hafnium captures neutrons strongly and is valuable in electronics'),
      electronic: facts('an [Xe]4f14 5d2 6s2 valence arrangement', 'it forms oxides, halides, and coordination compounds centered on Hf4+', '+4', 'HfO2, HfCl4, hafnates, and high-k dielectric thin films', 'vacant d orbitals and strong oxygen affinity make oxide and Lewis-acid chemistry central'),
      physical: facts('a dense refractory metallic solid', 'it combines high melting point with chemical durability and useful high-temperature behavior', 'strong metallic bonding and oxide passivation shape its physical behavior', 'hafnium metal, hafnia ceramics, thin-film dielectrics, and nuclear control materials', 'bulk metal is manageable, but powders and high-temperature processing require greater care'),
      reactivity: facts('a reactive refractory metal thermodynamically, moderated in practice by stable oxide films', 'fresh metal reacts with oxygen and halogens while bulk material shows good corrosion resistance under many conditions', 'formation of highly stable HfO2 drives much of the chemistry', 'oxides, halides, hafnates, dielectric films, and control-rod materials', 'powders and hot metal require oxidation and fire control despite the stability of passivated bulk material'),
      occurrence: facts('zircon-derived ores and minerals together with zirconium feedstocks', 'hafnium is not mined separately in most cases but accompanies zirconium in natural minerals', 'zircon concentrates are the main practical reservoir', 'hafnium occurrence is inseparable from zirconium geology and separation chemistry', 'native hafnium does not occur because oxide and silicate forms are far more stable'),
      isotopes: facts('multiple stable isotopes including hafnium-174, 176, 177, 178, 179, and 180', 'natural hafnium contains several stable isotopes', 'isotopes matter in nuclear science and geochemistry more than in routine handling', 'hafnium isotopes support reactor science and Hf-W geochemical studies', 'ordinary hafnium chemistry is influenced more by zirconium separation and oxide behavior than by isotope issues'),
      production: facts('separation from zirconium streams followed by chloride or related refining routes', 'industrial supply depends on difficult Zr-Hf separation before metal or oxide finishing', 'chloride chemistry and oxygen-free reduction routes are major production steps', 'purity control is essential for nuclear and microelectronic applications', 'supply depends on zircon processing and the economics of high-purity separation'),
      applied: facts('control rods, high-k dielectrics, superalloys, plasmas, and refractory materials', 'hafnium metal, hafnium oxide, hafnium halides, and thin-film dielectric materials', 'hafnium is important because it combines zirconium-like chemistry with stronger neutron absorption and advanced electronic utility', 'its modern prominence rose with nuclear control materials and semiconductor gate-dielectric technology', 'hazards are moderate and center on powders, halide intermediates, and high-temperature processing'),
    },
  }),
  makeSeed({
    id: 'tantalum',
    name: 'Tantalum',
    symbol: 'Ta',
    atomicNumber: 73,
    atomicMass: '180.94788',
    group: '5',
    period: '6',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d3 6s2',
    oxidationStates: '+5',
    summaryLine:
      'Tantalum is a refractory transition metal prized for chemical resistance, stable oxide films, capacitor technology, and high-performance alloys.',
    importanceLine:
      'Its chemistry links group-5 oxide stability to coltan ore processing, corrosion-resistant equipment, and miniaturized electronics.',
    heroFacts: ['Refractory transition metal', 'Ta5+ chemistry dominates', 'Highly corrosion resistant', 'Important in capacitors'],
    glossaryExtras: [
      term('Coltan', 'A commercial ore term for columbite-tantalite minerals containing tantalum and niobium.'),
      term('Tantalum capacitor', 'A compact capacitor built around tantalum metal and tantalum oxide dielectric layers.'),
      term('Passivation', 'Formation of a protective surface film that suppresses further corrosion.'),
    ],
    sections: {
      classification: facts('a refractory group-5 transition metal with strongly favored pentavalent oxide chemistry', 'group 5, period 6, d-block', '[Xe]4f14 5d3 6s2', 'it forms stable Ta5+ compounds and extremely durable oxide-coated metal surfaces', 'its chemistry parallels niobium but is even more corrosion resistant and technologically focused on capacitors and high-end materials'),
      electronic: facts('an [Xe]4f14 5d3 6s2 valence arrangement', 'it forms oxides, halides, and coordination compounds centered on Ta5+', '+5', 'Ta2O5, tantalum halides, tantalates, and capacitor-grade tantalum metal', 'strong oxygen affinity and stable high oxidation state dominate both chemistry and materials use'),
      physical: facts('a dense hard refractory metallic solid', 'it withstands high temperatures and many corrosive media while remaining useful in fabricated components', 'strong metallic bonding and protective oxide films shape its physical durability', 'tantalum metal, porous capacitor anodes, tantalum carbide, and corrosion-resistant process equipment', 'bulk metal is comparatively stable, but powders and high-temperature processes require more control'),
      reactivity: facts('a refractory metal whose ordinary behavior is strongly moderated by passivating oxide films', 'it resists many acids and corrosive environments, while fresh or hot surfaces can form stable oxides and halides', 'formation of very stable tantalum oxides drives the chemistry', 'oxides, halides, tantalates, carbides, and capacitor-dielectric systems', 'hazards are moderate for bulk metal but greater for powders, fluorides, and aggressive high-temperature processing'),
      occurrence: facts('tantalite and columbite-tantalite minerals together with complex pegmatites and placer deposits', 'it is relatively scarce and commonly recovered from mixed tantalum-niobium ores', 'coltan-related ore concentrates are the dominant commercial reservoir', 'tantalum supply depends on ore beneficiation and the separation of tantalum from niobium', 'native tantalum does not occur because oxide mineral forms are strongly favored'),
      isotopes: facts('stable tantalum-181 together with the extremely rare long-lived tantalum-180m state', 'tantalum-181 is the principal naturally occurring isotope', 'isotopic behavior is scientifically interesting even though routine chemistry uses essentially one stable isotope', 'tantalum isotopes matter in nuclear science and precise analytical work', 'ordinary tantalum chemistry is dominated more by materials behavior and supply-chain issues than by isotope diversity'),
      production: facts('refining of coltan and related concentrates followed by separation, fluoride or chloride chemistry, and metal reduction', 'industrial production depends on difficult separation from niobium and high-purity finishing', 'oxide, fluoride, and chloride intermediates are used in purification and metal production', 'purity control is essential for capacitor-grade powder and high-temperature alloys', 'supply is sensitive to ore geography, ethical sourcing, and electronics demand'),
      applied: facts('electronic capacitors, corrosion-resistant process equipment, superalloys, carbides, and medical implants', 'tantalum metal, tantalum oxide, tantalum carbide, halides, and tantalate materials', 'tantalum is important because its passivating oxide and refractory metal properties support compact reliable electronics and harsh-service hardware', 'its strategic significance rose with miniaturized electronics and high-performance industrial equipment', 'hazards are moderate and center on powders, fluoride chemistry, and supply-chain or processing constraints rather than ordinary corrosion'),
    },
  }),
  makeSeed({
    id: 'tungsten',
    name: 'Tungsten',
    symbol: 'W',
    atomicNumber: 74,
    atomicMass: '183.84',
    group: '6',
    period: '6',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d4 6s2',
    oxidationStates: '+2, +4, +6',
    summaryLine:
      'Tungsten is a refractory transition metal with the highest melting point of any pure metal, important in hard materials, high-temperature components, and tungsten(VI) oxide chemistry.',
    importanceLine:
      'Its chemistry links refractory metallic bonding to tungstates, carbides, lighting history, and extreme-service engineering.',
    heroFacts: ['Highest-melting pure metal', 'Refractory transition metal', 'Important in carbides and alloys', 'Forms tungstates and WO3'],
    glossaryExtras: [
      term('Wolframite', 'An iron-manganese tungstate mineral and a major tungsten ore.'),
      term('Tungstate', 'An oxyanion family derived from tungsten(VI), often written around WO4 units.'),
      term('Tungsten carbide', 'A very hard tungsten compound used in cutting and wear-resistant tools.'),
    ],
    sections: {
      classification: facts('a refractory group-6 transition metal with strong high-temperature and high-valent oxide chemistry', 'group 6, period 6, d-block', '[Xe]4f14 5d4 6s2', 'it forms metallic tungsten together with oxides, tungstates, and hard carbides of major industrial importance', 'its chemistry extends molybdenum-like group-6 behavior into far more refractory territory'),
      electronic: facts('an [Xe]4f14 5d4 6s2 valence arrangement', 'it forms compounds and metallic phases across several oxidation states, with tungsten(VI) especially important in oxides and tungstates', '+2, +4, and +6', 'WO3, tungstates, tungsten halides, tungsten carbide, and high-temperature alloys', 'partially filled d orbitals and strong W-O bonding give both refractory metal behavior and rich oxide chemistry'),
      physical: facts('a dense hard refractory metallic solid', 'it has the highest melting point of any pure metal and retains strength at very high temperature', 'exceptionally strong metallic bonding explains its refractory character and density', 'tungsten filaments, heavy alloys, tungsten carbide tools, and high-temperature components', 'bulk metal is manageable, but powders, hardmetal processing, and very high-temperature work require careful control'),
      reactivity: facts('a relatively unreactive refractory metal at room temperature whose chemistry becomes important through oxides, halides, and carbides', 'it resists many ordinary conditions yet forms strong oxides and hard compounds under suitable oxidizing or reactive environments', 'formation of stable W-O and W-C bonds drives much of the chemistry', 'tungsten oxides, tungstates, halides, carbides, and catalytic or electrochromic materials', 'hazards are usually tied to dusts, high-temperature processes, and hardmetal-related occupational exposure'),
      occurrence: facts('wolframite, scheelite, and related tungstate ores', 'it is not abundant in crustal average terms but is concentrated well enough in tungstate minerals for major mining', 'scheelite and wolframite deposits are the dominant commercial reservoir', 'tungsten occurrence is controlled by stable tungstate mineral chemistry', 'native tungsten does not occur because oxide and tungstate mineral forms are far more stable'),
      isotopes: facts('multiple stable isotopes including tungsten-180, 182, 183, 184, and 186', 'natural tungsten contains several stable isotopes', 'isotope chemistry supports geochronology, analytical science, and Hf-W cosmochemical studies', 'tungsten isotopes are important in planetary science and high-precision tracing', 'ordinary tungsten chemistry is governed more by refractory behavior and carbides than by isotope effects'),
      production: facts('beneficiation of wolframite and scheelite concentrates followed by oxide conversion and metal or carbide production', 'industrial production usually passes through tungsten oxide intermediates before final metal or carbide formation', 'ammonium paratungstate and oxide reduction routes are major refining steps', 'purity control is essential for hardmetals, filaments, and high-performance alloys', 'supply depends on ore concentration, strategic materials demand, and energy-intensive processing'),
      applied: facts('hardmetal tools, high-temperature alloys, electrodes, radiation shielding, catalysts, and electrochromic materials', 'tungsten metal, tungsten carbide, tungsten oxides, tungstates, and heavy alloys', 'tungsten is important because extreme refractory behavior and hard-compound chemistry enable tools and components few other elements can match', 'its industrial profile spans lighting history, armaments, machining, and modern hardmetals', 'hazards are moderate and center on powder inhalation, hardmetal processing, and very high-temperature manufacturing'),
    },
  }),
];
