import type { ElementSeed, SectionKey } from '@/content/subjects/chemistry/elementSeeds';
import {
  appliedSection,
  classificationSection,
  electronicSection,
  isotopeSection,
  occurrenceSection,
  physicalSection,
  productionSection,
  reactivitySection,
  term,
  type FactSet,
} from '@/content/subjects/chemistry/seedFactories';

type SeedConfig = Omit<ElementSeed, 'sections'> & { sections: Record<SectionKey, FactSet> };

function facts(a: string, b: string, c: string, d: string, e: string): FactSet {
  return [a, b, c, d, e];
}

function makeSeed(config: SeedConfig): ElementSeed {
  return {
    ...config,
    sections: {
      classification: classificationSection(config.name, config.sections.classification),
      electronic: electronicSection(config.name, config.sections.electronic),
      physical: physicalSection(config.name, config.sections.physical),
      reactivity: reactivitySection(config.name, config.sections.reactivity),
      occurrence: occurrenceSection(config.name, config.sections.occurrence),
      isotopes: isotopeSection(config.name, config.sections.isotopes),
      production: productionSection(config.name, config.sections.production),
      applied: appliedSection(config.name, config.sections.applied),
    },
  };
}

export const latePeriodFiveElementSeeds: ElementSeed[] = [
  makeSeed({
    id: 'palladium',
    name: 'Palladium',
    symbol: 'Pd',
    atomicNumber: 46,
    atomicMass: '106.42',
    group: '10',
    period: '5',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d10',
    oxidationStates: '+2, +4',
    summaryLine:
      'Palladium is a platinum-group metal whose surface chemistry, hydrogen affinity, and catalytic versatility make it central to synthesis, emissions control, and electronics.',
    importanceLine:
      'Its chemistry links noble-metal durability to highly active catalytic cycles, hydrogen sorption, and the economics of scarce platinum-group elements.',
    heroFacts: ['Platinum-group metal', 'Excellent catalyst metal', 'Absorbs hydrogen', 'Recovered from PGM streams'],
    glossaryExtras: [
      term('Hydrogen sorption', 'Absorption or adsorption of hydrogen by a solid such as palladium.'),
      term('Cross-coupling', 'Catalytic carbon-carbon bond-forming chemistry often associated with palladium.'),
      term('PGM refinery', 'A metallurgical process stream used to separate platinum-group metals.'),
    ],
    sections: {
      classification: facts('a noble group-10 transition metal within the platinum-group family', 'group 10, period 5, d-block', '[Kr]4d10', 'it forms catalytic complexes and surface species despite a relatively noble metallic character', 'its chemistry is less oxidation-state-diverse than ruthenium but especially important in catalysis and hydrogen handling'),
      electronic: facts('a [Kr]4d10 valence arrangement in the neutral atom', 'it forms coordination compounds and catalytic intermediates in which Pd(II) and Pd(0) behavior is especially important', '+2 and +4 in many simple descriptions, with Pd(0) central in catalysis', 'palladium metal, PdCl2, organopalladium catalysts, and hydrogen-loaded palladium phases', 'filled d-shell tendencies coexist with unusually useful metal-ligand and surface interactions'),
      physical: facts('a silvery noble metal', 'it is dense, ductile, and unusually capable of taking up hydrogen', 'noble metallic bonding and a receptive metal lattice support durability and hydrogen sorption', 'palladium foils, catalyst powders, plated contacts, and hydrogen-related materials', 'bulk metal is easy to handle, but fine powders and catalyst residues require routine control'),
      reactivity: facts('a relatively noble metal whose practical chemistry is dominated by catalytic activation rather than bulk corrosion', 'it activates hydrogen, alkenes, carbon-halogen bonds, and other substrates in catalytic cycles', 'surface adsorption and reversible oxidation-state changes drive much of the chemistry', 'hydrogenation catalysts, cross-coupling catalysts, palladium halides, and oxidation catalysts', 'catalyst powders, soluble salts, and hydrogen service conditions require more attention than the bulk metal itself'),
      occurrence: facts('nickel-copper sulfide ores, platinum-group deposits, and refinery byproduct streams', 'it is rare in crustal abundance but economically important because of catalytic demand', 'PGM concentrates and refinery residues are the main practical reservoirs', 'palladium occurrence follows platinum-group mineralogy rather than simple bulk abundance', 'native palladium can occur but is uncommon and not the basis of most supply'),
      isotopes: facts('multiple stable isotopes including palladium-102, 104, 105, 106, 108, and 110', 'several naturally occurring palladium isotopes are stable', 'isotope patterns support analytical chemistry, cosmochemistry, and specialized nuclear work', 'palladium isotopes are useful in tracing and high-precision measurement', 'routine palladium chemistry is controlled more by catalytic performance and scarcity than by isotope issues'),
      production: facts('recovery during refining of platinum-group metal concentrates and nickel-copper ores', 'supply depends on complex refinery separations rather than dedicated large palladium mines in most cases', 'chloride chemistry, selective precipitation, and solvent extraction are common refining strategies', 'purity is critical because palladium is often used catalytically or electronically', 'availability depends strongly on PGM mining, recycling, and automotive catalyst markets'),
      applied: facts('catalysis, hydrogenation, electronics, dentistry, sensors, and emissions control', 'palladium metal, palladium chlorides, supported catalysts, and alloy materials', 'palladium is important because small amounts can deliver highly selective catalytic behavior and hydrogen interactions', 'its industrial prominence expanded sharply with organic cross-coupling and automotive emission control', 'hazards are moderate and tied mainly to powders, soluble salts, and process-specific catalyst exposure'),
    },
  }),
  makeSeed({
    id: 'silver',
    name: 'Silver',
    symbol: 'Ag',
    atomicNumber: 47,
    atomicMass: '107.8682',
    group: '11',
    period: '5',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d10 5s1',
    oxidationStates: '+1',
    summaryLine:
      'Silver is a noble coinage metal celebrated for conductivity, reflectivity, and rich Ag+ chemistry in photography, antimicrobial materials, and electronics.',
    importanceLine:
      'Its chemistry connects coinage-metal stability to halide precipitation, surface tarnish, coordination chemistry, and high-value conductive materials.',
    heroFacts: ['Coinage metal', 'Highest electrical conductivity', 'Ag+ chemistry is central', 'Native silver can occur'],
    glossaryExtras: [
      term('Tarnish', 'A dark surface film, often silver sulfide, formed on silver exposed to sulfur-containing environments.'),
      term('Silver halide', 'A light-sensitive compound of silver with a halogen, central to classical photography.'),
      term('Sterling silver', 'A traditional silver-copper alloy used in objects and jewelry.'),
    ],
    sections: {
      classification: facts('a noble group-11 transition metal often described as a coinage metal', 'group 11, period 5, d-block', '[Kr]4d10 5s1', 'it combines metallic nobility with a characteristic Ag+ ionic chemistry', 'its chemistry is less redox-active than copper and less inertly expensive than gold'),
      electronic: facts('an [Kr]4d10 5s1 valence arrangement', 'it forms metallic silver and many compounds centered on Ag+ with significant coordination chemistry', '+1 in most ordinary compounds', 'AgCl, Ag2O, silver complexes with ammonia or cyanide, and metallic silver', 'filled d-shell behavior supports strong conductivity while still permitting useful soft-acid coordination chemistry'),
      physical: facts('a lustrous white noble metal', 'it has the highest electrical and thermal conductivity of any element and excellent reflectivity', 'metallic bonding in a face-centered-cubic lattice supports conductivity and ductility', 'silver wire, silver films, mirrors, coins, and sterling alloys', 'bulk silver is easy to handle, though surface tarnish and some salt exposures matter in practice'),
      reactivity: facts('a relatively unreactive metal that nonetheless forms useful silver(I) compounds and surface films', 'it reacts readily with sulfur-containing species and precipitates insoluble halides from solution', 'stabilization of Ag+ in suitable ligands and of very insoluble salts drives much of its chemistry', 'silver halides, oxide, coordination complexes, plating baths, and catalytic surfaces', 'soluble silver salts and fine powders demand more care than bulk noble metal'),
      occurrence: facts('native silver, argentite-type minerals, lead-zinc ores, and copper-related deposits', 'it is much rarer than base metals but can occur in native form because of its relative nobility', 'sulfide ores and polymetallic deposits are the main commercial reservoirs', 'silver often follows lead, zinc, copper, and gold mineral systems', 'native silver can persist in nature because the metal is less reactive than many common structural metals'),
      isotopes: facts('silver-107 and silver-109', 'both principal naturally occurring isotopes are stable', 'isotopic composition supports analytical chemistry and environmental tracing', 'stable-isotope work and nuclear-analytical studies use silver isotope information', 'ordinary silver chemistry is governed far more by Ag+ reactions and nobility than by isotope effects'),
      production: facts('recovery from lead, zinc, copper, and gold refining streams together with direct silver ore treatment', 'industrial silver supply is often byproduct-driven rather than based only on pure silver mining', 'smelting, cyanidation, electrorefining, and selective precipitation are common routes', 'purity control matters for electronics, mirrors, and bullion products', 'supply depends strongly on both precious-metal markets and byproduct base-metal refining'),
      applied: facts('electronics, mirrors, jewelry, coinage, photography history, antimicrobial products, and catalysis', 'silver metal, silver nitrate, silver halides, silver oxide, and coordination complexes', 'silver is important because it combines noble-metal stability with unmatched conductivity and useful ionic chemistry', 'its history spans money, decoration, imaging, and modern electronic materials', 'hazards are moderate and center on soluble salts, waste recovery chemistry, and occupational exposure to fine particulates'),
    },
  }),
  makeSeed({
    id: 'cadmium',
    name: 'Cadmium',
    symbol: 'Cd',
    atomicNumber: 48,
    atomicMass: '112.414',
    group: '12',
    period: '5',
    block: 'd',
    category: 'D-block metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d10 5s2',
    oxidationStates: '+2',
    summaryLine:
      'Cadmium is a soft d-block metal whose Cd2+ chemistry, historical pigments, battery uses, and serious toxicity make it chemically useful but tightly regulated.',
    importanceLine:
      'Its chemistry connects filled-d-shell metal behavior to zinc-processing byproducts, semiconductors, electrochemistry, and environmental toxicology.',
    heroFacts: ['Recovered with zinc', 'Cd2+ chemistry dominates', 'Important in CdTe and NiCd history', 'Highly toxic metal'],
    glossaryExtras: [
      term('Greenockite', 'Cadmium sulfide mineral, a rare direct cadmium source.'),
      term('Cadmium telluride', 'A compound semiconductor used in photovoltaic technology.'),
      term('Bioaccumulation', 'Progressive buildup of a substance such as cadmium within organisms or food webs.'),
    ],
    sections: {
      classification: facts('a filled-d-shell d-block metal with strongly favored divalent chemistry', 'group 12, period 5, d-block', '[Kr]4d10 5s2', 'it forms Cd2+ compounds with important coordination, semiconductor, and toxicological behavior', 'its chemistry resembles zinc and mercury but carries especially strong environmental concern'),
      electronic: facts('an [Kr]4d10 5s2 valence arrangement', 'it forms mostly Cd2+ compounds with significant soft-acid coordination tendencies', '+2', 'CdS, CdCl2, cadmium oxide, cadmium telluride, and solvated Cd2+ species', 'filled d-shell behavior suppresses multivalent redox diversity but not strong biological and environmental consequences'),
      physical: facts('a soft bluish-white metallic solid', 'it is relatively low melting and easy to work, but many practical forms are now restricted because of toxicity', 'metallic bonding and a filled-d-shell metal lattice explain softness and good workability', 'cadmium metal, electroplated coatings, battery materials, and CdTe semiconductors', 'dust, fumes, and soluble compounds require strict hygiene control'),
      reactivity: facts('a moderately reactive metal forming stable Cd2+ salts, sulfides, oxides, and coordination compounds', 'it dissolves in acids, forms insoluble sulfides, and participates in electrochemical and semiconductor chemistry', 'stabilization of Cd2+ and strong bonding to sulfur and soft donor ligands drive much of its behavior', 'cadmium sulfide pigments, cadmium oxide, plating baths, and CdTe materials', 'toxicity dominates practical hazard assessment more than spectacular chemical violence'),
      occurrence: facts('trace substitution in sphalerite and other zinc ores, with only minor direct cadmium minerals', 'it is obtained mainly as a byproduct rather than mined as a large standalone commodity', 'zinc concentrates and zinc-smelting streams are the dominant reservoirs', 'cadmium follows zinc geochemistry and can become an environmental contaminant when released from ores or wastes', 'native cadmium does not occur naturally because sulfide and oxide forms are more stable'),
      isotopes: facts('multiple stable isotopes together with very long-lived cadmium-113', 'natural cadmium contains several isotopes that are stable or effectively stable for chemical purposes', 'isotopic composition is useful in environmental tracing and nuclear science', 'cadmium isotopes support analytical chemistry, reactor science, and pollution studies', 'routine cadmium chemistry is governed much more by toxicity than by isotope effects'),
      production: facts('recovery from zinc-smelting and refining streams', 'industrial cadmium supply depends on selective byproduct separation rather than direct mining', 'distillation, precipitation, and electrolytic or chemical refining are common routes', 'purity control is important for semiconductors and specialized electrochemical uses', 'supply is constrained as much by regulation and environmental control as by metal demand'),
      applied: facts('historical pigments, nickel-cadmium batteries, control materials, coatings, and cadmium telluride photovoltaics', 'cadmium metal, cadmium sulfide, cadmium oxide, cadmium telluride, and cadmium salts', 'cadmium is important because it combines distinctive electrochemical and semiconductor behavior with strong toxicological relevance', 'its industrial history includes major pigment and battery use followed by tighter regulation', 'major hazards are chronic toxicity, kidney damage risk, inhalation of fumes, and contamination of soils or food webs'),
    },
  }),
  makeSeed({
    id: 'indium',
    name: 'Indium',
    symbol: 'In',
    atomicNumber: 49,
    atomicMass: '114.818',
    group: '13',
    period: '5',
    block: 'p',
    category: 'Post-transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d10 5s2 5p1',
    oxidationStates: '+1, +3',
    summaryLine:
      'Indium is a soft post-transition metal whose low melting point and transparent-conductor compounds make it central to display technology, solders, and semiconductor materials.',
    importanceLine:
      'Its chemistry links heavy group-13 behavior to indium tin oxide, byproduct metal recovery, and niche alloys or compounds for electronics.',
    heroFacts: ['Very soft metal', 'In3+ chemistry dominates', 'Important in ITO coatings', 'Recovered mainly from zinc processing'],
    glossaryExtras: [
      term('ITO', 'Indium tin oxide, a transparent conducting oxide widely used in displays and touchscreens.'),
      term('Transparent conductor', 'A material that combines electrical conductivity with optical transparency.'),
      term('Byproduct metal', 'A metal recovered mainly during processing of another major ore stream.'),
    ],
    sections: {
      classification: facts('a heavy group-13 post-transition metal with dominant trivalent chemistry', 'group 13, period 5, p-block', '[Kr]4d10 5s2 5p1', 'it forms In3+ compounds together with lower-valent chemistry in some soft-ligand and alloy systems', 'its chemistry is softer and more metallic than gallium while still supporting useful semiconductor compounds'),
      electronic: facts('an [Kr]4d10 5s2 5p1 valence arrangement', 'it forms mostly In3+ compounds with some In+ and metal-rich bonding in selected systems', '+1 and +3, with +3 dominant', 'In2O3, indium halides, indium tin oxide, and semiconductor compounds such as InP', 'heavy p-block behavior and a filled 4d shell support soft Lewis acidity and useful electronic materials'),
      physical: facts('a very soft silvery metal with a relatively low melting point', 'it can be cut easily and wets some surfaces, making it useful in solders and seals', 'comparatively weak metallic bonding contributes to softness and easy deformation', 'indium metal shots, low-melting alloys, and oxide coating materials', 'bulk metal is easy to handle, but high-purity fabrication requires contamination control'),
      reactivity: facts('a moderately reactive post-transition metal forming stable oxides, halides, and semiconductor compounds', 'it oxidizes in air over time and reacts with acids or halogens to form indium salts', 'stabilization of In3+ and oxide or semiconductor bonding drives much of the chemistry', 'indium oxide, halides, indium phosphide, and alloy or solder systems', 'hazards are moderate for the metal but increase for fine powders and process-specific semiconductor chemicals'),
      occurrence: facts('trace substitution in sphalerite and other zinc ores together with tin or copper processing residues', 'it is economically important because of technology demand, not because of abundant dedicated ore deposits', 'zinc smelting streams are the dominant commercial reservoir', 'indium supply depends strongly on byproduct recovery from larger base-metal operations', 'native indium does not occur because mineral-bound forms are more stable'),
      isotopes: facts('indium-113 and indium-115', 'indium-115 is naturally abundant and very weakly radioactive while indium-113 is stable', 'isotope behavior matters in precision analysis and selected nuclear applications', 'indium radioisotopes support tracing and diagnostic or research uses', 'ordinary indium chemistry is shaped much more by materials applications than by radiological issues'),
      production: facts('recovery from zinc-smelting and refining streams followed by purification to metal or high-purity compounds', 'supply depends on selective byproduct separation rather than large direct indium mines', 'solvent extraction, precipitation, electrorefining, and zone-refining approaches are used for high-purity products', 'trace-impurity removal is critical for transparent conductors and semiconductors', 'availability is closely tied to electronics demand and zinc-processing capacity'),
      applied: facts('transparent conductors, displays, photovoltaics, solders, semiconductors, and low-melting alloys', 'indium metal, indium tin oxide, indium phosphide, indium oxide, and solder alloys', 'indium is important because it helps deliver transparent conductivity and specialized semiconductor performance', 'its modern importance rose with flat-panel displays and touchscreen technology', 'hazards are generally moderate but include inhalation of indium-containing particulates in advanced manufacturing'),
    },
  }),
  makeSeed({
    id: 'tin',
    name: 'Tin',
    symbol: 'Sn',
    atomicNumber: 50,
    atomicMass: '118.710',
    group: '14',
    period: '5',
    block: 'p',
    category: 'Post-transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d10 5s2 5p2',
    oxidationStates: '+2, +4',
    summaryLine:
      'Tin is a soft post-transition metal whose two common oxidation states, useful alloys, and corrosion-resistant coatings make it technologically important far beyond its simple appearance.',
    importanceLine:
      'Its chemistry links heavy group-14 behavior to solders, tinplate, organotin compounds, and the structural consequences of allotropy.',
    heroFacts: ['Post-transition metal', 'Sn2+ and Sn4+ are common', 'Important in solders and tinplate', 'Derived mainly from cassiterite'],
    glossaryExtras: [
      term('Cassiterite', 'Tin dioxide mineral, SnO2, and the principal ore of tin.'),
      term('Tin pest', 'Low-temperature conversion of white metallic tin to brittle gray tin.'),
      term('Organotin compound', 'A compound containing covalent tin-carbon bonds, often used in synthesis or materials chemistry.'),
    ],
    sections: {
      classification: facts('a heavy group-14 post-transition metal showing stable +2 and +4 chemistry', 'group 14, period 5, p-block', '[Kr]4d10 5s2 5p2', 'it forms metallic tin together with oxidized compounds and organotin species', 'its chemistry is more metallic than germanium and more practical in bulk metallurgy than lead in many modern uses'),
      electronic: facts('an [Kr]4d10 5s2 5p2 valence arrangement', 'it forms compounds in which Sn2+ and Sn4+ both matter because inert-pair effects are present but not overwhelming', '+2 and +4', 'SnO, SnO2, tin halides, organotin compounds, and metallic tin', 'heavy p-block behavior and the ns2 pair help explain the coexistence of two common oxidation states'),
      physical: facts('a soft silvery metal with multiple allotropes', 'it is easily worked and can transform between metallic white tin and brittle gray tin under suitable conditions', 'metallic bonding explains ductility in white tin while allotropy explains unusual low-temperature behavior', 'tinplate, solder alloys, tin metal, and cassiterite-derived products', 'bulk tin is easy to handle, but temperature history and contamination can matter in alloy performance'),
      reactivity: facts('a moderately reactive post-transition metal forming stable oxides, halides, and covalent organotin compounds', 'it resists attack in many everyday settings yet reacts with strong oxidants, halogens, and suitable acids or bases', 'stabilization of Sn2+ or Sn4+ and oxide formation drives much of the chemistry', 'tin oxides, halides, solders, stannates, and organotin systems', 'hazards are moderate for the metal but can be much greater for some organotin compounds'),
      occurrence: facts('cassiterite and related oxide ores, often in placer deposits', 'it is sufficiently concentrated in selected oxide deposits to support major mining', 'cassiterite-rich veins and placer deposits are the dominant reservoirs', 'tin occurrence is controlled by durable oxide mineralogy and weathering concentration', 'native tin is essentially absent because oxide forms are more stable'),
      isotopes: facts('multiple stable isotopes including tin-112 through tin-124', 'tin has an unusually large number of stable isotopes', 'isotopic diversity makes tin useful in analytical chemistry and nuclear studies', 'stable-isotope and nuclear-analytical work both benefit from the rich isotope system of tin', 'routine tin chemistry is dominated more by alloying and oxidation-state behavior than by isotope concerns'),
      production: facts('reduction and refining of cassiterite concentrates', 'production is centered on oxide ores rather than sulfide-smelting chemistry', 'smelting, impurity removal, and high-purity metal refining are the main industrial routes', 'purity control is important for solders, coatings, and electronics', 'supply depends on ore grade, recycling, and changing solder or electronics markets'),
      applied: facts('solders, coatings, alloys, chemicals, and selected organotin or oxide materials', 'tin metal, tinplate, SnO2, tin halides, and organotin compounds', 'tin is important because it combines workable metallurgy with versatile +2 and +4 chemistry', 'its importance spans ancient bronze technology through modern lead-free soldering', 'hazards are generally moderate for metal and many salts but increase for some organotin compounds and process fumes'),
    },
  }),
  makeSeed({
    id: 'antimony',
    name: 'Antimony',
    symbol: 'Sb',
    atomicNumber: 51,
    atomicMass: '121.760',
    group: '15',
    period: '5',
    block: 'p',
    category: 'Metalloid',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d10 5s2 5p3',
    oxidationStates: '-3, +3, +5',
    summaryLine:
      'Antimony is a metalloid whose Sb(III) and Sb(V) chemistry supports flame-retardant systems, alloys, semiconductors, and important toxicological studies.',
    importanceLine:
      'Its chemistry links heavy pnictogen behavior to sulfide mineralogy, oxide additives, and the growing distinction between useful materials and regulated exposure.',
    heroFacts: ['Metalloid pnictogen', 'Sb3+ and Sb5+ are common', 'Used in flame-retardant systems', 'Derived mainly from stibnite'],
    glossaryExtras: [
      term('Stibnite', 'Antimony sulfide mineral, Sb2S3, and the principal ore of antimony.'),
      term('Antimonate', 'An Sb(V) oxyanion family related to oxidized antimony chemistry.'),
      term('Flame-retardant synergist', 'An additive that improves fire resistance in combination with other components.'),
    ],
    sections: {
      classification: facts('a heavy group-15 metalloid with important +3 and +5 chemistry', 'group 15, period 5, p-block', '[Kr]4d10 5s2 5p3', 'it forms covalent and ionic compounds, oxides, sulfides, and oxyanions across several oxidation states', 'its chemistry is more metallic than arsenic yet less metallic than bismuth'),
      electronic: facts('an [Kr]4d10 5s2 5p3 valence arrangement', 'it forms compounds shaped strongly by lone-pair effects and accessible oxidation-state changes', '-3, +3, and +5', 'Sb2O3, Sb2O5-related materials, antimony halides, sulfides, and semiconducting compounds', 'the inert-pair trend makes Sb(III) especially important in many real systems'),
      physical: facts('a brittle silvery metalloid', 'it is harder and more metallic-looking than arsenic but still brittle rather than ductile', 'covalent and semimetallic bonding explain brittleness and limited conductivity', 'antimony metal, antimony oxide powders, and lead-antimony alloy materials', 'dust control matters because inhalation and compound exposure are more significant than bulk-metal handling'),
      reactivity: facts('a moderately reactive metalloid forming oxides, sulfides, halides, and oxyanion species', 'it oxidizes under suitable conditions and participates in both reducing and oxidizing pnictogen chemistry', 'stabilization of Sb(III) and Sb(V) compounds drives much of its accessible behavior', 'antimony oxides, sulfides, halides, alloys, and semiconductor-related compounds', 'many antimony compounds require toxicological caution even when reactions are not especially violent'),
      occurrence: facts('stibnite and other sulfide ores together with polymetallic deposits', 'it is not abundant in crustal average terms but can be mined effectively from selected sulfide systems', 'sulfide ore bodies and smelter-related streams are the main practical reservoirs', 'antimony commonly follows sulfur-rich ore geology and can accompany lead, silver, or gold systems', 'native antimony is uncommon because sulfide and oxide forms are more stable'),
      isotopes: facts('stable antimony-121 and antimony-123', 'both principal naturally occurring isotopes are stable', 'isotopic composition supports analytical chemistry and environmental tracing', 'stable-antimony isotope work is useful in geochemistry and pollution studies', 'ordinary antimony chemistry is shaped more by oxidation state and toxicity than by isotope complexity'),
      production: facts('mining and smelting of stibnite and related sulfide concentrates', 'industrial production usually begins with sulfide ores that are roasted and reduced to oxide or metal intermediates', 'refining to antimony trioxide or metal are major industrial pathways', 'sulfur management and impurity removal are important process controls', 'supply depends on sulfide-ore economics and demand for flame-retardant or alloy additives'),
      applied: facts('flame-retardant systems, alloys, semiconductors, lead-acid battery materials, and specialty chemicals', 'antimony trioxide, antimony metal, antimony sulfide, and selected semiconductor compounds', 'antimony is important because heavy-pnictogen chemistry gives useful oxide and alloy behavior in small additions', 'its historical use spans metallurgy, pigments, medicine, and later flame-retardant chemistry', 'hazards center on compound toxicity, dust exposure, and controlled handling of industrial oxides'),
    },
  }),
  makeSeed({
    id: 'tellurium',
    name: 'Tellurium',
    symbol: 'Te',
    atomicNumber: 52,
    atomicMass: '127.60',
    group: '16',
    period: '5',
    block: 'p',
    category: 'Metalloid',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d10 5s2 5p4',
    oxidationStates: '-2, +4, +6',
    summaryLine:
      'Tellurium is a rare chalcogen metalloid whose alloying, thermoelectric, and photovoltaic roles make it important despite low abundance and byproduct supply.',
    importanceLine:
      'Its chemistry links heavy chalcogen behavior to byproduct metallurgy, semiconductor materials, and the contrast between useful electronic properties and relative scarcity.',
    heroFacts: ['Rare chalcogen metalloid', 'Recovered as a byproduct', 'Important in thermoelectrics and CdTe', 'Multiple oxidation states'],
    glossaryExtras: [
      term('Telluride', 'A compound containing tellurium in the formal -2 oxidation state.'),
      term('Thermoelectric material', 'A material able to convert heat differences into electrical voltage or the reverse.'),
      term('Anode slime', 'A refinery residue from electrorefining, often enriched in rare byproduct elements such as tellurium.'),
    ],
    sections: {
      classification: facts('a heavy group-16 metalloid with chalcogen redox chemistry and semimetallic behavior', 'group 16, period 5, p-block', '[Kr]4d10 5s2 5p4', 'it forms tellurides, oxides, and oxyanion species while also contributing to electronic materials', 'its chemistry is more metallic than selenium yet less metallic than polonium'),
      electronic: facts('an [Kr]4d10 5s2 5p4 valence arrangement', 'it forms two-electron bonds, chain or network structures, and oxidized oxyanion species typical of heavy chalcogens', '-2, +4, and +6', 'metal tellurides, tellurium dioxide, tellurites, tellurates, and CdTe', 'heavy chalcogen lone-pair behavior and covalent semimetallic bonding shape both inorganic and materials chemistry'),
      physical: facts('a brittle silvery metalloid', 'it shows semimetallic conductivity and is useful in selected electronic and thermoelectric materials', 'covalent chain or network structures explain brittleness and anisotropic physical behavior', 'elemental tellurium, cadmium telluride, and bismuth telluride-related materials', 'dusts and process residues require control because tellurium exposure can be biologically significant'),
      reactivity: facts('a moderately reactive heavy chalcogen forming tellurides, oxides, halides, and oxyanion species', 'it reacts with metals and oxidants to produce a broad range of reduced and oxidized compounds', 'strong Te-metal and Te-oxygen bonding across multiple oxidation states drives the chemistry', 'tellurides, TeO2, tellurites, tellurates, and organotellurium intermediates', 'hazards are moderate and include dust exposure and odor-causing metabolites from significant tellurium intake'),
      occurrence: facts('trace enrichment in sulfide ores, copper anode slimes, and some gold-related telluride minerals', 'it is rare and economically important mainly through byproduct recovery', 'copper-refining residues and telluride-bearing ores are the main practical reservoirs', 'tellurium occurrence is controlled by byproduct metallurgy more than by large dedicated ore bodies', 'native tellurium is uncommon because sulfide- or telluride-associated mineral forms dominate'),
      isotopes: facts('multiple stable isotopes including tellurium-120, 122, 123, 124, 125, 126, 128, and 130', 'natural tellurium contains several stable or extremely long-lived isotopes', 'isotope diversity makes tellurium important in analytical and rare-event physics studies', 'tellurium isotopes are used in nuclear measurements and double-beta-decay research', 'routine tellurium chemistry is governed more by materials applications than by isotope effects'),
      production: facts('recovery from copper-refining anode slimes and related byproduct streams', 'industrial supply depends on selective extraction from residues rather than on dedicated bulk tellurium mines', 'oxidation, precipitation, and reduction routes convert refinery residues into tellurium products', 'high purity is essential for photovoltaic and thermoelectric applications', 'availability depends strongly on copper refining and thin-film solar-material demand'),
      applied: facts('thermoelectrics, photovoltaics, alloying, vulcanization aids, and specialty chemicals', 'elemental tellurium, CdTe, bismuth tellurides, tellurium dioxide, and tellurium-containing alloys', 'tellurium is important because rare heavy-chalcogen chemistry enables valuable electronic and thermal properties', 'its modern importance rose with thermoelectrics and cadmium telluride solar technology', 'hazards center on compound exposure, dust management, and the need for careful recovery of scarce byproduct material'),
    },
  }),
  makeSeed({
    id: 'iodine',
    name: 'Iodine',
    symbol: 'I',
    atomicNumber: 53,
    atomicMass: '126.90447',
    group: '17',
    period: '5',
    block: 'p',
    category: 'Halogen',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d10 5s2 5p5',
    oxidationStates: '-1, +1, +5, +7',
    summaryLine:
      'Iodine is a heavy halogen whose iodide chemistry, biological thyroid role, and oxidized iodine compounds make it important in medicine, nutrition, and synthesis.',
    importanceLine:
      'Its chemistry links halogen trends to brine extraction, redox-active iodine species, antiseptics, and essential trace biology.',
    heroFacts: ['Heavy halogen', 'Iodide is biologically essential', 'Sublimes to violet vapor', 'Recovered from brines and caliche'],
    glossaryExtras: [
      term('Iodide', 'A compound or ion containing iodine in the formal -1 oxidation state.'),
      term('Iodate', 'An iodine(V) oxyanion family important in oxidation chemistry and iodized-salt formulations.'),
      term('Thyroid hormone', 'A hormone whose structure depends on organically bound iodine atoms.'),
    ],
    sections: {
      classification: facts('a heavy halogen nonmetal with accessible reduced and oxidized iodine chemistry', 'group 17, period 5, p-block', '[Kr]4d10 5s2 5p5', 'it readily forms iodide while also supporting oxidized oxyanions and interhalogen chemistry', 'its chemistry is less aggressively oxidizing than chlorine or bromine and more polarizable than either'),
      electronic: facts('an [Kr]4d10 5s2 5p5 valence arrangement', 'it forms one strongly polarized bond in many compounds and readily stabilizes I- in salts and biomolecules', '-1, +1, +5, and +7', 'I2, iodide salts, iodates, periodates, and organoiodine compounds', 'large size and polarizability make iodine particularly useful in soft-ligand and organic substitution chemistry'),
      physical: facts('a dark lustrous solid that sublimes to violet vapor', 'it is the least volatile common halogen solid in introductory chemistry yet still forms a conspicuous molecular vapor', 'molecular I2 with relatively strong intermolecular forces explains the solid state and sublimation behavior', 'crystalline iodine, tinctures, iodized salts, and radiological iodine preparations', 'vapors and concentrated oxidizing iodine preparations require controlled handling and ventilation'),
      reactivity: facts('a reactive halogen whose elemental oxidizing power is moderate compared with lighter halogens', 'it forms iodides readily and participates in redox, substitution, and antiseptic chemistry', 'stabilization of iodide and accessible oxidized iodine oxyanions drive the chemistry', 'iodide salts, iodates, periodates, iodine monochloride, and organoiodine reagents', 'hazards are significant for concentrated iodine and oxidized iodine species even though they are less aggressive than bromine or chlorine'),
      occurrence: facts('iodide and iodate in brines, seawater-related systems, caliche deposits, and biological reservoirs', 'it is scarce in crustal abundance but concentrated enough in certain brines and nitrate deposits for recovery', 'subsurface brines, caliche ores, and marine-biological cycles are the main reservoirs', 'iodine is unusually important biologically because trace intake is required for thyroid hormones', 'free iodine is absent in nature because iodide and iodate are the stable environmental forms'),
      isotopes: facts('stable iodine-127 together with radioactive isotopes such as iodine-123, 125, and 131', 'iodine-127 is the only stable isotope', 'radioiodine chemistry is central to thyroid imaging, therapy, and nuclear-environmental monitoring', 'iodine radioisotopes are widely used in medicine and nuclear safety studies', 'ordinary iodine chemistry is closely linked to isotope behavior because thyroid uptake makes many radioiodines biologically significant'),
      production: facts('oxidative recovery from iodide-rich brines and nitrate-related caliche processing', 'industrial supply depends on selective concentration from dilute natural sources rather than direct elemental occurrence', 'air oxidation, chlorine oxidation, extraction, and purification routes are common', 'purity control matters for nutritional, pharmaceutical, and electronic uses', 'supply depends strongly on a small number of brine and caliche districts'),
      applied: facts('nutrition, antiseptics, radiology, organic synthesis, catalysts, and specialty chemicals', 'iodized salts, iodine solutions, iodides, iodates, periodates, and radioiodine preparations', 'iodine is important because it unites halogen chemistry with essential biology and major medical isotope applications', 'its public-health importance rose sharply with iodized-salt programs and thyroid medicine', 'hazards center on concentrated oxidizing preparations, thyroid-active isotopes, and the need to control exposure in radiological settings'),
    },
  }),
  makeSeed({
    id: 'xenon',
    name: 'Xenon',
    symbol: 'Xe',
    atomicNumber: 54,
    atomicMass: '131.293',
    group: '18',
    period: '5',
    block: 'p',
    category: 'Noble gas',
    roomState: 'Gas',
    electronConfiguration: '[Kr]4d10 5s2 5p6',
    oxidationStates: '0, +2, +4, +6',
    summaryLine:
      'Xenon is a heavy noble gas whose rare but real compound chemistry, brilliant discharge behavior, and specialized medical or propulsion uses distinguish it from lighter noble gases.',
    importanceLine:
      'Its chemistry links closed-shell stability to cryogenic air separation, fluorination chemistry, anesthesia, ion propulsion, and xenon-based lighting.',
    heroFacts: ['Heavy noble gas', 'Forms rare fluorides', 'Important in lamps and ion thrusters', 'Recovered from liquid air'],
    glossaryExtras: [
      term('Xenon fluoride', 'A rare noble-gas compound such as XeF2, XeF4, or XeF6.'),
      term('Ion thruster', 'A propulsion device that accelerates ions of a gas such as xenon to generate thrust.'),
      term('Excimer lamp', 'A light source based on excited dimers or related excited gas species.'),
    ],
    sections: {
      classification: facts('a heavy noble gas with a closed valence shell but rare accessible compound chemistry', 'group 18, period 5, p-block', '[Kr]4d10 5s2 5p6', 'it is largely monatomic and inert under ordinary conditions yet can form fluorides and oxides under forcing conditions', 'its chemistry is the clearest exception to the simple idea that noble gases never form compounds'),
      electronic: facts('an [Kr]4d10 5s2 5p6 closed-shell valence arrangement', 'it remains monatomic in ordinary settings but can be oxidized by extremely powerful reagents to form xenon compounds', '0, +2, +4, and +6 in known compounds', 'Xe gas, xenon fluorides, xenon oxides or oxyfluorides, and discharge-plasma systems', 'the filled shell still dominates, but the heavy atom is polarizable enough for unusual high-oxidation-state chemistry'),
      physical: facts('a colorless dense monatomic gas', 'it is much denser than air and produces intense light in electrical discharge devices', 'weak but stronger-than-neon dispersion forces among heavy noble-gas atoms explain easy liquefaction relative to lighter noble gases', 'flash lamps, HID lamps, ion-thruster propellant tanks, and cryogenic xenon systems', 'main practical risks are pressure, oxygen displacement, and specialized cryogenic or electrical systems'),
      reactivity: facts('chemically inert in ordinary use but capable of forming rare high-valent fluorides and related compounds', 'it is activated only by unusually strong oxidizing or fluorinating conditions and by electrical excitation', 'high ionization energy preserves nobility, but heavy-atom polarizability permits a narrow chemistry beyond lighter noble gases', 'xenon fluorides, oxides, excimer systems, and plasma-discharge applications', 'practical hazards are usually physical, although xenon fluorides and related oxidized species require strong chemical caution'),
      occurrence: facts('trace quantities in the atmosphere and in cosmic materials', 'it is a very rare atmospheric constituent and therefore expensive to isolate', 'cryogenic air-separation streams are the dominant commercial reservoir', 'environmental cycling is minimal because xenon is chemically inert in most natural settings', 'free elemental xenon persists because noble-gas atoms are highly resistant to ordinary reaction'),
      isotopes: facts('multiple stable isotopes including xenon-124, 126, 128, 129, 130, 131, 132, 134, and 136', 'natural xenon has a rich isotope distribution with both stable and analytically important compositions', 'xenon isotopes are central in geochemistry, cosmochemistry, reactor science, and rare-event physics', 'xenon isotope analysis is used in atmospheric tracing, nuclear safeguards, and particle-physics detectors', 'few elements combine inert-gas chemistry with such important isotope science'),
      production: facts('fractional distillation of liquid air followed by purification from krypton and other rare gases', 'commercial supply depends on processing enormous volumes of air because xenon is only a trace constituent', 'additional purification and isotope-handling steps are used for high-value technical applications', 'high purity is essential for lighting, propulsion, anesthesia, and detector uses', 'availability is tied to large air-separation infrastructure and demand from specialized industries'),
      applied: facts('lighting, medical anesthesia, ion propulsion, imaging agents, and particle detectors', 'xenon gas, xenon fluorides, excimer-lighting systems, and high-purity detector or propulsion xenon', 'xenon is important because it combines noble-gas physical behavior with rare but real chemistry and extraordinary isotope utility', 'its technological profile grew through lamps, spacecraft propulsion, and high-end scientific instrumentation', 'hazards are usually physical for the gas but chemical for rare xenon fluorides and operationally significant in closed environments'),
    },
  }),
];
