import type { ElementSeed, SectionKey } from '@/content/subjects/chemistry/elementSeeds';
import {
  appliedSection,
  classificationSection,
  electronicSection,
  isotopeSection,
  occurrenceSection,
  physicalSection,
  productionSection,
  reactivitySection,
  term,
  type FactSet,
} from '@/content/subjects/chemistry/seedFactories';

type SeedConfig = Omit<ElementSeed, 'sections'> & { sections: Record<SectionKey, FactSet> };

function facts(a: string, b: string, c: string, d: string, e: string): FactSet {
  return [a, b, c, d, e];
}

function makeSeed(config: SeedConfig): ElementSeed {
  return {
    ...config,
    sections: {
      classification: classificationSection(config.name, config.sections.classification),
      electronic: electronicSection(config.name, config.sections.electronic),
      physical: physicalSection(config.name, config.sections.physical),
      reactivity: reactivitySection(config.name, config.sections.reactivity),
      occurrence: occurrenceSection(config.name, config.sections.occurrence),
      isotopes: isotopeSection(config.name, config.sections.isotopes),
      production: productionSection(config.name, config.sections.production),
      applied: appliedSection(config.name, config.sections.applied),
    },
  };
}

export const latePeriodSixHeavyElementSeeds: ElementSeed[] = [
  makeSeed({
    id: 'rhenium',
    name: 'Rhenium',
    symbol: 'Re',
    atomicNumber: 75,
    atomicMass: '186.207',
    group: '7',
    period: '6',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d5 6s2',
    oxidationStates: '-1, +2, +4, +6, +7',
    summaryLine:
      'Rhenium is a dense refractory transition metal whose wide oxidation-state chemistry and high-temperature durability make it important in superalloys and catalysis.',
    importanceLine:
      'Its chemistry links manganese-group redox behavior to petroleum catalysis, tungsten-like refractory metallurgy, and very scarce byproduct supply.',
    heroFacts: ['Refractory transition metal', 'Broad oxidation-state chemistry', 'Important in superalloys', 'Recovered mainly as a byproduct'],
    glossaryExtras: [
      term('Perrhenate', 'A rhenium(VII) oxyanion family, commonly written around ReO4 units.'),
      term('Superalloy', 'A high-temperature alloy engineered for strength and corrosion resistance.'),
      term('Molybdenite roast gas', 'A processing stream that can contain recoverable rhenium during molybdenum refining.'),
    ],
    sections: {
      classification: facts('a refractory group-7 transition metal with very broad oxidation-state chemistry', 'group 7, period 6, d-block', '[Xe]4f14 5d5 6s2', 'it forms metallic phases, oxides, halides, and oxyanions across an unusually wide redox range', 'its chemistry parallels manganese and technetium but is far more refractory and technologically tied to superalloys'),
      electronic: facts('an [Xe]4f14 5d5 6s2 valence arrangement', 'it forms coordination compounds and oxides spanning several oxidation states, with higher oxo chemistry especially important', '-1, +2, +4, +6, and +7', 'rhenium metal, perrhenates, rhenium oxides, halides, and organometallic catalysts', 'partially filled d orbitals and strong Re-O bonding make both redox chemistry and catalytic behavior unusually rich'),
      physical: facts('a very dense high-melting metallic solid', 'it retains strength at extreme temperature and is among the most refractory useful metals', 'strong metallic bonding and high cohesive energy explain its very high melting point and density', 'rhenium metal, rhenium-bearing superalloys, and catalytic rhenium compounds', 'bulk metal is manageable, but powder and high-temperature processing require controlled conditions'),
      reactivity: facts('a relatively unreactive refractory metal in bulk whose chemistry becomes important through oxides, halides, and catalysts', 'it forms stable oxides, perrhenates, and supported catalytic species under oxidizing conditions', 'strong stabilization of high-valent oxo chemistry drives much of its reactivity', 'perrhenates, rhenium oxides, halides, and reforming catalysts', 'hazards are usually associated with dusts, process fumes, and oxidized compounds rather than with the bulk metal'),
      occurrence: facts('trace concentrations in molybdenite, porphyry copper-molybdenum systems, and related sulfide ores', 'it is one of the scarcest technologically important metals and is obtained as a byproduct', 'molybdenum-roasting streams and selected sulfide concentrates are the main practical reservoirs', 'rhenium occurrence is controlled by trace substitution in sulfide minerals rather than by rich primary ores', 'native rhenium is absent because oxidized and sulfide-associated forms are more stable'),
      isotopes: facts('stable rhenium-185 and rhenium-187', 'rhenium-187 is naturally long lived and radioactive while rhenium-185 is stable', 'the Re-Os isotope system makes rhenium geochemically and cosmochemically important', 'Re-Os geochronology and tracing are major isotope applications', 'rhenium isotope chemistry is more significant in dating science than in routine handling'),
      production: facts('recovery from molybdenite-roasting and copper-molybdenum processing streams', 'industrial supply depends on extracting a trace element from much larger metallurgical operations', 'scrubbing and refining of roast-gas-derived intermediates are common routes to ammonium perrhenate and metal', 'high purity is essential for catalysts and superalloys', 'supply is tightly constrained by byproduct economics and aerospace or catalyst demand'),
      applied: facts('superalloys, petroleum reforming catalysts, electrical contacts, and specialized scientific materials', 'rhenium metal, ammonium perrhenate, rhenium oxides, and Pt-Re catalysts', 'rhenium is important because it combines broad d-block redox chemistry with extreme high-temperature metallic performance', 'its strategic profile grew with jet engines and reforming catalysis rather than bulk structural use', 'hazards are moderate and focus on industrial powders, process fumes, and the scarcity-driven importance of recycling'),
    },
  }),
  makeSeed({
    id: 'osmium',
    name: 'Osmium',
    symbol: 'Os',
    atomicNumber: 76,
    atomicMass: '190.23',
    group: '8',
    period: '6',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d6 6s2',
    oxidationStates: '+2, +3, +4, +8',
    summaryLine:
      'Osmium is a dense platinum-group metal whose noble-metal bulk behavior contrasts sharply with the volatility and toxicity of osmium tetroxide.',
    importanceLine:
      'Its chemistry links platinum-group durability to very high oxidation states, fine surface chemistry, and one of the most distinctive reagent hazards in inorganic chemistry.',
    heroFacts: ['Densest naturally occurring element', 'Platinum-group metal', 'OsO4 is a defining compound', 'Recovered from PGM streams'],
    glossaryExtras: [
      term('Osmium tetroxide', 'A volatile oxidizing osmium(VIII) compound widely used in microscopy and organic oxidation.'),
      term('Platinum-group metal', 'A noble transition metal recovered from specialized ores and refinery streams.'),
      term('Fixative', 'A reagent used to preserve biological structure, as osmium tetroxide is in microscopy.'),
    ],
    sections: {
      classification: facts('a platinum-group transition metal combining noble bulk behavior with accessible high-valent oxo chemistry', 'group 8, period 6, d-block', '[Xe]4f14 5d6 6s2', 'it forms metallic osmium and oxidized compounds ranging up to Os(VIII)', 'its chemistry is less common industrially than iron-group chemistry but more extreme in oxidation-state contrast'),
      electronic: facts('an [Xe]4f14 5d6 6s2 valence arrangement', 'it forms coordination compounds, alloys, and high-valent oxides across several oxidation states', '+2, +3, +4, and +8', 'osmium metal, osmium tetroxide, coordination complexes, and platinum-group alloys', 'strong metal-ligand interactions and accessible high oxidation states give osmium distinctive redox chemistry'),
      physical: facts('a very dense hard platinum-group metal', 'it is extremely dense and mechanically durable, though often used only in small amounts', 'strong metallic bonding and noble-metal character explain density and resistance to ordinary corrosion', 'osmium metal, hard alloys, and osmium tetroxide-derived laboratory reagents', 'bulk metal is comparatively stable, but oxidized osmium compounds require exceptional caution'),
      reactivity: facts('a relatively noble metal whose chemistry becomes dramatically different in strongly oxidizing conditions', 'it can be oxidized to volatile osmium tetroxide and also forms coordination and alloy systems', 'stabilization of high-valent oxo chemistry under oxidizing conditions drives the most famous osmium reactions', 'osmium tetroxide, coordination complexes, catalytic surfaces, and platinum-group alloys', 'osmium tetroxide is highly toxic and volatile, so exposure control is the dominant practical concern'),
      occurrence: facts('platinum-group ores, nickel-copper sulfides, and refinery residues', 'it is very rare and recovered only as a minor platinum-group component', 'PGM concentrates and refinery streams are the practical reservoir', 'osmium occurrence follows platinum-group mineralogy rather than broad crustal abundance', 'native osmium-bearing alloy grains can occur but are uncommon'),
      isotopes: facts('multiple stable isotopes including osmium-184, 186, 187, 188, 189, 190, and 192', 'natural osmium contains several stable isotopes', 'the Re-Os isotope system makes osmium exceptionally important in geochemistry and cosmochemistry', 'osmium isotopes are used in mantle studies, ore tracing, and geochronology', 'routine osmium chemistry is notable partly because isotope science is so influential in Earth science'),
      production: facts('recovery during refining of platinum-group metal concentrates', 'industrial supply depends entirely on complex PGM separations and byproduct recovery', 'oxidative and chloride-based refinery routes are used to isolate osmium-bearing fractions', 'purity control is critical because laboratory and high-value uses involve small quantities and strong hazards', 'supply depends on PGM mining and refinery throughput rather than standalone osmium extraction'),
      applied: facts('microscopy fixation, selected oxidation chemistry, hard alloys, and niche electronic or scientific materials', 'osmium tetroxide, osmium metal, platinum-group alloys, and specialized catalyst or contact materials', 'osmium is important because its chemistry ranges from extremely inert bulk metal to one of the most distinctive oxidizing molecular reagents', 'its scientific identity is dominated by OsO4 in microscopy and by isotope geochemistry', 'major hazards center on the volatility, toxicity, and oxidative power of osmium tetroxide'),
    },
  }),
  makeSeed({
    id: 'iridium',
    name: 'Iridium',
    symbol: 'Ir',
    atomicNumber: 77,
    atomicMass: '192.217',
    group: '9',
    period: '6',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d7 6s2',
    oxidationStates: '+3, +4',
    summaryLine:
      'Iridium is a very dense noble metal valued for exceptional corrosion resistance, high-temperature stability, and specialized catalytic or electrochemical roles.',
    importanceLine:
      'Its chemistry links platinum-group durability to catalytic surface science, chloride complexes, and extreme-service materials engineering.',
    heroFacts: ['Very dense noble metal', 'Highly corrosion resistant', 'Platinum-group element', 'Used in harsh-service components'],
    glossaryExtras: [
      term('Chloroiridate', 'A coordination complex family based on iridium and chloride ligands.'),
      term('Anodic stability', 'Resistance of a material to degradation under oxidizing electrochemical conditions.'),
      term('Platinum-group metal', 'A noble transition metal recovered from specialized ores and refinery streams.'),
    ],
    sections: {
      classification: facts('a noble group-9 transition metal within the platinum-group family', 'group 9, period 6, d-block', '[Xe]4f14 5d7 6s2', 'it forms durable metallic phases together with coordination compounds and catalytic surfaces', 'its chemistry is less common than rhodium but even more notable for chemical durability and extreme-service stability'),
      electronic: facts('an [Xe]4f14 5d7 6s2 valence arrangement', 'it forms coordination compounds and catalytic centers in which Ir(III) and Ir(IV) are especially important', '+3 and +4', 'iridium metal, chloride complexes, catalytic iridium oxides, and organoiridium systems', 'strong metal-ligand interactions and noble-metal character support robust but still catalytically active chemistry'),
      physical: facts('a dense hard corrosion-resistant noble metal', 'it remains stable under conditions that attack many other metals', 'strong metallic bonding and noble-metal character explain durability, density, and high-temperature performance', 'iridium metal, spark-plug components, crucibles, and oxide-coated electrodes', 'bulk metal is stable, though powder processing and some salts require industrial hygiene'),
      reactivity: facts('a relatively inert noble metal whose chemistry becomes useful in catalytic and electrochemical settings', 'it forms coordination compounds, oxides, and catalytic surfaces under forcing or designed conditions', 'noble-metal stability combined with accessible coordination chemistry drives its reactivity profile', 'iridium chlorides, iridium oxide electrodes, organometallic catalysts, and alloy systems', 'hazards are moderate and tied mainly to soluble compounds, powders, and high-temperature processing'),
      occurrence: facts('platinum-group ores, nickel-copper sulfides, and refinery byproduct streams', 'it is very rare and economically recovered only with other platinum-group metals', 'PGM concentrates and refinery residues are the practical reservoir', 'iridium occurrence is governed by scarce platinum-group mineralogy rather than ordinary crustal abundance', 'native iridium-bearing alloy grains can occur but are uncommon and not the main supply basis'),
      isotopes: facts('stable iridium-191 and iridium-193', 'both principal naturally occurring isotopes are stable', 'isotope chemistry supports analytical studies and selected radioactive industrial or medical uses', 'iridium isotopes are useful in tracing and in the context of radioisotope source materials', 'ordinary iridium chemistry is shaped more by noble-metal behavior than by isotope complexity'),
      production: facts('recovery during refining of platinum-group metal concentrates', 'industrial supply depends on complex PGM separations rather than direct mining', 'chloride chemistry, selective precipitation, and advanced refinery steps isolate iridium from related metals', 'purity is critical for electrochemical and high-temperature applications', 'availability depends strongly on PGM mining and the economics of recovery from mixed noble-metal streams'),
      applied: facts('corrosion-resistant hardware, electrochemical electrodes, crucibles, spark components, and specialized catalysis', 'iridium metal, iridium oxide, chloride complexes, and platinum-group alloys', 'iridium is important because it combines exceptional chemical durability with useful catalytic and electrochemical performance', 'its modern profile grew through harsh-service engineering and advanced electrochemical materials', 'hazards are moderate and mainly associated with soluble salts, powders, and specialized process conditions'),
    },
  }),
  makeSeed({
    id: 'platinum',
    name: 'Platinum',
    symbol: 'Pt',
    atomicNumber: 78,
    atomicMass: '195.084',
    group: '10',
    period: '6',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d9 6s1',
    oxidationStates: '+2, +4',
    summaryLine:
      'Platinum is a noble transition metal central to catalysis, electrochemistry, jewelry, and high-value chemical processing because of its balance of reactivity and durability.',
    importanceLine:
      'Its chemistry links noble-metal stability to surface catalysis, coordination compounds, and one of the most economically important families of high-value metals.',
    heroFacts: ['Noble transition metal', 'Premier catalyst metal', 'Highly corrosion resistant', 'Recovered from PGM ores'],
    glossaryExtras: [
      term('Catalytic converter', 'An emissions-control device that uses noble-metal catalysts such as platinum.'),
      term('Platinic complex', 'A coordination compound involving platinum, often in the +4 or +2 state.'),
      term('Fuel-cell catalyst', 'A catalyst that accelerates electrochemical reactions in a fuel cell.'),
    ],
    sections: {
      classification: facts('a noble group-10 transition metal and one of the most important platinum-group elements', 'group 10, period 6, d-block', '[Xe]4f14 5d9 6s1', 'it combines metallic nobility with highly useful catalytic and coordination chemistry', 'its chemistry is more broadly deployed than palladium in many electrochemical and high-temperature systems'),
      electronic: facts('an [Xe]4f14 5d9 6s1 valence arrangement', 'it forms coordination compounds and catalytic surfaces in which Pt(II), Pt(IV), and metallic Pt are all important', '+2 and +4', 'platinum metal, chloroplatinates, organoplatinum catalysts, and electrocatalytic surfaces', 'strong metal-ligand interactions and noble-metal surface chemistry make platinum central to both homogeneous and heterogeneous catalysis'),
      physical: facts('a dense ductile corrosion-resistant noble metal', 'it remains stable, workable, and highly conductive in demanding chemical environments', 'noble metallic bonding explains durability, ductility, and thermal stability', 'platinum metal, catalyst supports, crucibles, and precious-metal alloys', 'bulk metal is easy to handle, though salts, fine powders, and refinery residues require more caution'),
      reactivity: facts('a relatively unreactive metal in bulk whose chemistry becomes highly active at surfaces and in coordination complexes', 'it catalyzes hydrogenation, oxidation, electrochemical reactions, and many organometallic transformations', 'surface adsorption and accessible coordination chemistry drive its most important reactivity', 'fuel-cell catalysts, chloroplatinate salts, supported Pt catalysts, and organometallic systems', 'sensitizing platinum salts and catalyst powders are the main practical hazards rather than the bulk metal itself'),
      occurrence: facts('platinum-group ores, ultramafic deposits, and nickel-copper sulfide systems', 'it is rare in crustal abundance but concentrated enough in selected ore bodies to support major high-value mining', 'PGM reef deposits and refinery streams are the practical reservoirs', 'platinum occurrence is governed by specialized noble-metal geology rather than ordinary bulk abundance', 'native platinum-group alloys can occur because noble metals resist ordinary oxidation'),
      isotopes: facts('multiple stable isotopes including platinum-190, 192, 194, 195, 196, and 198', 'natural platinum contains several stable isotopes', 'isotope chemistry supports analytical studies and specialized tracing', 'platinum isotopes are useful in geochemistry, analytical chemistry, and selected radiochemical applications', 'routine platinum chemistry is controlled much more by catalysis and supply than by isotope effects'),
      production: facts('mining, concentration, smelting, and refinery separation of platinum-group ores', 'industrial supply depends on complex multi-metal separations from PGM concentrates rather than direct simple metallurgy', 'chloride refining, solvent extraction, and selective precipitation are central routes', 'high purity is essential for catalysts, electronics, and medical uses', 'supply depends on a small number of ore districts and strong recycling from catalysts'),
      applied: facts('automotive catalysts, fuel cells, chemical catalysis, jewelry, laboratory ware, and medical or electronic materials', 'platinum metal, chloroplatinates, supported catalysts, alloys, and anticancer-related compounds', 'platinum is important because it combines noble-metal stability with exceptional catalytic and coordination chemistry', 'its industrial identity spans precious-metal use, catalytic chemistry, and modern electrochemical energy systems', 'hazards center on sensitizing salts, catalyst powders, and refinery process exposure rather than on the inert bulk metal'),
    },
  }),
  makeSeed({
    id: 'gold',
    name: 'Gold',
    symbol: 'Au',
    atomicNumber: 79,
    atomicMass: '196.966569',
    group: '11',
    period: '6',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d10 6s1',
    oxidationStates: '+1, +3',
    summaryLine:
      'Gold is a noble coinage metal famous for chemical inertness, conductivity, and surface stability, yet still capable of rich Au(I) and Au(III) coordination chemistry.',
    importanceLine:
      'Its chemistry links noble-metal durability to cyanide extraction, nanomaterials, soft-ligand coordination, and the cultural history of precious metals.',
    heroFacts: ['Noble coinage metal', 'Native gold occurs', 'Au(I) and Au(III) chemistry', 'Important in electronics and finance'],
    glossaryExtras: [
      term('Aqua regia', 'A strongly oxidizing acid mixture able to dissolve gold.'),
      term('Cyanidation', 'An extraction process that dissolves gold through cyanide complex formation.'),
      term('Colloidal gold', 'Nanoscale gold particles dispersed in a medium, valued for optical behavior.'),
    ],
    sections: {
      classification: facts('a noble group-11 transition metal and classic coinage metal', 'group 11, period 6, d-block', '[Xe]4f14 5d10 6s1', 'it combines extraordinary metallic stability with useful soft-ligand coordination chemistry', 'its chemistry is more inert in bulk than copper or silver while still supporting distinctive Au(I) and Au(III) compounds'),
      electronic: facts('an [Xe]4f14 5d10 6s1 valence arrangement', 'it forms metallic gold together with coordination compounds centered mainly on Au(I) and Au(III)', '+1 and +3', 'gold metal, aurous complexes, auric chlorides, and nanoparticle materials', 'relativistic effects and soft-metal behavior help explain gold color, nobility, and ligand preferences'),
      physical: facts('a dense lustrous yellow noble metal', 'it is highly malleable, electrically conductive, and resistant to corrosion or tarnish', 'metallic bonding and relativistic electronic structure explain its unusual color and ductility', 'gold bullion, thin films, bonding wire, plated contacts, and colloidal gold', 'bulk metal is very easy to handle, though fine particles and solution chemistry demand more care'),
      reactivity: facts('a highly noble metal that resists most ordinary chemical attack but forms complexes under appropriate oxidizing and ligand conditions', 'it dissolves in aqua regia and in cyanide systems with oxidants, and it forms soft-ligand coordination compounds', 'strong metallic stability combined with favorable complex formation drives the chemistry', 'cyanide complexes, chloride complexes, gold nanoparticles, and catalytic surfaces', 'bulk gold is low hazard, but extraction chemistry and some soluble gold compounds require strict control'),
      occurrence: facts('native gold, quartz-vein deposits, placers, and polymetallic ores', 'it is rare in crustal abundance but important because native metal can concentrate in economically useful deposits', 'native gold-bearing veins and placer systems are the dominant practical reservoirs', 'gold occurrence is shaped by both hydrothermal concentration and the metal’s resistance to oxidation', 'native gold is common enough geologically because gold is unusually unreactive'),
      isotopes: facts('stable gold-197 together with specialized radioisotopes', 'gold-197 is the only stable isotope', 'radioisotopes are useful in analytical science and selected medical research', 'gold radioisotopes support tracing and specialized therapeutic or diagnostic studies', 'ordinary gold chemistry is dominated by extraction, surfaces, and coordination rather than isotope diversity'),
      production: facts('mining, concentration, cyanidation, smelting, and refining of native or ore-bound gold', 'industrial supply depends on ore grade and selective dissolution chemistry rather than simple bulk smelting alone', 'gravity separation, cyanide leaching, electrorefining, and bullion refining are major routes', 'purity control is essential for bullion, electronics, and high-value materials applications', 'supply depends on mining economics, recycling, and the chemistry of low-grade ore recovery'),
      applied: facts('bullion, jewelry, electronics, dentistry history, nanotechnology, catalysis, and high-reliability contacts', 'gold metal, gold complexes, plated films, colloidal gold, and catalytic nanomaterials', 'gold is important because it combines extraordinary bulk stability with useful nanoscale and coordination chemistry', 'its scientific identity now spans finance and ornament as well as nanoscience and catalysis', 'hazards are moderate for the metal but significant for cyanide extraction systems and some soluble gold compounds'),
    },
  }),
  makeSeed({
    id: 'mercury',
    name: 'Mercury',
    symbol: 'Hg',
    atomicNumber: 80,
    atomicMass: '200.592',
    group: '12',
    period: '6',
    block: 'd',
    category: 'D-block metal',
    roomState: 'Liquid',
    electronConfiguration: '[Xe]4f14 5d10 6s2',
    oxidationStates: '+1, +2',
    summaryLine:
      'Mercury is the only metal liquid at room temperature, with unusual Hg(I) and Hg(II) chemistry that is scientifically important but tightly governed by toxicity concerns.',
    importanceLine:
      'Its chemistry links filled-d-shell behavior, volatility, amalgam formation, redox chemistry, and one of the most consequential environmental toxicology stories in inorganic chemistry.',
    heroFacts: ['Liquid metal at room temperature', 'Hg(I) and Hg(II) chemistry', 'Forms amalgams', 'Major toxicological importance'],
    glossaryExtras: [
      term('Amalgam', 'An alloy or solution of mercury with another metal.'),
      term('Methylmercury', 'A highly toxic organomercury species that bioaccumulates strongly.'),
      term('Cinnabar', 'Mercury sulfide mineral, HgS, and the principal ore of mercury.'),
    ],
    sections: {
      classification: facts('a filled-d-shell heavy metal with unusually soft bonding and major toxicological relevance', 'group 12, period 6, d-block', '[Xe]4f14 5d10 6s2', 'it forms metallic mercury together with Hg(I) and Hg(II) compounds, many of them highly significant environmentally', 'its chemistry is more volatile and biologically hazardous than that of zinc or cadmium'),
      electronic: facts('an [Xe]4f14 5d10 6s2 valence arrangement', 'it forms both Hg(I) species with Hg-Hg bonding and Hg(II) compounds with soft-ligand coordination', '+1 and +2', 'mercury metal, mercurous compounds, mercuric halides, and organomercury species', 'relativistic effects help explain weak metallic bonding, volatility, and unusual cation chemistry'),
      physical: facts('a dense silvery liquid metal at room temperature', 'it is uniquely liquid among the metals in ordinary laboratory conditions and forms volatile vapor', 'weak metallic bonding helps explain the low melting point and liquid state', 'mercury metal, thermometric history, amalgams, and sealed analytical devices', 'vapor exposure control is essential because volatility creates inhalation risk'),
      reactivity: facts('a relatively noble soft metal whose chemistry is dominated by complexation, amalgam formation, and oxidation to Hg(I) or Hg(II)', 'it forms sulfides, halides, oxides, and amalgams rather than reacting violently like electropositive metals', 'soft-metal coordination and strong sulfur affinity drive much of the chemistry', 'amalgams, mercuric halides, mercury sulfide, organomercury compounds, and analytical reagents', 'toxicity dominates hazard evaluation for almost all mercury chemistry'),
      occurrence: facts('cinnabar deposits, geothermal systems, and contaminated sediments or food webs impacted by human release', 'it is rare but concentrated enough in sulfide ores for historic mining', 'cinnabar ores and industrial release pathways are the major practical reservoirs', 'mercury cycles globally through atmosphere, waters, sediments, and biota because speciation controls mobility and bioaccumulation', 'native mercury and mercury droplets can occur because elemental mercury is comparatively stable'),
      isotopes: facts('multiple stable isotopes including mercury-196, 198, 199, 200, 201, 202, and 204', 'natural mercury contains several stable isotopes', 'isotope patterns are valuable in tracing environmental cycling and pollution sources', 'mercury isotopes are widely used in environmental and geochemical studies', 'few toxic elements are studied isotopically as intensively as mercury in environmental science'),
      production: facts('mining and roasting of cinnabar together with recovery from recycled industrial streams', 'industrial supply historically depended on sulfide-ore roasting, though modern demand is far lower and recycling or controls matter greatly', 'thermal decomposition and condensation of mercury vapor were classic production steps', 'strict emission control is essential because mercury volatilizes easily', 'modern mercury supply is shaped strongly by regulation, waste control, and phaseout of many historical uses'),
      applied: facts('historical thermometers and switches, amalgams, lighting history, analytical science, and niche chemical uses', 'mercury metal, mercury salts, amalgams, and organomercury species', 'mercury is important because it illustrates how unusual physical properties and severe toxicity can coexist in one element', 'its scientific and industrial history is increasingly defined by replacement and environmental control rather than expansion of use', 'major hazards are vapor inhalation, chronic neurotoxicity, and bioaccumulative organomercury exposure'),
    },
  }),
  makeSeed({
    id: 'thallium',
    name: 'Thallium',
    symbol: 'Tl',
    atomicNumber: 81,
    atomicMass: '204.38',
    group: '13',
    period: '6',
    block: 'p',
    category: 'Post-transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d10 6s2 6p1',
    oxidationStates: '+1, +3',
    summaryLine:
      'Thallium is a heavy post-transition metal whose Tl(I) chemistry dominates because of the inert-pair effect, and whose toxicology has greatly narrowed its acceptable uses.',
    importanceLine:
      'Its chemistry links group-13 periodic trends to soft heavy-metal behavior, selective electronic uses, and serious biological hazard.',
    heroFacts: ['Heavy group-13 metal', 'Tl(I) is strongly favored', 'Inert-pair effect is important', 'Highly toxic element'],
    glossaryExtras: [
      term('Inert-pair effect', 'The tendency of heavy p-block ns2 electrons to resist participation in bonding.'),
      term('Thallous ion', 'Thallium in the +1 oxidation state, the most common state in ordinary chemistry.'),
      term('Crookes tube', 'A discharge tube historically associated with thallium-related spectroscopy and vacuum science.'),
    ],
    sections: {
      classification: facts('a heavy group-13 post-transition metal whose chemistry is dominated by the +1 state', 'group 13, period 6, p-block', '[Xe]4f14 5d10 6s2 6p1', 'it forms soft Tl+ compounds more readily than the trivalent chemistry expected from lighter group-13 analogies', 'its chemistry shows the inert-pair effect far more strongly than gallium or indium'),
      electronic: facts('an [Xe]4f14 5d10 6s2 6p1 valence arrangement', 'it forms mainly Tl(I) compounds, with Tl(III) accessible but less stable under ordinary conditions', '+1 and +3, with +1 dominant', 'TlCl, Tl2O, Tl(III) halides, and soft-ligand coordination compounds', 'heavy p-block relativistic and inert-pair effects strongly bias the chemistry toward monovalent behavior'),
      physical: facts('a soft bluish-white metallic solid', 'it is easily cut and deforms readily, though many uses are restricted by toxicity', 'relatively weak metallic bonding and heavy-metal character explain softness and low hardness', 'thallium metal, specialized optical materials, and thallium salts', 'dusts, residues, and soluble compounds require strict toxicological control'),
      reactivity: facts('a moderately reactive heavy metal forming mainly Tl(I) salts and selected Tl(III) oxidized compounds', 'it reacts with halogens, oxygen, acids, and complexing agents to form salts rather than the robust oxide passivation seen in aluminum', 'stabilization of Tl+ and soft heavy-metal coordination drives much of the chemistry', 'halides, oxides, sulfates, and specialty electronic or optical compounds', 'toxicity dominates practical hazard assessment more than spectacular chemical violence'),
      occurrence: facts('trace substitution in sulfide ores, especially those of zinc, copper, and lead', 'it is economically important mainly as a byproduct rather than as a major mined element', 'sulfide-smelting streams and refinery residues are the main practical reservoirs', 'thallium distribution follows heavy-metal sulfide geochemistry and can create contamination around mining or smelting', 'native thallium is absent because oxidized and sulfide-associated forms are more stable'),
      isotopes: facts('stable thallium-203 and thallium-205 together with selected radioisotopes', 'both principal naturally occurring isotopes are stable', 'isotope chemistry supports analytical work and selected medical or tracing applications', 'thallium radioisotopes are used in specialized diagnostics and research', 'ordinary thallium chemistry is defined far more by toxicology than by isotope complexity'),
      production: facts('recovery from zinc, lead, and copper smelting or refinery streams', 'industrial supply depends on byproduct separation from larger heavy-metal process streams', 'leaching, precipitation, and refining of residue streams are common routes', 'purity control matters for specialized optics and electronics, though many uses are now restricted', 'supply is shaped strongly by environmental regulation and byproduct economics'),
      applied: facts('specialty optical materials, electronics, detectors, and limited chemical uses after many historical applications were curtailed', 'thallium metal, thallium halides, thallium oxides, and detector-related compounds', 'thallium is important because it is a textbook example of the inert-pair effect becoming chemically dominant in a heavy p-block metal', 'its industrial history has shifted from broader use toward tightly controlled niche applications', 'major hazards are severe systemic toxicity, contamination of dusts or salts, and strict exposure-control requirements'),
    },
  }),
  makeSeed({
    id: 'lead',
    name: 'Lead',
    symbol: 'Pb',
    atomicNumber: 82,
    atomicMass: '207.2',
    group: '14',
    period: '6',
    block: 'p',
    category: 'Post-transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d10 6s2 6p2',
    oxidationStates: '+2, +4',
    summaryLine:
      'Lead is a dense post-transition metal whose Pb(II) chemistry, corrosion products, and historical ubiquity in pipes, pigments, and batteries are now viewed through major public-health concerns.',
    importanceLine:
      'Its chemistry links heavy group-14 behavior, the inert-pair effect, electrochemical energy storage, and long-term toxic exposure.',
    heroFacts: ['Dense post-transition metal', 'Pb(II) dominates chemistry', 'Central to lead-acid batteries', 'Major toxicological legacy'],
    glossaryExtras: [
      term('Lead-acid battery', 'An electrochemical storage system based on lead, lead dioxide, and sulfuric acid.'),
      term('Red lead', 'A mixed lead oxide pigment historically important in paints and corrosion protection.'),
      term('Plumbous ion', 'Lead in the +2 oxidation state, the dominant state in ordinary chemistry.'),
    ],
    sections: {
      classification: facts('a heavy group-14 post-transition metal whose chemistry is dominated by the +2 state', 'group 14, period 6, p-block', '[Xe]4f14 5d10 6s2 6p2', 'it forms Pb(II) compounds more readily than the +4 chemistry expected from lighter group-14 analogies', 'its chemistry shows the inert-pair effect strongly and differs markedly from carbon or silicon'),
      electronic: facts('an [Xe]4f14 5d10 6s2 6p2 valence arrangement', 'it forms mainly Pb(II) salts and solids, with Pb(IV) important in selected strongly oxidizing systems such as PbO2', '+2 and +4, with +2 dominant', 'PbO, PbO2, lead halides, lead carbonate, and lead-acid battery materials', 'heavy p-block inert-pair effects strongly bias the chemistry toward divalent compounds'),
      physical: facts('a dense soft metallic solid', 'it is easily shaped, comparatively low melting for a metal, and useful for shielding because of high density', 'heavy-metal bonding and large atomic mass explain softness and density', 'lead sheet, battery grids, radiation shielding, and historical plumbing or pigments', 'dusts, fumes, and old lead-containing materials require strict exposure control'),
      reactivity: facts('a moderately reactive heavy metal forming oxides, carbonates, sulfates, and halides while showing good resistance in some environments', 'it corrodes to surface films and participates in electrochemical redox chemistry rather than violent metal-water reaction', 'stabilization of Pb(II) salts and surface products drives much of its chemistry', 'lead oxides, lead sulfate in batteries, halides, and historical pigments', 'toxicity dominates practical hazard assessment more than dramatic reaction hazard'),
      occurrence: facts('galena and associated lead-zinc sulfide ores together with industrial and legacy environmental reservoirs', 'it is abundant enough in sulfide ores to support major historical mining and refining', 'galena-bearing ore bodies and anthropogenic reservoirs such as old paint or soils are the main practical reservoirs', 'lead occurrence now includes large legacy contamination as well as geological supply', 'native lead is uncommon because sulfide and oxide-associated forms are generally favored'),
      isotopes: facts('stable isotopes such as lead-204, 206, 207, and 208', 'several naturally occurring lead isotopes are stable, with some formed radiogenically from uranium and thorium decay chains', 'lead isotopes are central in geochronology, pollution tracing, and ore-source studies', 'Pb isotope ratios are used widely in Earth science and environmental forensics', 'few toxic heavy metals are studied isotopically as extensively as lead'),
      production: facts('smelting and refining of galena and other lead-bearing concentrates together with major recycling from batteries', 'industrial supply now relies heavily on secondary lead recycling as well as mining', 'sintering, smelting, electrorefining, and battery-recycling routes are major pathways', 'impurity control is crucial because arsenic, antimony, silver, and sulfur can accompany lead', 'supply and regulation are strongly shaped by battery demand and environmental-control costs'),
      applied: facts('lead-acid batteries, radiation shielding, alloys, weights, and historically pipes, solders, and pigments', 'lead metal, lead oxides, lead sulfate, battery materials, and shielding products', 'lead is important because it combines dense soft-metal properties with accessible electrochemistry, though toxicity now limits many uses', 'its history is inseparable from both civilization-scale utility and public-health damage from chronic exposure', 'major hazards are neurotoxicity, contaminated dust, fumes, and long-term environmental persistence'),
    },
  }),
  makeSeed({
    id: 'bismuth',
    name: 'Bismuth',
    symbol: 'Bi',
    atomicNumber: 83,
    atomicMass: '208.98040',
    group: '15',
    period: '6',
    block: 'p',
    category: 'Post-transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d10 6s2 6p3',
    oxidationStates: '+3, +5',
    summaryLine:
      'Bismuth is a heavy p-block metal whose Bi(III) chemistry, low-toxicity profile relative to lead, and low-melting alloys make it valuable in medicines, alloys, and oxide materials.',
    importanceLine:
      'Its chemistry links heavy-pnictogen inert-pair behavior to layered oxides, fusible alloys, and efforts to replace more toxic heavy metals.',
    heroFacts: ['Heavy pnictogen metal', 'Bi(III) dominates chemistry', 'Low-melting alloy component', 'Less toxic than lead'],
    glossaryExtras: [
      term('Bismuth subsalicylate', 'A bismuth-containing pharmaceutical used in gastrointestinal medicine.'),
      term('Fusible alloy', 'An alloy designed to melt at comparatively low temperature.'),
      term('Bismuthinite', 'A bismuth sulfide mineral and one of the natural sources of bismuth.'),
    ],
    sections: {
      classification: facts('a heavy group-15 post-transition metal whose chemistry is dominated by the +3 state', 'group 15, period 6, p-block', '[Xe]4f14 5d10 6s2 6p3', 'it forms Bi(III) compounds readily while Bi(V) remains limited to more strongly oxidizing systems', 'its chemistry is more metallic and often less toxic in practice than that of antimony or lead'),
      electronic: facts('an [Xe]4f14 5d10 6s2 6p3 valence arrangement', 'it forms mainly Bi(III) compounds because heavy-pnictogen inert-pair effects stabilize the lower oxidation state', '+3 and +5, with +3 dominant', 'bismuth oxides, halides, oxysalts, pharmaceuticals, and low-melting alloys', 'the inert-pair effect and soft heavy-metal behavior shape both coordination chemistry and materials use'),
      physical: facts('a brittle lustrous heavy metal', 'it expands on solidification and forms low-melting alloys useful in specialty engineering', 'metallic bonding and heavy-atom structure explain density, brittleness, and unusual solidification behavior', 'bismuth metal, fusible alloys, oxide powders, and pharmaceutical compounds', 'bulk metal is comparatively easy to handle, though powders and soluble compounds still require routine care'),
      reactivity: facts('a moderately reactive heavy metal forming oxides, oxysalts, halides, and medicinal or alloy compounds', 'it oxidizes under suitable conditions but is less notorious for toxic exposure than neighboring heavy metals', 'stabilization of Bi(III) oxides and oxycompounds drives much of the chemistry', 'bismuth oxides, oxychlorides, low-melting alloys, and medicinal salts', 'hazards are moderate and generally lower than for lead or thallium, though dusts and soluble compounds still require control'),
      occurrence: facts('bismuthinite, polymetallic sulfide ores, and byproduct refinery streams', 'it is relatively scarce and commonly obtained as a byproduct of lead, copper, tin, or tungsten processing', 'polymetallic ore systems and refinery residues are the main practical reservoirs', 'bismuth supply depends strongly on byproduct recovery rather than major dedicated mining', 'native bismuth can occur because the metal is relatively resistant compared with many base metals'),
      isotopes: facts('stable bismuth-209 together with specialized radioisotopes', 'bismuth-209 is the dominant naturally occurring isotope and is extremely long lived radioactively', 'isotope behavior is scientifically interesting but less central than the chemistry of heavy-metal replacement and oxide materials', 'bismuth isotopes are used in nuclear and analytical studies', 'ordinary bismuth chemistry is shaped more by oxidation state and application than by isotope diversity'),
      production: facts('recovery from polymetallic ore refining and byproduct heavy-metal streams', 'industrial supply depends on selective separation from lead, copper, tin, and tungsten process flows', 'smelting, electrolytic refining, and selective precipitation are common routes', 'purity control matters for pharmaceuticals, low-melting alloys, and functional oxides', 'supply follows byproduct economics and specialty-material demand more than bulk bismuth mining'),
      applied: facts('pharmaceuticals, low-melting alloys, cosmetics history, catalysts, and functional oxide materials', 'bismuth metal, bismuth subsalicylate, bismuth oxychloride, oxide ceramics, and fusible alloys', 'bismuth is important because it offers heavy-metal functionality in some uses where lead replacement is desirable', 'its modern profile blends medicinal chemistry, alloys, and advanced oxide materials', 'hazards are moderate and lower than for many neighboring heavy elements, though process hygiene remains necessary'),
    },
  }),
  makeSeed({
    id: 'polonium',
    name: 'Polonium',
    symbol: 'Po',
    atomicNumber: 84,
    atomicMass: '[209]',
    group: '16',
    period: '6',
    block: 'p',
    category: 'Post-transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d10 6s2 6p4',
    oxidationStates: '-2, +2, +4, +6',
    summaryLine:
      'Polonium is a highly radioactive heavy chalcogen whose ordinary chemistry is overshadowed by severe radiological hazard and its historical place in nuclear science.',
    importanceLine:
      'Its chemistry links heavy chalcogen trends to radioactivity, alpha emission, and the transition from ordinary inorganic chemistry into radiochemistry.',
    heroFacts: ['Highly radioactive element', 'Heavy chalcogen', 'Known mainly in nuclear science', 'Severe radiological hazard'],
    glossaryExtras: [
      term('Alpha emitter', 'A radionuclide that decays by emitting a helium-4 nucleus.'),
      term('Radiochemistry', 'Chemistry involving radioactive substances and their transformations.'),
      term('Curie discovery', 'Historical isolation and study of polonium as part of foundational radioactivity research.'),
    ],
    sections: {
      classification: facts('a heavy chalcogen best understood today as a highly radioactive post-transition heavy element', 'group 16, period 6, p-block', '[Xe]4f14 5d10 6s2 6p4', 'it forms oxidized compounds consistent with heavy chalcogen chemistry but is encountered mainly in radiochemical contexts', 'its chemistry is more metallic and far more radiologically dominated than that of tellurium or selenium'),
      electronic: facts('an [Xe]4f14 5d10 6s2 6p4 valence arrangement', 'it can form reduced and oxidized compounds across several states, though ordinary bonding chemistry is rarely the main practical issue', '-2, +2, +4, and +6', 'polonium oxides, halides, chalcogen-like compounds, and radiochemical source materials', 'heavy-atom and radiochemical effects matter more operationally than subtle valence-bond distinctions'),
      physical: facts('a rare dense radioactive solid', 'its physical handling is governed almost entirely by radioactivity and contamination control rather than bulk-metallurgical use', 'metallic and chalcogen-like bonding exist, but practical work is carried out only in specialized radiochemical settings', 'polonium sources, sealed radiochemical materials, and research-scale compounds', 'alpha radiation, contamination risk, and heat generation dominate handling requirements'),
      reactivity: facts('a chemically accessible heavy chalcogen whose practical chemistry is dominated by radiological control', 'it forms oxides, halides, and related compounds but is not handled like an ordinary laboratory chalcogen', 'stabilization of oxidized polonium compounds exists, but radioactivity sets the practical limits', 'radiochemical compounds, oxides, halides, and source materials', 'the dominant hazards are radiological and contamination-related rather than conventional corrosive or pyrophoric behavior'),
      occurrence: facts('trace decay-chain occurrence in uranium minerals and nuclear-production contexts', 'it is extraordinarily rare in natural abundance and generally discussed through radioactive decay chains', 'uranium-bearing minerals and artificial production streams are the main reservoirs', 'polonium occurrence is inseparable from nuclear decay processes rather than from economic ore geology', 'native polonium is not encountered as an ordinary natural material'),
      isotopes: facts('radioisotopes such as polonium-210', 'polonium has no stable isotopes', 'isotope identity determines essentially all scientific and practical significance of the element', 'polonium-210 is important in radiochemistry, alpha-source applications, and toxicological case studies', 'all polonium handling requires stringent radiological control'),
      production: facts('recovery or irradiation-based production through nuclear routes rather than mining', 'supply is governed by nuclear production and decay-chain chemistry, not by direct mineral extraction', 'irradiation and radiochemical separation routes are used to prepare useful isotopes', 'radiochemical purity and containment are the central process requirements', 'availability is limited by nuclear infrastructure, safety constraints, and short usable lifetimes'),
      applied: facts('alpha sources, specialized static eliminators, heat sources history, and nuclear-science research', 'polonium isotopes, sealed alpha sources, and radiochemical materials', 'polonium is important because it helped define radioactivity research and remains one of the clearest examples of chemistry governed by nuclear hazard', 'its scientific significance is far greater than its direct commercial footprint', 'major hazards are extreme radiotoxicity, contamination, and isotope-specific decay management'),
    },
  }),
  makeSeed({
    id: 'astatine',
    name: 'Astatine',
    symbol: 'At',
    atomicNumber: 85,
    atomicMass: '[210]',
    group: '17',
    period: '6',
    block: 'p',
    category: 'Halogen',
    roomState: 'Solid',
    electronConfiguration: '[Xe]4f14 5d10 6s2 6p5',
    oxidationStates: '-1, +1, +3, +5, +7',
    summaryLine:
      'Astatine is a very rare radioactive halogen whose chemistry blends halogen behavior with unusually metallic and radiochemical character.',
    importanceLine:
      'Its chemistry links periodic halogen trends to radiopharmaceutical research, short-lived isotopes, and the limits of atom-at-a-time heavy-element chemistry.',
    heroFacts: ['Radioactive halogen', 'Very scarce in nature', 'Shows mixed halogen and metallic behavior', 'Important in targeted alpha-therapy research'],
    glossaryExtras: [
      term('Radiopharmaceutical', 'A radioactive compound used for imaging or therapy.'),
      term('Targeted alpha therapy', 'Cancer treatment strategy that delivers alpha-emitting isotopes to selected tissues.'),
      term('Halogen chemistry', 'The family of reactions and compounds associated with group-17 elements.'),
    ],
    sections: {
      classification: facts('a heavy radioactive halogen whose chemistry is less purely nonmetallic than that of iodine or bromine', 'group 17, period 6, p-block', '[Xe]4f14 5d10 6s2 6p5', 'it forms halide-like At- species together with oxidized compounds and covalent heavy-element complexes', 'its chemistry marks the point where halogen trends become strongly shaped by radioactivity and heavy-atom effects'),
      electronic: facts('an [Xe]4f14 5d10 6s2 6p5 valence arrangement', 'it can show several oxidation states, with halide behavior and higher oxidized forms both relevant in radiochemistry', '-1, +1, +3, +5, and +7', 'astatides, oxidized astatine species, organoastatine compounds, and radiolabeled targeting molecules', 'heavy-atom and relativistic effects weaken simple analogies to lighter halogens and give astatine more polarizable bonding behavior'),
      physical: facts('an extremely rare radioactive solid known mostly through trace-scale radiochemical work', 'bulk physical characterization is limited because only minute short-lived samples are handled', 'radioactivity and scarcity dominate practical handling more than ordinary condensed-matter measurement', 'trace astatine sources, sealed radiochemical preparations, and labeled biomolecular systems', 'all work is governed by isotope-specific radiological containment rather than routine solid-state handling'),
      reactivity: facts('a reactive heavy halogen whose chemistry is studied mainly through atom-scale or tracer-scale radiochemical transformations', 'it forms halide-like species, interhalogen-type compounds, and covalently bound labeling agents under controlled conditions', 'bonding is driven by heavy halogen valence behavior together with strong radiochemical constraints', 'astatide salts, oxidized astatine species, and radiopharmaceutical labeling intermediates', 'the dominant hazards are radiological exposure, contamination, and short-lived isotope handling rather than conventional corrosive hazard alone'),
      occurrence: facts('trace members of uranium and thorium decay chains together with artificial cyclotron or reactor production streams', 'natural abundance is vanishingly small because the isotopes are short lived', 'practical supply comes from nuclear production rather than from mining', 'astatine occurrence is inseparable from nuclear decay and laboratory production rather than from ordinary geochemical reservoirs', 'native astatine is not encountered as an ordinary natural material'),
      isotopes: facts('short-lived radioisotopes such as astatine-211 and astatine-210', 'astatine has no stable isotopes and is defined scientifically through isotope-specific behavior', 'astatine-211 is especially important for targeted alpha-therapy research', 'radiopharmaceutical tracing, therapeutic research, and nuclear-structure studies are the principal isotope applications', 'every practical use depends on short half-lives, rapid synthesis, and strict radiological control'),
      production: facts('cyclotron production and radiochemical isolation rather than conventional metallurgy', 'supply depends on bombarding suitable targets and isolating minute quantities rapidly', 'nuclear production and fast purification are central because the useful isotopes decay quickly', 'radiochemical purification, labeling chemistry, and controlled distribution are the practical product streams', 'availability depends on accelerator access, isotope half-life, and specialized radiochemistry expertise'),
      applied: facts('targeted alpha therapy research, nuclear chemistry, and tracer-scale radiopharmaceutical design', 'astatine isotopes, labeled biomolecules, and specialized radiochemical preparations', 'astatine is important because it extends halogen chemistry into clinically relevant alpha-emitting radiopharmaceutical research', 'its scientific importance is driven by medical promise and the unusual chemistry of an ultrarare heavy halogen', 'major hazards are radiotoxicity, contamination, and the operational difficulty of working with short-lived isotopes'),
    },
  }),
  makeSeed({
    id: 'radon',
    name: 'Radon',
    symbol: 'Rn',
    atomicNumber: 86,
    atomicMass: '[222]',
    group: '18',
    period: '6',
    block: 'p',
    category: 'Noble gas',
    roomState: 'Gas',
    electronConfiguration: '[Xe]4f14 5d10 6s2 6p6',
    oxidationStates: '0, +2',
    summaryLine:
      'Radon is a radioactive noble gas whose inert closed-shell chemistry is overshadowed by its importance in indoor-air exposure and radiation health.',
    importanceLine:
      'Its chemistry links noble-gas trends to radioactive decay chains, environmental transport, and one of the most important natural sources of human ionizing-radiation exposure.',
    heroFacts: ['Radioactive noble gas', 'Member of uranium decay chains', 'Indoor-air health hazard', 'Mostly inert in ordinary chemistry'],
    glossaryExtras: [
      term('Decay chain', 'A sequence of radioactive transformations from one nuclide to another.'),
      term('Indoor radon', 'Radon gas that accumulates inside buildings and elevates radiation exposure.'),
      term('Noble-gas compound', 'An uncommon compound formed by a group-18 element under special conditions.'),
    ],
    sections: {
      classification: facts('a heavy radioactive noble gas with a filled outer shell and limited compound chemistry', 'group 18, period 6, p-block', '[Xe]4f14 5d10 6s2 6p6', 'it exists mainly as monatomic Rn gas, with only limited oxidized or fluoride chemistry under specialized conditions', 'its classification is controlled by closed-shell behavior even though radiological significance far outweighs ordinary chemical reactivity'),
      electronic: facts('an [Xe]4f14 5d10 6s2 6p6 closed-shell valence arrangement', 'it is largely inert but can participate in a small number of oxidized noble-gas compounds under forcing conditions', '0 and limited positive states such as +2 in specialized chemistry', 'radon gas, radon fluorides in theoretical or specialized discussions, and decay-derived daughter products', 'closed-shell stability suppresses ordinary bonding, while heavy-atom effects make radon slightly more polarizable than lighter noble gases'),
      physical: facts('a colorless radioactive monatomic gas', 'its physical transport through soils, groundwater, and buildings is more consequential than condensed-phase properties', 'low chemical reactivity and gaseous mobility make ventilation and diffusion central practical themes', 'environmental radon gas, calibration sources, and radiation-monitoring systems', 'hazards arise from inhalation and radioactive decay products rather than from corrosive or flammable behavior'),
      reactivity: facts('chemically inert under ordinary conditions but environmentally hazardous because it moves readily as a radioactive gas', 'it participates little in everyday synthesis, though rare oxidized species and adsorption behavior can be studied', 'closed-shell stability keeps reaction chemistry limited compared with almost all other heavy elements', 'trace noble-gas chemistry, environmental transport, and radon-daughter surface deposition systems', 'the dominant hazard is inhalation exposure and subsequent alpha-emitting decay products in the lungs'),
      occurrence: facts('uranium- and thorium-series decay in rocks, soils, groundwater, and building materials', 'it is generated continuously in natural radioactive decay chains and can migrate into enclosed spaces', 'soils, basements, mines, and groundwater-bearing systems are the main practical reservoirs', 'radon occurrence is controlled by both geology and building ventilation rather than by conventional mineral extraction', 'native elemental radon is encountered only as transient decay-generated gas'),
      isotopes: facts('radioisotopes such as radon-222, radon-220, and radon-219', 'radon has no stable isotopes and is studied through its decay-chain members', 'radon-222 is the most important isotope for environmental and health discussions', 'environmental monitoring, geochemical tracing, and radiation-health assessment are the principal isotope uses', 'handling centers on ventilation, sealed standards, and control of radioactive daughters'),
      production: facts('natural generation in decay chains and controlled collection from radium-containing sources for calibration or research', 'practical supply is minute and specialized rather than a bulk industrial product', 'sealed-source emanation, decay-based generation, and radiological trapping methods are the relevant routes', 'monitoring standards, research sources, and detector-calibration materials are the main practical forms', 'availability is constrained by radiological regulation and the short-lived nature of the isotopes'),
      applied: facts('radiation monitoring, geochemical tracing, limited research applications, and public-health risk assessment', 'radon monitoring systems, sealed reference sources, and environmental measurement workflows', 'radon is important because it turns noble-gas chemistry into a major environmental-health topic rather than a synthetic-chemistry topic', 'its scientific significance lies in indoor-air exposure, geology, and radiation protection', 'major hazards are inhalation, radioactive daughters, and long-term lung-cancer risk'),
    },
  }),
  makeSeed({
    id: 'francium',
    name: 'Francium',
    symbol: 'Fr',
    atomicNumber: 87,
    atomicMass: '[223]',
    group: '1',
    period: '7',
    block: 's',
    category: 'Alkali metal',
    roomState: 'Solid',
    electronConfiguration: '[Rn]7s1',
    oxidationStates: '+1',
    summaryLine:
      'Francium is an extremely rare radioactive alkali metal whose chemistry is inferred mostly from periodic trends, tracer studies, and atomic-physics experiments.',
    importanceLine:
      'Its significance lies less in bulk chemistry than in showing how far alkali-metal behavior can be extended before scarcity and radioactivity dominate the discussion.',
    heroFacts: ['Heaviest alkali metal', 'Extremely rare', 'Known mainly from tracer and atomic studies', 'Strongly radioactive'],
    glossaryExtras: [
      term('Tracer scale', 'Working with minute quantities sufficient for detection but not bulk isolation.'),
      term('Atomic trap', 'A device that confines atoms for precise spectroscopic or atomic-physics study.'),
      term('Decay product', 'A nuclide produced from the radioactive decay of another nuclide.'),
    ],
    sections: {
      classification: facts('an extremely rare radioactive alkali metal known primarily through periodic inference and trace-scale experiments', 'group 1, period 7, s-block', '[Rn]7s1', 'it is expected to form Fr+ salts and highly ionic compounds analogous to cesium salts', 'its classification follows alkali-metal trends, but scarcity prevents ordinary bulk chemistry from being explored'),
      electronic: facts('an [Rn]7s1 valence arrangement', 'it is expected to lose its outer electron readily and behave overwhelmingly as Fr+ in compounds', '+1', 'francium halides, oxides, hydroxides, and tracer-scale ionic salts are the usual predicted or studied forms', 'shielding, large radius, and heavy-atom effects shape the chemistry, though most evidence comes from atomic or tracer-scale work'),
      physical: facts('a short-lived radioactive metallic solid inferred mainly from periodic trends', 'bulk physical properties are not studied routinely because no macroscopic sample is available under ordinary conditions', 'the metal is expected to be soft, dense, and highly electropositive like the heavier alkali metals', 'tracer sources, atomic traps, and research-scale salts are the practical material forms', 'all handling is governed by radioactivity and minuscule sample size rather than bulk-metallurgical practice'),
      reactivity: facts('a highly electropositive alkali-metal chemistry known mainly through prediction and trace experiments', 'it is expected to react vigorously with electronegative partners and to form strongly ionic compounds', 'loss of the 7s electron drives simple Fr+ chemistry much as in cesium, though heavy-atom effects slightly modify details', 'halides, hydroxides, oxides, and radiochemical tracer salts are the relevant reaction classes', 'practical hazards are radiological and scarcity-driven rather than the visible violence associated with bulk alkali metals'),
      occurrence: facts('minute transient quantities in uranium and actinium decay chains', 'natural abundance is extraordinarily low because all isotopes are short lived', 'francium exists only as fleeting decay products rather than as mineable ores or reservoirs', 'occurrence is inseparable from nuclear decay and laboratory generation rather than from ordinary geochemistry', 'native francium is never encountered as a bulk natural substance'),
      isotopes: facts('radioisotopes such as francium-223 and related short-lived nuclides', 'francium has no stable isotopes and is defined entirely by radioactive decay behavior', 'francium isotopes are valuable mainly in atomic physics and nuclear-structure studies', 'laser spectroscopy, trapping experiments, and nuclear-decay studies are the major isotope applications', 'all work is dictated by short half-lives and stringent radiological controls'),
      production: facts('collection from decay chains and specialized production for atomic-physics experiments', 'practical supply involves generating or harvesting tiny amounts rather than manufacturing bulk material', 'radiochemical separation and rapid transfer into trapping or detection systems are the key routes', 'atomic-beam, trapping, and tracer-scale materials are the only realistic product forms', 'availability is limited by isotope lifetime and by the specialized infrastructure needed to study it'),
      applied: facts('atomic physics, spectroscopy, and tests of nuclear or electroweak theories rather than bulk technology', 'laser-cooled atoms, tracer-scale salts, and decay-study sources', 'francium is important because it extends alkali-metal behavior into an extreme regime where radioactivity dominates the science', 'its significance is primarily fundamental rather than industrial', 'major hazards are radiological, and practical chemistry is limited by vanishingly small quantities'),
    },
  }),
  makeSeed({
    id: 'radium',
    name: 'Radium',
    symbol: 'Ra',
    atomicNumber: 88,
    atomicMass: '[226]',
    group: '2',
    period: '7',
    block: 's',
    category: 'Alkaline earth metal',
    roomState: 'Solid',
    electronConfiguration: '[Rn]7s2',
    oxidationStates: '+2',
    summaryLine:
      'Radium is a radioactive alkaline-earth metal whose Ra2+ chemistry resembles barium but whose historical and radiological significance is far greater.',
    importanceLine:
      'Its chemistry links group-2 ionic behavior to radioactivity research, medical history, luminous materials, and radiation protection.',
    heroFacts: ['Radioactive alkaline-earth metal', 'Ra2+ dominates chemistry', 'Historic role in radiochemistry', 'Major radiation hazard'],
    glossaryExtras: [
      term('Radium therapy', 'Historical medical use of radium-based radiation sources.'),
      term('Emanation', 'Older terminology for radioactive gases such as radon released from radium.'),
      term('Alkaline-earth chemistry', 'The ionic chemistry characteristic of group-2 metals.'),
    ],
    sections: {
      classification: facts('a heavy radioactive alkaline-earth metal whose chemistry is dominated by the Ra2+ ion', 'group 2, period 7, s-block', '[Rn]7s2', 'it forms ionic salts and minerals analogous to barium compounds, though radioactivity dominates handling', 'its classification is straightforward chemically but exceptional radiologically because the element is intensely radioactive'),
      electronic: facts('an [Rn]7s2 valence arrangement', 'it behaves overwhelmingly as Ra2+ in compounds and aqueous chemistry', '+2', 'radium halides, radium sulfate, radium carbonate, and radiological source materials', 'loss of the two outer s electrons gives the simple ionic chemistry expected for an alkaline-earth metal'),
      physical: facts('a dense radioactive metallic solid', 'bulk samples are rare and all practical work is governed by radiological control rather than ordinary metal handling', 'alkaline-earth metallic bonding explains the expected softness and reactivity, while radioactivity adds heat and damage concerns', 'sealed radium sources, historical luminous materials, and radiochemical salts', 'external radiation, internal exposure, and decay-product buildup dominate safety requirements'),
      reactivity: facts('a reactive group-2 metal forming strongly ionic Ra2+ salts', 'it reacts analogously to barium in oxides, halides, sulfates, and carbonates, but radiochemistry governs every practical operation', 'simple ionic bonding drives compound formation, while radioactive decay controls storage and contamination risk', 'radium salts, sealed sources, and radiochemical standards', 'the dominant hazards are radiological exposure, contamination, and radon generation from decay'),
      occurrence: facts('trace amounts in uranium ores and radioactive decay chains', 'it occurs naturally only as a daughter product in uranium-bearing minerals', 'uraninite and related radioactive minerals are the main natural reservoirs', 'occurrence is controlled by nuclear decay rather than by independent radium mineralogy', 'native radium is not encountered because the element is both reactive and scarce'),
      isotopes: facts('radioisotopes such as radium-226 and radium-228', 'radium has no stable isotopes and is known through long-lived members of natural decay series', 'radium-226 is especially important because it generates radon and historically defined many radiological measurements', 'radiation sources, geochemical tracing, and decay-chain studies are the main isotope applications', 'all isotopic work requires shielding, contamination control, and management of daughter products'),
      production: facts('recovery from uranium-bearing minerals or specialized radiochemical separation streams', 'industrial production has always been limited and specialized rather than bulk scale', 'radiochemical extraction, purification, and encapsulation are the relevant process routes', 'sealed sources, radiological standards, and research materials are the main product forms', 'modern handling is tightly governed by regulation and declining use relative to safer substitute technologies'),
      applied: facts('historical luminous paints, radiotherapy history, radiological standards, and specialized research sources', 'radium salts, sealed sources, and radiochemical reference materials', 'radium is important because it helped define early radioactivity research and radiation medicine, even though many uses are now obsolete', 'its history is a major lesson in how scientific discovery and radiological harm can be tightly intertwined', 'major hazards are intense radioactivity, contamination, and daughter-product exposure including radon'),
    },
  }),
];
