import type { ElementSeed, SectionKey } from '@/content/subjects/chemistry/elementSeeds';
import {
  appliedSection,
  classificationSection,
  electronicSection,
  isotopeSection,
  occurrenceSection,
  physicalSection,
  productionSection,
  reactivitySection,
  term,
  type FactSet,
} from '@/content/subjects/chemistry/seedFactories';

type SeedConfig = Omit<ElementSeed, 'sections'> & { sections: Record<SectionKey, FactSet> };

function facts(a: string, b: string, c: string, d: string, e: string): FactSet {
  return [a, b, c, d, e];
}

function makeSeed(config: SeedConfig): ElementSeed {
  return {
    ...config,
    sections: {
      classification: classificationSection(config.name, config.sections.classification),
      electronic: electronicSection(config.name, config.sections.electronic),
      physical: physicalSection(config.name, config.sections.physical),
      reactivity: reactivitySection(config.name, config.sections.reactivity),
      occurrence: occurrenceSection(config.name, config.sections.occurrence),
      isotopes: isotopeSection(config.name, config.sections.isotopes),
      production: productionSection(config.name, config.sections.production),
      applied: appliedSection(config.name, config.sections.applied),
    },
  };
}

export const midPeriodicElementSeeds: ElementSeed[] = [
  makeSeed({
    id: 'rubidium',
    name: 'Rubidium',
    symbol: 'Rb',
    atomicNumber: 37,
    atomicMass: '85.4678',
    group: '1',
    period: '5',
    block: 's',
    category: 'Alkali metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]5s1',
    oxidationStates: '+1',
    summaryLine:
      'Rubidium is a very reactive heavy alkali metal whose Rb+ chemistry is simpler than its elemental reactivity, making it more important in precision physics than in bulk industry.',
    importanceLine:
      'Its chemistry connects heavy alkali-metal trends to atomic clocks, vapor spectroscopy, isotope geochronology, and highly reactive metal handling.',
    heroFacts: ['Heavy alkali metal', 'Forms Rb+ salts', 'Important in atomic clocks', 'Extremely water reactive'],
    glossaryExtras: [
      term('Rubidium standard', 'A frequency reference based on rubidium atomic transitions.'),
      term('Lepidolite', 'A lithium-bearing mica that can contain recoverable rubidium.'),
      term('Rb-Sr dating', 'A geochronological method based on decay of rubidium-87 to strontium-87.'),
    ],
    sections: {
      classification: facts('an alkali metal with one 5s valence electron', 'group 1, period 5, s-block', '[Kr]5s1', 'it forms strongly ionic Rb+ salts and is even more easily oxidized than potassium', 'its chemistry extends the heavy alkali trend toward softness, low ionization energy, and very high reactivity'),
      electronic: facts('a [Kr]5s1 valence shell', 'it forms overwhelmingly ionic compounds stabilized as Rb+ in solids and solutions', '+1 in ordinary compounds', 'RbCl, RbOH, rubidium superoxide, and solvated Rb+ ions', 'large cation size weakens hydration and lattice effects relative to lighter alkali metals'),
      physical: facts('a very soft silvery low-melting metal', 'it is softer and more easily melted than sodium or potassium', 'expanded metallic bonding in the large alkali lattice explains softness and rapid oxidation', 'sealed rubidium ampoules, alkali-metal vapor cells, and specialty alloys', 'air and moisture exclusion is essential because tarnishing and ignition occur rapidly'),
      reactivity: facts('an extremely reactive reducing metal that attacks water and oxygen vigorously', 'it forms hydroxide and hydrogen with water and oxidized surface products in air', 'low ionization energy and strong stabilization of Rb+ drive the chemistry', 'oxides, superoxides, halides, and alkali-vapor or organorubidium systems', 'contact with moisture or oxidizers can cause fire or violent reaction'),
      occurrence: facts('dispersed in feldspars, lepidolite, pollucite-related minerals, and some brines', 'it is geochemically dispersed and not mined as a major standalone bulk element', 'pegmatites, granitic minerals, and specialty brines are the main practical reservoirs', 'Rb+ often follows potassium geochemistry and is useful in geological tracing', 'native rubidium is absent because ionic mineral forms are far more stable'),
      isotopes: facts('rubidium-85 and rubidium-87', 'rubidium-87 is naturally radioactive whereas rubidium-85 is stable', 'the long-lived decay of rubidium-87 to strontium-87 gives rubidium isotope chemistry geochronological importance', 'Rb-Sr dating is a major geochemical application', 'ordinary chemical handling is not driven by radiological hazard, but isotope science is important'),
      production: facts('recovery from pegmatite minerals, specialty brines, and mixed alkali feedstocks', 'industrial supply is small and depends on separation from potassium and cesium rather than bulk extraction', 'ion-exchange, solvent extraction, and high-purity salt processing are common routes', 'separation from closely related alkali metals is the central refining challenge', 'demand is governed mainly by research, electronics, and specialty optical uses'),
      applied: facts('atomic clocks, photoemissive devices, specialty glass, and research lasers', 'rubidium salts, rubidium vapor, and selected alkali-metal alloys or sensors', 'rubidium is scientifically important because its transitions are valuable in precision measurement and quantum optics', 'isotope work and alkali-vapor physics gave rubidium outsized importance relative to its abundance', 'hazards center on extreme metal reactivity and the handling of sealed alkali or vapor systems'),
    },
  }),
  makeSeed({
    id: 'strontium',
    name: 'Strontium',
    symbol: 'Sr',
    atomicNumber: 38,
    atomicMass: '87.62',
    group: '2',
    period: '5',
    block: 's',
    category: 'Alkaline earth metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]5s2',
    oxidationStates: '+2',
    summaryLine:
      'Strontium is an alkaline-earth metal best known for Sr2+ salts, bright crimson flame colors, and the environmental and medical significance of selected isotopes.',
    importanceLine:
      'Its chemistry links group-2 ionic behavior to pyrotechnics, ceramic materials, bone-seeking isotope behavior, and mineral geochemistry.',
    heroFacts: ['Alkaline earth metal', 'Forms Sr2+ salts', 'Crimson flame color', 'Key isotope is 90Sr'],
    glossaryExtras: [
      term('Celestite', 'Strontium sulfate mineral and the principal ore of strontium.'),
      term('Strontianite', 'Strontium carbonate mineral used as a strontium source.'),
      term('Bone-seeking isotope', 'A radioactive nuclide that follows calcium-like chemistry into bones, as strontium-90 does.'),
    ],
    sections: {
      classification: facts('an alkaline earth metal with a filled 5s pair', 'group 2, period 5, s-block', '[Kr]5s2', 'it forms Sr2+ readily and shows classic group-2 ionic chemistry', 'its chemistry is more reactive and more soluble in some salts than that of calcium'),
      electronic: facts('a [Kr]5s2 valence shell', 'it forms strongly ionic compounds centered on Sr2+ in solids and solutions', '+2 in ordinary compounds', 'SrO, SrCl2, SrCO3, and hydrated Sr2+ ions', 'the large doubly charged cation favors ionic lattices, high coordination, and calcium-like geochemistry'),
      physical: facts('a soft silvery metallic solid', 'it is softer and more reactive than calcium and gives a vivid crimson flame', 'metallic bonding in the heavy group-2 lattice and facile oxidation shape its physical handling', 'strontium metal, pyrotechnic salts, and ceramic precursor materials', 'metal samples must be protected from air and moisture because oxidation proceeds readily'),
      reactivity: facts('a reactive alkaline-earth metal forming stable oxides, hydroxides, halides, and salts', 'it reacts with oxygen, water, and acids to produce oxidized strontium compounds', 'stabilization of Sr2+ and of ionic solids drives most accessible chemistry', 'oxides, hydroxides, nitrates, carbonates, and selected ceramic materials', 'metal handling requires dry conditions and some strontium compounds require dust control'),
      occurrence: facts('celestite, strontianite, seawater traces, and calcium-bearing geological systems', 'it is less abundant than calcium but concentrated enough in sulfate and carbonate minerals for industrial recovery', 'evaporites and carbonate-related deposits are the dominant commercial reservoirs', 'Sr2+ can substitute for Ca2+ in minerals and biological hard tissues', 'native strontium metal does not occur because ionic mineral forms are strongly favored'),
      isotopes: facts('stable isotopes such as strontium-84, 86, 87, and 88 together with radioactive strontium-90', 'strontium-87 has radiogenic importance and strontium-90 is a major fission product', 'isotopic composition records geological history and radioactive isotopes create environmental health concern', 'Sr isotope ratios are central in geology and archaeology, while strontium-90 matters in radiological monitoring', 'strontium isotope chemistry is unusually important because it spans both stable tracing and nuclear fallout science'),
      production: facts('mining and refining of celestite and related strontium minerals', 'industrial supply is based on sulfate and carbonate ores rather than on isolated metal production', 'conversion to carbonate, nitrate, oxide, or other salts precedes most end uses', 'purity control matters for pyrotechnic, ceramic, and ferrite applications', 'metallic strontium is a niche product compared with the much larger strontium-salt market'),
      applied: facts('pyrotechnics, ferrite magnets, ceramics, specialty glass, and isotope-related medical or environmental science', 'strontium nitrate, strontium carbonate, strontium ferrites, and selected radioisotopes', 'strontium is important because its ionic chemistry overlaps with calcium while its flame color and isotopes give distinctive applications', 'its practical significance expanded through fireworks, permanent magnets, and nuclear-era isotope monitoring', 'hazards depend on the compound, with radioactive strontium and reactive metal requiring the greatest control'),
    },
  }),
  makeSeed({
    id: 'yttrium',
    name: 'Yttrium',
    symbol: 'Y',
    atomicNumber: 39,
    atomicMass: '88.90584',
    group: '3',
    period: '5',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d1 5s2',
    oxidationStates: '+3',
    summaryLine:
      'Yttrium is a group-3 metal with strongly favored Y3+ chemistry, widely used in phosphors, ceramics, lasers, and high-temperature oxide materials.',
    importanceLine:
      'Its chemistry sits between transition-metal and rare-earth behavior, linking separation chemistry to phosphors, superconductors, and advanced oxides.',
    heroFacts: ['Group-3 metal', 'Y3+ dominates chemistry', 'Important in phosphors', 'Recovered with rare earths'],
    glossaryExtras: [
      term('Yttria', 'Yttrium oxide, Y2O3, a major yttrium ceramic and optical material.'),
      term('YSZ', 'Yttria-stabilized zirconia, an oxide ceramic used in thermal barriers and solid-oxide systems.'),
      term('YBCO', 'A high-temperature superconducting material containing yttrium, barium, copper, and oxygen.'),
    ],
    sections: {
      classification: facts('a group-3 metal whose chemistry strongly favors the trivalent state', 'group 3, period 5, d-block', '[Kr]4d1 5s2', 'it forms hard Y3+ compounds and behaves geochemically like the rare earth elements in many separations', 'its chemistry is simpler and more consistently trivalent than that of many neighboring transition metals'),
      electronic: facts('an [Kr]4d1 5s2 valence arrangement', 'it loses three electrons readily to form strongly Lewis-acidic Y3+ centers', '+3', 'Y2O3, YCl3, hydrated Y3+, phosphor hosts, and oxide ceramics', 'dominant d0 trivalent chemistry makes ligand-field complexity less important than oxide and coordination behavior'),
      physical: facts('a silvery metallic solid', 'it is fairly light for a transition metal and forms useful high-temperature oxides', 'metallic bonding gives a workable metal while many yttrium compounds are refractory ionic or oxide materials', 'yttrium metal, yttria ceramics, phosphor powders, and laser-host crystals', 'dust and powder control matter more than unusual bulk-metal hazards'),
      reactivity: facts('a moderately reactive metal that forms stable trivalent oxides, halides, and ceramics', 'it oxidizes in air at elevated temperature and dissolves in acids to yield Y3+ salts', 'strong stabilization of Y3+ and of oxide lattices dominates the chemistry', 'oxides, fluorides, chlorides, phosphors, and mixed-oxide materials', 'powders, hot metal, and fine ceramic precursors require oxidation and dust control'),
      occurrence: facts('monazite, bastnasite, xenotime, and other rare-earth-bearing minerals', 'it is dispersed with rare earths rather than mined chiefly as a separate large-volume ore', 'rare-earth mineral concentrates are the main practical reservoirs', 'yttrium geochemistry closely parallels the rare-earth elements despite its formal d-block placement', 'native yttrium is absent because oxidized mineral-bound forms are much more stable'),
      isotopes: facts('stable yttrium-89 together with medically important radioisotopes such as yttrium-90', 'yttrium-89 is the only stable isotope', 'radioisotopes give yttrium unusual importance in nuclear medicine and tracing', 'yttrium-90 is used in radiotherapy and isotope-labeled materials studies', 'routine bulk chemistry uses stable yttrium, but isotope applications are scientifically important'),
      production: facts('recovery and separation from rare-earth mineral concentrates', 'industrial supply depends on difficult separations from chemically similar lanthanides', 'solvent extraction and ion-exchange refining are central processing tools', 'purity control is essential for phosphors, ceramics, and electronic materials', 'supply economics track the broader rare-earth separation industry more than simple ore abundance'),
      applied: facts('phosphors, lasers, superconductors, structural ceramics, and electronic oxides', 'yttria, YAG-type materials, yttria-stabilized zirconia, YBCO, and yttrium halides', 'yttrium is important because small amounts can transform oxide optical, mechanical, and electronic properties', 'modern yttrium demand grew through display phosphors, lasers, and advanced ceramic engineering', 'hazards are generally moderate and center on dusts, powders, and specialized radioisotope use'),
    },
  }),
  makeSeed({
    id: 'zirconium',
    name: 'Zirconium',
    symbol: 'Zr',
    atomicNumber: 40,
    atomicMass: '91.224',
    group: '4',
    period: '5',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d2 5s2',
    oxidationStates: '+4',
    summaryLine:
      'Zirconium is a corrosion-resistant transition metal whose oxide stability, nuclear applications, and refractory ceramics make it important in engineering and high-temperature materials.',
    importanceLine:
      'Its chemistry links early transition-metal oxide formation to nuclear cladding, zircon minerals, and the challenge of separating zirconium from hafnium.',
    heroFacts: ['Corrosion-resistant metal', 'Zr4+ chemistry dominates', 'Important in reactor cladding', 'Derived from zircon'],
    glossaryExtras: [
      term('Zircon', 'Zirconium silicate mineral, ZrSiO4, the principal zirconium ore.'),
      term('Baddeleyite', 'A natural zirconium dioxide mineral and zirconium feedstock.'),
      term('Hafnium separation', 'Industrial removal of hafnium from zirconium for nuclear-grade metal.'),
    ],
    sections: {
      classification: facts('an early transition metal with strong oxide-forming and tetravalent chemistry', 'group 4, period 5, d-block', '[Kr]4d2 5s2', 'it forms Zr4+ compounds and highly stable oxides, halides, and coordination environments', 'its chemistry closely parallels titanium and hafnium but emphasizes refractory behavior and corrosion resistance'),
      electronic: facts('an [Kr]4d2 5s2 valence arrangement', 'it forms both ionic and covalent compounds centered on Zr4+ in oxides, halides, and complexes', '+4', 'ZrO2, ZrCl4, zircon, and coordination compounds with hard donor ligands', 'vacant d orbitals and strong oxygen affinity make oxide formation and Lewis acidity central'),
      physical: facts('a lustrous corrosion-resistant metallic solid', 'it combines useful strength with remarkable resistance to many corrosive environments', 'passivating oxide films protect the bulk metal and support demanding engineering use', 'zirconium metal, zirconia ceramics, and nuclear-grade alloy tubing', 'fine powders can be flammable even though bulk metal is comparatively easy to handle'),
      reactivity: facts('a reactive metal thermodynamically, but one whose ordinary behavior is moderated by passivating oxide films', 'fresh metal reacts with oxygen and halogens while bulk metal remains corrosion resistant in many service environments', 'formation of highly stable ZrO2 drives much of its chemistry', 'oxides, halides, zirconates, refractory ceramics, and coordination compounds', 'powders, machining swarf, and hot metal require stricter fire and oxidation control than bulk plate or tubing'),
      occurrence: facts('zircon, baddeleyite, heavy-mineral sands, and related refractory minerals', 'it is fairly abundant in crustal minerals but encountered almost entirely in stable oxide and silicate forms', 'zircon concentrates are the major industrial reservoir', 'zirconium remains mineral-bound because of very strong oxygen affinity', 'native zirconium is absent because oxide and silicate phases are much more stable'),
      isotopes: facts('multiple stable isotopes including zirconium-90, 91, 92, 94, and 96', 'several naturally occurring isotopes are stable, with zirconium-90 most abundant', 'isotopic composition matters in nuclear science and specialized analytical work', 'zirconium isotopes support reactor science, geochemistry, and precision measurement', 'routine zirconium chemistry is controlled more by hafnium content and corrosion behavior than by isotope effects'),
      production: facts('chlorination and reduction routes applied to zircon-derived feedstocks', 'production depends on converting stable oxide minerals into purifiable intermediates before metal recovery', 'separation of hafnium from zirconium is essential for many nuclear applications', 'chloride purification and tight oxygen control are critical for high-quality metal', 'supply depends on mineral-sand processing and the cost of high-purity refining'),
      applied: facts('nuclear cladding, corrosion-resistant equipment, refractory ceramics, and foundry or catalyst materials', 'zirconium metal, zirconia, zircon, zirconyl salts, and high-temperature ceramics', 'zirconium is important because it combines oxide stability with nuclear and corrosion-resistant engineering value', 'modern zirconium technology grew with reactor materials and advanced ceramics as much as with traditional zircon uses', 'hazards center on reactive powders, chloride intermediates, and high-temperature processing rather than on bulk passivated metal'),
    },
  }),
  makeSeed({
    id: 'niobium',
    name: 'Niobium',
    symbol: 'Nb',
    atomicNumber: 41,
    atomicMass: '92.90637',
    group: '5',
    period: '5',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d4 5s1',
    oxidationStates: '+3, +5',
    summaryLine:
      'Niobium is a transition metal valued for ferroniobium alloying, superconducting materials, and oxide or halide chemistry centered on the +5 state.',
    importanceLine:
      'Its chemistry connects refractory group-5 behavior to steel strengthening, superconductivity, and mineral separation from tantalum.',
    heroFacts: ['Refractory transition metal', 'Nb5+ chemistry is common', 'Major steel alloy addition', 'Important in superconductors'],
    glossaryExtras: [
      term('Pyrochlore', 'A niobium-rich oxide mineral and the leading ore of niobium.'),
      term('Ferroniobium', 'An iron-niobium alloy used to introduce niobium into steelmaking.'),
      term('Superconducting alloy', 'A metallic material that loses electrical resistance below a critical temperature.'),
    ],
    sections: {
      classification: facts('a refractory group-5 transition metal with strong high-valent oxide chemistry', 'group 5, period 5, d-block', '[Kr]4d4 5s1', 'it forms stable Nb5+ compounds together with lower-valent metallic and coordination behavior', 'its chemistry parallels tantalum but is generally more accessible in alloying and industrial oxide systems'),
      electronic: facts('an [Kr]4d4 5s1 valence arrangement', 'it forms oxides, halides, coordination compounds, and metallic phases in which high oxidation states are important', '+3 and +5, with +5 dominant in many compounds', 'Nb2O5, niobates, NbCl5, ferroniobium, and superconducting alloys', 'partially filled d orbitals support metallic conduction while strong oxygen affinity stabilizes oxidized compounds'),
      physical: facts('a gray ductile high-melting metallic solid', 'it resists heat and contributes strength in small alloy additions', 'refractory metallic bonding and stable surface oxides give useful mechanical and corrosion behavior', 'niobium metal, ferroniobium, superconducting wires, and oxide ceramics', 'bulk metal is manageable, but high-temperature processing and fine powders need controlled conditions'),
      reactivity: facts('a moderately reactive refractory metal whose chemistry is dominated by oxidation to stable oxide and halide species', 'it reacts more readily at elevated temperature and forms oxides, halides, and complex oxoanions', 'stabilization of high-valent niobium in oxygen-rich and halide environments drives the chemistry', 'niobium oxides, niobates, halides, and metallic superconducting or alloy systems', 'powders, chlorides, and hot-process streams require more care than passivated bulk metal'),
      occurrence: facts('pyrochlore, columbite-group minerals, and complex oxide ores', 'it is not abundant enough for bulk commodity status but is concentrated effectively in selected ore bodies', 'carbonatites and niobium-rich oxide deposits are the main practical reservoirs', 'niobium often occurs with tantalum and other refractory metals, making separation important', 'native niobium is absent because oxidized mineral phases are strongly favored'),
      isotopes: facts('stable niobium-93 together with radioactive nuclides used in tracing and nuclear work', 'niobium-93 is the only stable isotope', 'isotope chemistry is specialized rather than central to routine industrial use', 'niobium radioisotopes support analytical and nuclear studies', 'ordinary niobium chemistry is defined much more by refractory oxide behavior than by isotopic complexity'),
      production: facts('concentration and refining of pyrochlore ores into ferroniobium, oxides, or metal', 'industrial production usually targets alloy additives first rather than pure metal', 'oxide reduction and halide routes are used when high-purity niobium metal is needed', 'separation from tantalum and impurity control are critical refining tasks', 'supply depends strongly on a limited number of ore districts and alloy demand'),
      applied: facts('microalloyed steels, superconducting magnets, high-temperature alloys, and oxide electronics', 'ferroniobium, niobium metal, niobium-titanium alloys, niobates, and high-purity oxides', 'niobium is important because very small additions can transform steel properties and because superconducting alloys are technologically essential', 'its modern significance rose through specialty steels and cryogenic superconducting technology', 'hazards are moderate and tied mainly to dusts, powders, halides, and high-temperature processing'),
    },
  }),
  makeSeed({
    id: 'molybdenum',
    name: 'Molybdenum',
    symbol: 'Mo',
    atomicNumber: 42,
    atomicMass: '95.95',
    group: '6',
    period: '5',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d5 5s1',
    oxidationStates: '+2, +3, +4, +6',
    summaryLine:
      'Molybdenum is a refractory transition metal notable for strong Mo=O chemistry, catalytic oxides and sulfides, alloying value, and important radioisotopes in medicine.',
    importanceLine:
      'Its chemistry links variable d-block redox behavior to hydrodesulfurization catalysts, high-temperature alloys, and the Mo-99 medical supply chain.',
    heroFacts: ['Refractory transition metal', 'Multiple oxidation states', 'MoO3 and MoS2 are major materials', 'Mo-99 is medically important'],
    glossaryExtras: [
      term('Molybdenite', 'Molybdenum disulfide mineral and the principal ore of molybdenum.'),
      term('Hydrodesulfurization', 'Catalytic removal of sulfur from petroleum streams using hydrogen.'),
      term('Molybdate', 'An oxyanion family derived from oxidized molybdenum, usually in the +6 state.'),
    ],
    sections: {
      classification: facts('a refractory group-6 transition metal with broad oxidation-state chemistry', 'group 6, period 5, d-block', '[Kr]4d5 5s1', 'it forms both metallic phases and high-valent oxides or oxoanions centered on molybdenum(VI)', 'its chemistry is more oxidation-state-diverse and catalytically important than that of niobium'),
      electronic: facts('an [Kr]4d5 5s1 valence arrangement', 'it forms coordination compounds, oxides, sulfides, and metallic phases across several oxidation states', '+2, +3, +4, and +6', 'MoO3, molybdate species, MoS2, and metal alloys or enzyme centers', 'partially filled d orbitals support rich redox behavior and multiple bonding to oxygen or sulfur'),
      physical: facts('a hard high-melting metallic solid', 'it retains strength at elevated temperature and is valuable in refractory alloys', 'strong metallic bonding and refractory crystal behavior explain high melting point and structural durability', 'molybdenum metal, molybdenum disulfide lubricants, and oxide catalysts', 'powders and hot-working operations require routine industrial control but bulk metal is manageable'),
      reactivity: facts('a transition metal with important oxide and sulfide redox chemistry rather than violent bulk-metal reactivity', 'it forms stable oxides, sulfides, halides, and catalytic surface species under oxidizing or sulfidizing conditions', 'strong Mo-O and Mo-S bonding plus accessible redox changes drive the chemistry', 'molybdates, MoO3 catalysts, MoS2 catalysts and lubricants, and halide precursors', 'process hazards are usually tied to dusts, hot surfaces, and catalyst handling rather than to spontaneous ignition of bulk metal'),
      occurrence: facts('molybdenite, porphyry copper-molybdenum systems, and selected secondary minerals', 'it is less abundant than iron but concentrated enough in sulfide deposits to support major recovery', 'porphyry deposits and molybdenite-bearing sulfide ores are the main practical reservoirs', 'molybdenum often follows sulfur-rich ore geology and can be recovered with copper mining', 'native molybdenum is absent because sulfide and oxide mineral forms are much more stable'),
      isotopes: facts('several stable isotopes together with medically important molybdenum-99', 'natural molybdenum contains multiple stable isotopes while molybdenum-99 is radioactive', 'isotopes matter in geochemistry, nuclear science, and diagnostic-medicine supply chains', 'molybdenum-99 is the parent of technetium-99m used in medical imaging', 'isotope significance makes molybdenum unusual among refractory alloy metals'),
      production: facts('flotation roasting and refining of molybdenite concentrates, often alongside copper production', 'industrial production commonly converts sulfides into purified oxide before reduction or chemical finishing', 'byproduct recovery from porphyry copper operations is a major supply route', 'sulfur management, oxide purity, and downstream reduction control are essential', 'supply depends strongly on copper mining economics and catalyst or alloy demand'),
      applied: facts('high-strength alloys, petroleum catalysis, lubricants, pigments, and isotope-production targets', 'molybdenum metal, ferro-molybdenum, MoO3, molybdates, and MoS2', 'molybdenum is important because it combines refractory metallic behavior with highly useful oxide and sulfide chemistry', 'its industrial significance expanded through alloy steels, petroleum refining, and nuclear medicine', 'hazards are generally moderate and focus on dusts, process fumes, and radioactive target handling where relevant'),
    },
  }),
  makeSeed({
    id: 'technetium',
    name: 'Technetium',
    symbol: 'Tc',
    atomicNumber: 43,
    atomicMass: '[98]',
    group: '7',
    period: '5',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d5 5s2',
    oxidationStates: '+4, +7',
    summaryLine:
      'Technetium is the lightest element with no stable isotopes and is best known through pertechnetate chemistry and the diagnostic-radioisotope role of technetium-99m.',
    importanceLine:
      'Its chemistry links transition-metal redox behavior to nuclear medicine, fission-product management, and the environmental mobility of oxoanions.',
    heroFacts: ['No stable isotopes', 'Pertechnetate chemistry is central', 'Tc-99m is medically indispensable', 'Produced through fission routes'],
    glossaryExtras: [
      term('Pertechnetate', 'The tetrahedral TcO4- oxyanion, characteristic of technetium in the +7 state.'),
      term('Fission product', 'A nuclide formed when heavy nuclei such as uranium split.'),
      term('Technetium-99m', 'A short-lived metastable radioisotope widely used in diagnostic imaging.'),
    ],
    sections: {
      classification: facts('a group-7 transition metal known mainly through radioactive isotopes rather than bulk elemental abundance', 'group 7, period 5, d-block', '[Kr]4d5 5s2', 'it forms oxoanions and coordination compounds across several redox states, with technetium(VII) especially important', 'its chemistry parallels manganese and rhenium but is dominated by radiochemistry and tracer use'),
      electronic: facts('an [Kr]4d5 5s2 valence arrangement', 'it forms coordination compounds and oxoanions with accessible redox states in aqueous and nuclear chemistry', '+4 and +7 are especially important in introductory descriptions', 'pertechnetate, reduced Tc complexes, and oxide-containing radiopharmaceutical systems', 'd-electron redox flexibility governs both environmental mobility and imaging chemistry'),
      physical: facts('a silvery radioactive metallic solid known mostly in specialized forms rather than bulk consumer use', 'its physical handling is shaped more by radiological control than by ordinary metallurgy', 'metallic bonding exists in the element, but practical work usually involves tracer quantities, salts, or generator systems', 'technetium metal, pertechnetate salts, and radiopharmaceutical preparations', 'shielding, contamination control, and decay timing dominate handling requirements'),
      reactivity: facts('a redox-active transition metal whose higher oxoanions can be chemically mobile', 'it interconverts between pertechnetate and more reduced coordination or oxide forms under changing redox conditions', 'stabilization of TcO4- in oxidizing environments and reduced complexes in controlled chemistry drives the behavior', 'pertechnetate salts, reduced radiopharmaceutical complexes, and waste-form oxides', 'the dominant practical hazards are radiological rather than corrosive or pyrophoric'),
      occurrence: facts('trace natural formation in uranium ores and far larger production as a nuclear fission product', 'it is effectively absent as a normal stable crustal element because all isotopes are radioactive', 'reactor fuel, reprocessing streams, and selected natural uranium systems are the main reservoirs', 'pertechnetate mobility makes technetium important in nuclear-waste and groundwater studies', 'native technetium is not encountered as an ordinary natural material'),
      isotopes: facts('radioisotopes such as technetium-99 and technetium-99m', 'technetium has no stable isotopes', 'short-lived technetium-99m transformed diagnostic medicine, while long-lived technetium-99 matters in waste management', 'medical imaging generators and nuclear-fuel-cycle studies are the principal isotope applications', 'all technetium chemistry requires radiological control and time-aware handling'),
      production: facts('generation from molybdenum-99 decay and recovery from nuclear fission streams', 'supply is governed by nuclear production routes rather than mining or conventional metallurgy', 'technetium-99m is obtained from technetium generators loaded with molybdenum-99', 'radiochemical purification and decay management are essential process constraints', 'availability depends on reactor or accelerator production infrastructure and isotope logistics'),
      applied: facts('diagnostic nuclear medicine, radiochemical tracing, and waste-form chemistry studies', 'pertechnetate, reduced technetium radiopharmaceutical complexes, and nuclear-fuel-cycle residues', 'technetium is important because its isotope chemistry turned a synthetic element into a routine clinical tool', 'its discovery and later medical adoption made technetium a landmark in both nuclear chemistry and medicine', 'hazards are inseparable from radioactivity, contamination control, and isotope-specific decay properties'),
    },
  }),
  makeSeed({
    id: 'ruthenium',
    name: 'Ruthenium',
    symbol: 'Ru',
    atomicNumber: 44,
    atomicMass: '101.07',
    group: '8',
    period: '5',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d7 5s1',
    oxidationStates: '+2, +3, +4, +8',
    summaryLine:
      'Ruthenium is a platinum-group transition metal known for robust catalytic chemistry, multiple oxidation states, and specialized electronic or alloy uses.',
    importanceLine:
      'Its chemistry links noble-metal durability to redox-active complexes, oxide catalysis, and the recovery of minor but valuable platinum-group elements.',
    heroFacts: ['Platinum-group metal', 'Multiple oxidation states', 'Important catalyst metal', 'Recovered with PGM streams'],
    glossaryExtras: [
      term('Platinum-group metal', 'One of the chemically valuable noble transition metals recovered from specialized ores and refinery streams.'),
      term('Ruthenate', 'An oxyanion family derived from oxidized ruthenium.'),
      term('Olefin metathesis', 'A catalytic carbon-carbon double-bond reorganization reaction often associated with ruthenium catalysts.'),
    ],
    sections: {
      classification: facts('a platinum-group transition metal combining noble-metal durability with broad oxidation-state chemistry', 'group 8, period 5, d-block', '[Kr]4d7 5s1', 'it forms metallic, coordination, and oxide compounds ranging from lower oxidation states to very high oxo species', 'its chemistry is more catalytically versatile than that of technetium and less commonly encountered than iron or osmium'),
      electronic: facts('an [Kr]4d7 5s1 valence arrangement', 'it forms coordination compounds and catalytic intermediates across several oxidation states', '+2, +3, +4, and +8', 'ruthenium complexes, RuO2, ruthenates, and organometallic catalysts', 'partially filled d orbitals and strong metal-ligand interactions make catalytic and redox chemistry especially rich'),
      physical: facts('a hard silvery platinum-group metal', 'it is dense, corrosion resistant, and useful in small alloy or electronic additions', 'strong metallic bonding and noble-metal character explain durability and high-temperature stability', 'ruthenium metal, RuO2 coatings, and homogeneous catalyst complexes', 'bulk metal is manageable, but some volatile oxides and catalytic powders demand more care'),
      reactivity: facts('a relatively noble metal whose most important chemistry appears in oxidized complexes and catalytic cycles', 'it forms oxides, halides, coordination compounds, and highly active organometallic catalysts', 'multiple accessible oxidation states and strong ligand interactions drive reactivity', 'RuO2, ruthenium halides, metathesis catalysts, and redox-active complexes', 'some ruthenium oxides and catalytic materials require exposure control because volatility or bioactivity can increase hazard'),
      occurrence: facts('nickel-copper sulfide ores, platinum-group deposits, and refinery byproduct streams', 'it is rare in crustal abundance but economically recovered with other platinum-group metals', 'PGM concentrates and refinery residues are the main practical reservoirs', 'ruthenium occurrence is controlled by platinum-group mineralogy rather than simple bulk abundance', 'native ruthenium can occur in platinum-group assemblages but is uncommon'),
      isotopes: facts('several stable isotopes including ruthenium-96, 98, 99, 100, 101, 102, and 104', 'multiple naturally occurring isotopes are stable, while selected radioisotopes are important in nuclear contexts', 'isotopic composition supports analytical chemistry, cosmochemistry, and fission-product studies', 'ruthenium isotopes are useful in tracing and nuclear-fuel-cycle analysis', 'routine ruthenium chemistry is driven far more by catalysis and redox behavior than by isotope issues'),
      production: facts('recovery during refining of platinum-group metal concentrates and related base-metal streams', 'production is a byproduct-intensive separation problem rather than a large standalone mining route', 'oxidative dissolution, selective precipitation, and solvent-extraction or chloride chemistry are common refining tools', 'high purity is essential because ruthenium is often used catalytically or electronically', 'supply depends on PGM mining and refinery throughput more than on ruthenium demand alone'),
      applied: facts('catalysis, electronics, hard alloying, electrochemistry, and specialty organometallic synthesis', 'ruthenium metal, RuO2, ruthenium chlorides, and metathesis or redox catalysts', 'ruthenium is important because it can unite noble-metal stability with unusually diverse catalytic chemistry', 'its scientific profile grew strongly with homogeneous catalysis and advanced electrochemical materials', 'hazards are moderate for the metal but increase for fine powders, bioactive complexes, and oxidized species'),
    },
  }),
  makeSeed({
    id: 'rhodium',
    name: 'Rhodium',
    symbol: 'Rh',
    atomicNumber: 45,
    atomicMass: '102.90550',
    group: '9',
    period: '5',
    block: 'd',
    category: 'Transition metal',
    roomState: 'Solid',
    electronConfiguration: '[Kr]4d8 5s1',
    oxidationStates: '+1, +3',
    summaryLine:
      'Rhodium is a rare platinum-group metal prized for catalytic selectivity, chemical durability, and reflective plating applications.',
    importanceLine:
      'Its chemistry links noble transition-metal behavior to automotive catalysis, coordination chemistry, and the economics of scarce high-value metals.',
    heroFacts: ['Rare platinum-group metal', 'Rhodium catalysts are highly selective', 'Corrosion resistant', 'Critical in catalytic converters'],
    glossaryExtras: [
      term('Catalytic converter', 'An exhaust-treatment device that uses catalysts such as rhodium to reduce harmful emissions.'),
      term('Wilkinson catalyst', 'A classic rhodium complex used in homogeneous hydrogenation chemistry.'),
      term('Noble metal', 'A metal resistant to oxidation and corrosion under many ordinary conditions.'),
    ],
    sections: {
      classification: facts('a noble group-9 transition metal within the platinum-group family', 'group 9, period 5, d-block', '[Kr]4d8 5s1', 'it forms stable coordination complexes and catalytic species while remaining corrosion resistant as a metal', 'its chemistry is less bulk-abundant than cobalt or iridium but highly important in catalysis'),
      electronic: facts('an [Kr]4d8 5s1 valence arrangement', 'it forms coordination compounds and organometallic catalysts in which Rh(I) and Rh(III) are especially important', '+1 and +3', 'rhodium chlorides, Wilkinson-type complexes, plated rhodium, and catalytic surfaces', 'd-electron configuration and strong ligand bonding make rhodium especially useful for selective homogeneous and heterogeneous catalysis'),
      physical: facts('a hard silvery-white noble metal', 'it is highly reflective, corrosion resistant, and mechanically durable in thin coatings', 'noble-metal bonding and surface stability explain its resistance to tarnish and attack', 'rhodium plating, catalyst powders, and high-value refinery metal', 'bulk metal is stable, but fine powders and process salts require routine industrial hygiene'),
      reactivity: facts('a relatively unreactive noble metal whose chemistry becomes important mainly in complexes and catalytic cycles', 'it participates in oxidative addition, hydrogenation, carbonylation, and emission-control catalysis more readily than bulk corrosion chemistry', 'stable low-valent and trivalent coordination states drive the chemistry', 'rhodium complexes, chloride salts, catalytic converter surfaces, and organometallic catalysts', 'hazards are usually tied to soluble salts and catalyst handling rather than to the metallic surface itself'),
      occurrence: facts('platinum-group ores, nickel-copper sulfides, and refinery byproduct streams', 'it is one of the rarest economically important metals and is recovered as a high-value minor component', 'PGM concentrates and refinery residues are the dominant practical reservoirs', 'rhodium occurrence is controlled by scarce platinum-group mineralogy rather than by bulk crustal abundance', 'native rhodium is rare and usually associated with other noble metals'),
      isotopes: facts('stable rhodium-103 together with specialized radioactive isotopes', 'rhodium-103 is the only stable isotope', 'radioisotopes have analytical and nuclear-use significance, but ordinary chemistry uses stable rhodium', 'rhodium radioisotopes support tracing and nuclear studies', 'routine rhodium chemistry is defined far more by catalytic behavior and scarcity than by isotope diversity'),
      production: facts('recovery during refining of platinum-group metal concentrates', 'production is entirely tied to complex refinery separations from mixed noble-metal streams', 'selective dissolution, precipitation, and chloride-based refining routes are central', 'purity control is critical because rhodium is often used in very demanding catalytic roles', 'supply depends strongly on PGM mining output and can be highly price volatile'),
      applied: facts('automotive exhaust catalysis, homogeneous catalysis, reflective plating, and specialty alloys', 'rhodium metal, rhodium complexes, plated coatings, and catalytic converter materials', 'rhodium is important because it delivers exceptional catalytic selectivity and durability in small amounts', 'its industrial importance rose dramatically with emission-control catalysis and modern organometallic chemistry', 'hazards are moderate for the metal but require tighter control for soluble salts and fine catalyst powders'),
    },
  }),
];
