"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.astronomyAccentSources = exports.astronomyUnits = exports.astronomyTopics = exports.astronomySubject = void 0;
const createStructuredSubject_1 = require("@/content/subjects/shared/createStructuredSubject");
const topics = [
    {
        id: 'foundations-of-astronomy',
        title: 'Foundations of Astronomy',
        description: 'The scope of astronomy, observational methods, and the scale of the universe.',
        units: [
            { title: 'What Is Astronomy?' },
            { title: 'The Celestial Sphere' },
            { title: 'Motions in the Sky' },
            { title: 'Astronomical Coordinates' },
            { title: 'Time, Seasons, and Calendars' },
            { title: 'Scale of the Universe' },
        ],
    },
    {
        id: 'observing-the-universe',
        title: 'Observing the Universe',
        description: 'Telescopes, detectors, light, and the methods used to collect astronomical information.',
        units: [
            { title: 'Nature of Light' },
            { title: 'Telescopes Basics' },
            { title: 'Optical Telescopes' },
            { title: 'Radio and Space Telescopes' },
            { title: 'Spectroscopy in Astronomy' },
            { title: 'Imaging and Detectors' },
            { title: 'Resolution and Magnification' },
            { title: 'Observational Challenges' },
        ],
    },
    {
        id: 'earth-moon-and-solar-system-basics',
        title: 'Earth, Moon, and Solar System Basics',
        description: 'The structure and motion of nearby astronomical bodies and the local context of planetary science.',
        units: [
            { title: 'Earth as a Planet' },
            { title: 'The Moon' },
            { title: 'Phases and Eclipses' },
            { title: 'Tides' },
            { title: 'Solar System Overview' },
            { title: 'Formation of the Solar System' },
            { title: 'Small Bodies: Asteroids, Comets, and Meteoroids' },
        ],
    },
    {
        id: 'the-planets',
        title: 'The Planets',
        description: 'Comparative study of terrestrial planets, giant planets, and planetary systems.',
        units: [
            { title: 'Mercury' },
            { title: 'Venus' },
            { title: 'Earth' },
            { title: 'Mars' },
            { title: 'Jupiter' },
            { title: 'Saturn' },
            { title: 'Uranus' },
            { title: 'Neptune' },
            { title: 'Dwarf Planets' },
        ],
    },
    {
        id: 'the-sun-and-stars',
        title: 'The Sun and Stars',
        description: 'Stellar structure, energy generation, classification, and the life cycles of stars.',
        units: [
            { title: 'The Sun' },
            { title: 'Solar Structure' },
            { title: 'Nuclear Fusion in Stars' },
            { title: 'Stellar Properties' },
            { title: 'Hertzsprung-Russell Diagram', aliases: ['Hertzsprung Russell Diagram'] },
            { title: 'Star Formation' },
            { title: 'Main Sequence Stars' },
            { title: 'Red Giants and Supergiants' },
            { title: 'White Dwarfs' },
            { title: 'Neutron Stars' },
            { title: 'Black Holes Basics' },
        ],
    },
    {
        id: 'stellar-evolution-and-nucleosynthesis',
        title: 'Stellar Evolution and Nucleosynthesis',
        description: 'How stars evolve and how chemical elements are formed in stellar environments.',
        units: [
            { title: 'Protostars' },
            { title: 'Stellar Lifetimes' },
            { title: 'Low-Mass Star Evolution', aliases: ['Low Mass Star Evolution'] },
            { title: 'High-Mass Star Evolution', aliases: ['High Mass Star Evolution'] },
            { title: 'Supernovae' },
            { title: 'Element Formation in Stars' },
            { title: 'Compact Stellar Remnants' },
        ],
    },
    {
        id: 'galaxies',
        title: 'Galaxies',
        description: 'The structure, classification, and evolution of galaxies and large stellar systems.',
        units: [
            { title: 'What Is a Galaxy?' },
            { title: 'Spiral Galaxies' },
            { title: 'Elliptical Galaxies' },
            { title: 'Irregular Galaxies' },
            { title: 'The Milky Way' },
            { title: 'Galactic Structure' },
            { title: 'Supermassive Black Holes' },
            { title: 'Galaxy Formation and Evolution' },
        ],
    },
    {
        id: 'cosmology',
        title: 'Cosmology',
        description: 'The origin, expansion, and large-scale structure of the universe.',
        units: [
            { title: 'Expanding Universe' },
            { title: "Hubble's Law", aliases: ['Hubbles Law'] },
            { title: 'Big Bang Cosmology' },
            { title: 'Cosmic Microwave Background' },
            { title: 'Dark Matter' },
            { title: 'Dark Energy' },
            { title: 'Large-Scale Structure', aliases: ['Large Scale Structure'] },
            { title: 'Fate of the Universe' },
        ],
    },
    {
        id: 'astrophysics-foundations',
        title: 'Astrophysics Foundations',
        description: 'The physical laws behind astronomical systems, including gravity, radiation, and orbital behavior.',
        units: [
            { title: 'Gravity in Astronomy' },
            { title: "Orbits and Kepler's Laws", aliases: ['Orbits and Keplers Laws'] },
            { title: 'Radiation and Blackbody Spectra' },
            { title: 'Doppler Effect in Astronomy' },
            { title: 'Energy Transport in Stars' },
            { title: 'Relativity in Astrophysics' },
            { title: 'Accretion and High-Energy Phenomena', aliases: ['Accretion and High Energy Phenomena'] },
        ],
    },
    {
        id: 'exoplanets-and-astrobiology',
        title: 'Exoplanets and Astrobiology',
        description: 'Planets around other stars, methods of detection, habitability, and the scientific search for life.',
        units: [
            { title: 'Exoplanet Detection Methods' },
            { title: 'Transit Method' },
            { title: 'Radial Velocity Method' },
            { title: 'Planetary Habitability' },
            { title: 'Habitable Zones' },
            { title: 'Atmospheres of Exoplanets' },
            { title: 'Astrobiology Foundations' },
            { title: 'Search for Life Beyond Earth' },
        ],
    },
];
const built = (0, createStructuredSubject_1.createStructuredSubject)({
    id: 'astronomy-astrophysics',
    title: 'Astronomy / Astrophysics',
    description: 'Local-first astronomy and astrophysics content spanning observation, planetary systems, stars, galaxies, cosmology, and exoplanets.',
    tagline: 'Read, review, and quiz through a broad astronomy and astrophysics study sequence.',
    accent: 'oxygen',
    practitionerPlural: 'astronomers',
    topics,
    accentCycle: createStructuredSubject_1.defaultSubjectAccentCycle,
});
exports.astronomySubject = built.subject;
exports.astronomyTopics = built.topics;
exports.astronomyUnits = built.units;
exports.astronomyAccentSources = built.accentSources;
