"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.actinideElementSeeds = void 0;
const seedFactories_1 = require("@/content/subjects/chemistry/seedFactories");
function facts(a, b, c, d, e) {
    return [a, b, c, d, e];
}
function buildSections(config) {
    return {
        classification: facts(config.classificationLead, `${config.group}, period ${config.period}, ${config.block}-block`, config.electronConfiguration, `it is commonly encountered through ${config.compoundsLine}`, config.comparisonNote),
        electronic: facts(`an ${config.electronConfiguration} valence arrangement with accessible 5f/6d participation`, config.reactivityLead, config.oxidationStates, config.compoundsLine, 'orbital participation, shielding, and heavy-element effects strongly influence actinide bonding'),
        physical: facts(config.physicalLead, config.physicalNote, 'radioactivity, oxidation sensitivity, and dense metallic bonding govern practical handling', config.appliedSystems, config.hazardNote),
        reactivity: facts(config.reactivityLead, `it forms ${config.compoundsLine}`, 'oxygen, halide, and donor-ligand bonding drive much of the accessible chemistry', config.appliedSystems, config.hazardNote),
        occurrence: facts(config.occurrenceLead, config.occurrenceNote, 'ore mineralogy, decay chains, or reactor production determine how the element is encountered', config.productionRoutes, config.significanceNote),
        isotopes: facts(config.isotopeLead, config.isotopeDetail, 'isotope identity determines scientific use, half-life, and radiological behavior', config.isotopeUse, 'all practical work depends on isotope-specific containment and monitoring'),
        production: facts(config.productionLead, config.productionRoutes, 'radiochemical separation, purification, and containment dominate practical supply', config.appliedSystems, config.significanceNote),
        applied: facts(config.appliedLead, config.appliedSystems, config.significanceNote, config.comparisonNote, config.hazardNote),
    };
}
function makeSeed(config) {
    const sections = buildSections(config);
    return {
        ...config,
        sections: {
            classification: (0, seedFactories_1.classificationSection)(config.name, sections.classification),
            electronic: (0, seedFactories_1.electronicSection)(config.name, sections.electronic),
            physical: (0, seedFactories_1.physicalSection)(config.name, sections.physical),
            reactivity: (0, seedFactories_1.reactivitySection)(config.name, sections.reactivity),
            occurrence: (0, seedFactories_1.occurrenceSection)(config.name, sections.occurrence),
            isotopes: (0, seedFactories_1.isotopeSection)(config.name, sections.isotopes),
            production: (0, seedFactories_1.productionSection)(config.name, sections.production),
            applied: (0, seedFactories_1.appliedSection)(config.name, sections.applied),
        },
    };
}
exports.actinideElementSeeds = [
    makeSeed({
        id: 'actinium',
        name: 'Actinium',
        symbol: 'Ac',
        atomicNumber: 89,
        atomicMass: '[227]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]6d1 7s2',
        oxidationStates: '+3',
        summaryLine: 'Actinium is an early actinide whose Ac3+ chemistry resembles lanthanum, but whose radioactivity makes it scientifically important in nuclear medicine and radiochemistry.',
        importanceLine: 'Its chemistry links simple trivalent actinide behavior to alpha-emitting isotopes, decay chains, and targeted radiotherapy research.',
        heroFacts: ['Early actinide metal', 'Ac3+ dominates chemistry', 'Strong alpha-emitter isotopes', 'Important in radiotherapy research'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Actinide', 'A heavy f-block element with important radiochemical behavior.'),
            (0, seedFactories_1.term)('Actinium-225', 'A short-lived alpha-emitting isotope widely studied for targeted therapy.'),
            (0, seedFactories_1.term)('Decay chain', 'A sequence of radioactive transformations from one nuclide to another.'),
        ],
        classificationLead: 'a radioactive early actinide metal with chemistry dominated by the Ac3+ ion',
        comparisonNote: 'it behaves more like lanthanum in ordinary coordination chemistry than like the multivalent mid-actinides',
        compoundsLine: 'actinium oxides, halides, Ac3+ salts, and radiopharmaceutical precursors',
        physicalLead: 'a dense radioactive metallic solid encountered only in specialized radiochemical settings',
        physicalNote: 'macroscopic handling is rare, so physical characterization is secondary to isotope management and containment',
        reactivityLead: 'a reactive actinide whose practical chemistry is overwhelmingly trivalent and ionic',
        occurrenceLead: 'trace quantities in uranium ores and decay-series materials',
        occurrenceNote: 'natural occurrence is minute, so useful quantities depend mainly on radiochemical isolation',
        isotopeLead: 'radioisotopes such as actinium-227 and actinium-225',
        isotopeDetail: 'actinium has no stable isotopes and is defined by alpha-emitting members of decay chains',
        isotopeUse: 'targeted alpha therapy, tracer studies, and nuclear-structure research',
        productionLead: 'recovery from decay chains and specialized nuclear-production routes',
        productionRoutes: 'radium or thorium decay sources, irradiation, and rapid radiochemical purification',
        appliedLead: 'radiopharmaceutical development, tracer chemistry, and fundamental radiochemistry',
        appliedSystems: 'Ac-225 therapeutic precursors, actinium salts, tracer sources, and decay-chain standards',
        significanceNote: 'its importance is rising because alpha-emitter therapy depends on reliable isotope production and handling',
        hazardNote: 'hazards are radiological and contamination-driven rather than determined by ordinary bulk-metal handling',
    }),
    makeSeed({
        id: 'thorium',
        name: 'Thorium',
        symbol: 'Th',
        atomicNumber: 90,
        atomicMass: '232.0377',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]6d2 7s2',
        oxidationStates: '+4',
        summaryLine: 'Thorium is an abundant actinide whose strongly tetravalent chemistry underlies refractory oxide materials, fertile-fuel concepts, and classic actinide coordination chemistry.',
        importanceLine: 'Its chemistry links early-actinide covalency to monazite minerals, ThO2 materials, and alternative nuclear-fuel cycles.',
        heroFacts: ['Abundant actinide', 'Th4+ dominates chemistry', 'ThO2 is highly refractory', 'Important in fertile-fuel discussions'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Fertile material', 'A material that can be converted into a fissile nuclide in a reactor.'),
            (0, seedFactories_1.term)('Monazite', 'A phosphate mineral that can contain thorium and rare earths.'),
            (0, seedFactories_1.term)('Thorium dioxide', 'A refractory actinide oxide once used in mantles, ceramics, and fuels.'),
        ],
        classificationLead: 'an early actinide metal with strongly tetravalent chemistry and comparatively accessible mineral abundance',
        comparisonNote: 'it is less multivalent than uranium and neptunium, so Th4+ dominates most coordination and materials chemistry',
        compoundsLine: 'thorium dioxide, thorium halides, thorium nitrate, and Th4+ coordination compounds',
        physicalLead: 'a dense silvery radioactive metal that quickly develops surface oxides',
        physicalNote: 'its most important physical forms are often refractory oxide ceramics and fuel-related materials rather than exposed metal',
        reactivityLead: 'a reactive actinide metal whose chemistry is centered on stable Th4+ oxides and salts',
        occurrenceLead: 'thorium-bearing minerals such as monazite, thorite, and heavy-mineral sands',
        occurrenceNote: 'thorium is relatively abundant for an actinide and is recovered from mineral concentrates rather than trace nuclear streams',
        isotopeLead: 'thorium-232 together with shorter-lived decay-series isotopes',
        isotopeDetail: 'thorium-232 is long lived and defines the thorium decay series',
        isotopeUse: 'nuclear-fuel research, dating studies, and radiological tracing',
        productionLead: 'refining of thorium-bearing mineral concentrates and specialized nuclear-grade purification',
        productionRoutes: 'monazite processing, solvent extraction, precipitation, and oxide conversion',
        appliedLead: 'fertile-fuel research, refractory ceramics, specialized catalysts, and radiochemical standards',
        appliedSystems: 'ThO2 ceramics, thorium nitrate, thorium halides, and fuel-cycle precursor materials',
        significanceNote: 'its modern significance comes from nuclear-fuel-cycle discussions and the extraordinary stability of ThO2',
        hazardNote: 'hazards combine radiological control with fine-particle inhalation risk from thorium-containing dusts',
    }),
    makeSeed({
        id: 'protactinium',
        name: 'Protactinium',
        symbol: 'Pa',
        atomicNumber: 91,
        atomicMass: '231.03588',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f2 6d1 7s2',
        oxidationStates: '+4, +5',
        summaryLine: 'Protactinium is a scarce radioactive actinide whose Pa(V) chemistry provides an important bridge between thorium and uranium behavior.',
        importanceLine: 'Its chemistry links early-actinide oxo bonding to geochemistry, nuclear decay chains, and difficult radiochemical separations.',
        heroFacts: ['Scarce actinide', 'Pa(V) is central', 'Bridge between Th and U chemistry', 'Important in radiochemistry'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Actinyl-like species', 'Oxygen-rich cationic species characteristic of some early actinides.'),
            (0, seedFactories_1.term)('Geochemical tracer', 'An element or isotope used to track Earth-system processes.'),
            (0, seedFactories_1.term)('Radiochemical separation', 'Isolation of radioactive elements using chemical methods.'),
        ],
        classificationLead: 'a rare early actinide metal whose chemistry centers on high-valent oxygen-rich species',
        comparisonNote: 'it bridges the more strictly tetravalent chemistry of thorium and the broader multivalency of uranium',
        compoundsLine: 'protactinium oxides, fluorides, Pa(V) salts, and oxygen-rich coordination species',
        physicalLead: 'a dense radioactive metallic solid known mainly through specialized research quantities',
        physicalNote: 'scarcity and radioactivity make its physical characterization secondary to chemical separation and control',
        reactivityLead: 'an actinide whose accessible +5 state gives it strongly oxygen-seeking radiochemical behavior',
        occurrenceLead: 'trace concentrations in uranium ores and decay-series materials',
        occurrenceNote: 'protactinium is extraordinarily scarce in nature and generally recovered only during specialized separations',
        isotopeLead: 'protactinium-231 together with shorter-lived reactor or decay products',
        isotopeDetail: 'protactinium-231 is long lived enough to matter in geochemistry and radiological handling',
        isotopeUse: 'ocean and sediment tracing, decay studies, and nuclear research',
        productionLead: 'recovery during uranium-thorium processing and specialized nuclear chemistry',
        productionRoutes: 'ore dissolution, selective extraction, ion exchange, and radiochemical purification',
        appliedLead: 'geochemical tracing, decay research, and fundamental actinide chemistry',
        appliedSystems: 'Pa(V) salts, fluoride complexes, tracer sources, and research reference materials',
        significanceNote: 'its importance lies in the insight it gives into early-actinide bonding and Earth-system tracing',
        hazardNote: 'hazards are dominated by radioactivity, contamination control, and the difficulty of working with tiny quantities',
    }),
    makeSeed({
        id: 'uranium',
        name: 'Uranium',
        symbol: 'U',
        atomicNumber: 92,
        atomicMass: '238.02891',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f3 6d1 7s2',
        oxidationStates: '+3, +4, +5, +6',
        summaryLine: 'Uranium is the most consequential actinide in energy and geochemistry, with multivalent chemistry built around U(IV) solids and the uranyl U(VI) ion.',
        importanceLine: 'Its chemistry links nuclear fuel, ore geology, uranyl coordination, environmental migration, and the modern history of atomic science.',
        heroFacts: ['Central nuclear-fuel element', 'Uranyl chemistry is major', 'Occurs in uranium minerals', 'Multiple accessible oxidation states'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Uranyl ion', 'The linear UO2 2+ cation characteristic of many uranium(VI) compounds.'),
            (0, seedFactories_1.term)('Yellowcake', 'Concentrated uranium oxide product from ore processing.'),
            (0, seedFactories_1.term)('Fuel cycle', 'The set of processes involved in producing, using, and managing nuclear fuel.'),
        ],
        classificationLead: 'a multivalent actinide metal whose chemistry ranges from U(IV) solids to highly mobile uranyl species',
        comparisonNote: 'it is the benchmark actinide for comparing ore geology, actinyl chemistry, and nuclear-fuel processing',
        compoundsLine: 'uraninite-derived oxides, uranium halides, uranyl salts, UF6, and mixed-oxide fuel materials',
        physicalLead: 'a dense radioactive metallic solid more often encountered as oxides or fuel compounds than as exposed metal',
        physicalNote: 'its physical importance comes from fuel density, oxide stability, and the volatility of selected fluorides',
        reactivityLead: 'a reactive actinide with especially important U(IV), U(VI), and oxygen-rich coordination chemistry',
        occurrenceLead: 'uraninite, carnotite, sandstone-hosted ores, and fuel-cycle materials',
        occurrenceNote: 'uranium is abundant enough to be mined and also persists in environmental systems through soluble uranyl species',
        isotopeLead: 'uranium-238, uranium-235, and uranium-234',
        isotopeDetail: 'natural uranium contains fissile U-235 and fertile U-238, making isotope composition technologically decisive',
        isotopeUse: 'nuclear fuel, geochronology, environmental tracing, and decay-series studies',
        productionLead: 'mining, hydrometallurgical extraction, oxide concentration, enrichment, and fuel conversion',
        productionRoutes: 'ore leaching, solvent extraction, yellowcake refining, UF6 conversion, enrichment, and fuel fabrication',
        appliedLead: 'nuclear fuel, geochronology, shielding, catalysts, and analytical tracing',
        appliedSystems: 'UO2 fuel, UF6 conversion streams, uranyl salts, mixed oxides, and depleted-uranium materials',
        significanceNote: 'its chemistry is central to modern nuclear energy, weapons history, environmental remediation, and isotope dating',
        hazardNote: 'hazards include both radiological exposure and heavy-metal toxicity, especially for mobile uranium compounds',
    }),
    makeSeed({
        id: 'neptunium',
        name: 'Neptunium',
        symbol: 'Np',
        atomicNumber: 93,
        atomicMass: '[237]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f4 6d1 7s2',
        oxidationStates: '+3, +4, +5, +6, +7',
        summaryLine: 'Neptunium is the first transuranium element and a multivalent actinide whose Np(V) and Np(VI) chemistry is important in fuel-cycle separations and long-term waste behavior.',
        importanceLine: 'Its chemistry links advanced fuel processing to actinyl bonding, redox control, and the environmental science of long-lived actinides.',
        heroFacts: ['First transuranium element', 'Wide oxidation-state range', 'Important in fuel-cycle chemistry', 'Long-lived Np-237 is significant'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Transuranium element', 'An element with atomic number greater than uranium.'),
            (0, seedFactories_1.term)('Redox control', 'Management of oxidation state during separation or environmental transport.'),
            (0, seedFactories_1.term)('Waste form', 'A solid or conditioned material used to immobilize radioactive waste.'),
        ],
        classificationLead: 'a multivalent transuranium actinide whose chemistry is dominated by redox-sensitive cations and actinyl species',
        comparisonNote: 'it extends uranium-like actinyl chemistry into the transuranium region and is crucial in reprocessing science',
        compoundsLine: 'neptunium oxides, halides, Np(V) and Np(VI) actinyl species, and fuel-cycle intermediates',
        physicalLead: 'a dense radioactive metallic solid handled mainly as oxides, salts, and nuclear-process materials',
        physicalNote: 'its physical profile matters most through fuel-cycle forms and immobilized waste systems rather than exposed metal',
        reactivityLead: 'an actinide with unusually broad accessible oxidation states under solution and process conditions',
        occurrenceLead: 'trace reactor-bred material and minute decay-chain presence rather than mineable natural reservoirs',
        occurrenceNote: 'practical neptunium is generated in reactors and managed through fuel-cycle separations',
        isotopeLead: 'neptunium-237 and related reactor-produced isotopes',
        isotopeDetail: 'Np-237 is long lived enough to matter strongly in waste management and transmutation discussions',
        isotopeUse: 'fuel-cycle research, waste studies, target preparation, and nuclear forensics',
        productionLead: 'reactor formation followed by reprocessing and radiochemical isolation',
        productionRoutes: 'fuel irradiation, dissolution, solvent extraction, redox conditioning, and target purification',
        appliedLead: 'fuel-cycle research, target materials, waste-form studies, and nuclear forensics',
        appliedSystems: 'NpO2, neptunyl solutions, target oxides, and separated actinide process streams',
        significanceNote: 'its importance comes from long-lived waste behavior and the redox-sensitive mobility of neptunium species',
        hazardNote: 'hazards are radiological and contamination-driven, with redox-sensitive solution chemistry complicating containment',
    }),
    makeSeed({
        id: 'plutonium',
        name: 'Plutonium',
        symbol: 'Pu',
        atomicNumber: 94,
        atomicMass: '[244]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f6 7s2',
        oxidationStates: '+3, +4, +5, +6',
        summaryLine: 'Plutonium is a central transuranium element whose complex allotropy, redox flexibility, and isotope-specific behavior dominate nuclear fuel, weapons history, and waste management.',
        importanceLine: 'Its chemistry links actinide covalency, fuel fabrication, separations chemistry, and the long-term stewardship of fissile materials.',
        heroFacts: ['Major fissile element', 'Multiple oxidation states', 'Complex allotropy', 'Central to fuel and weapons history'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Allotropy', 'Existence of multiple structural forms of the same element.'),
            (0, seedFactories_1.term)('Mixed oxide fuel', 'Fuel combining uranium and plutonium oxides.'),
            (0, seedFactories_1.term)('Fissile', 'Able to sustain chain reactions with thermal neutrons.'),
        ],
        classificationLead: 'a multivalent transuranium actinide whose chemistry and metallurgy are both exceptionally complex',
        comparisonNote: 'it combines uranium-like solution chemistry with uniquely difficult metallurgy and isotope-specific strategic significance',
        compoundsLine: 'plutonium oxides, fluorides, nitrates, mixed-oxide fuels, and Pu(III)-Pu(VI) process species',
        physicalLead: 'a dense radioactive metal with multiple allotropes and challenging metallurgy',
        physicalNote: 'phase behavior, self-heating, and surface oxidation make plutonium unlike most engineering metals',
        reactivityLead: 'an actinide with several accessible oxidation states and sensitive redox interconversion in solution and solids',
        occurrenceLead: 'reactor-bred material and legacy fuel-cycle inventories rather than ordinary natural deposits',
        occurrenceNote: 'practical plutonium is artificial and arises through neutron capture and subsequent separations',
        isotopeLead: 'plutonium isotopes such as Pu-239, Pu-240, and Pu-238',
        isotopeDetail: 'different isotopes control whether plutonium is important for power generation, heat sources, safeguards, or weapons',
        isotopeUse: 'mixed-oxide fuel, radioisotope power systems, forensics, and safeguards',
        productionLead: 'reactor production followed by reprocessing, purification, and controlled fabrication',
        productionRoutes: 'neutron capture in uranium, fuel irradiation, dissolution, solvent extraction, and oxide conversion',
        appliedLead: 'nuclear fuel, radioisotope heat sources, safeguards science, and waste stewardship',
        appliedSystems: 'PuO2, MOX fuel, nitrate process streams, metal forms, and Pu-238 heat-source materials',
        significanceNote: 'its chemistry is inseparable from twentieth-century nuclear history and the long-term management of fissile materials',
        hazardNote: 'hazards include alpha contamination, self-heating for some isotopes, criticality concerns, and extremely strict security controls',
    }),
    makeSeed({
        id: 'americium',
        name: 'Americium',
        symbol: 'Am',
        atomicNumber: 95,
        atomicMass: '[243]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f7 7s2',
        oxidationStates: '+3, +4, +5, +6',
        summaryLine: 'Americium is a transuranium actinide best known for Am(III) chemistry, smoke-detector sources, and its role in advanced waste and separations research.',
        importanceLine: 'Its chemistry links practical sealed-source use to complex actinide separation science and long-term waste management.',
        heroFacts: ['Am(III) chemistry is common', 'Used in smoke detectors', 'Transuranium actinide', 'Relevant to waste separations'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Ionization smoke detector', 'A detector that uses americium-241 as a radiation source.'),
            (0, seedFactories_1.term)('Minor actinide', 'An actinide such as americium often discussed separately from uranium and plutonium in fuel cycles.'),
            (0, seedFactories_1.term)('Partitioning', 'Chemical separation of waste components into different streams.'),
        ],
        classificationLead: 'a transuranium actinide whose chemistry is centered on Am3+ with accessible higher oxidation states in strong oxidizing conditions',
        comparisonNote: 'it behaves more like a trivalent actinide in ordinary coordination chemistry than plutonium does',
        compoundsLine: 'americium oxides, halides, nitrates, Am3+ complexes, and sealed alpha-source materials',
        physicalLead: 'a radioactive metallic solid usually managed as oxide or salt rather than as bulk metal',
        physicalNote: 'its practical forms are controlled by isotope heat generation, source design, and waste-processing requirements',
        reactivityLead: 'an actinide dominated by trivalent solution chemistry but capable of higher-valent process states',
        occurrenceLead: 'artificial production in reactors and fuel-cycle residues',
        occurrenceNote: 'americium is not a mined natural resource and is encountered through irradiated fuel and separated actinide streams',
        isotopeLead: 'americium-241, americium-243, and related isotopes',
        isotopeDetail: 'Am-241 is the best-known isotope because it is relatively long lived and useful as a compact alpha source',
        isotopeUse: 'smoke detectors, neutron sources when combined with beryllium, and separations research',
        productionLead: 'reactor formation followed by reprocessing and actinide partitioning',
        productionRoutes: 'fuel irradiation, decay of plutonium isotopes, solvent extraction, and oxide purification',
        appliedLead: 'sealed sources, neutron-source systems, separations research, and waste management',
        appliedSystems: 'AmO2, americium salts, smoke-detector sources, Am-Be neutron sources, and partitioning streams',
        significanceNote: 'its importance comes from being a practical source isotope and a key minor actinide in waste-treatment chemistry',
        hazardNote: 'hazards are radiological and contamination-driven, especially for inhalable oxides and separated salts',
    }),
    makeSeed({
        id: 'curium',
        name: 'Curium',
        symbol: 'Cm',
        atomicNumber: 96,
        atomicMass: '[247]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f7 6d1 7s2',
        oxidationStates: '+3',
        summaryLine: 'Curium is a strongly radioactive actinide whose Cm(III) chemistry and intense alpha emission matter in research, source materials, and actinide science.',
        importanceLine: 'Its chemistry links trivalent actinide coordination to self-heating isotopes, target preparation, and nuclear-materials research.',
        heroFacts: ['Strongly radioactive actinide', 'Cm3+ dominates chemistry', 'Important research target material', 'Notable self-heating'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Self-heating', 'Heat generation caused by radioactive decay in a material.'),
            (0, seedFactories_1.term)('Target material', 'A material used for irradiation to make new isotopes or elements.'),
            (0, seedFactories_1.term)('Alpha source', 'A material that emits alpha particles for research or applied use.'),
        ],
        classificationLead: 'a transuranium actinide whose ordinary chemistry is largely trivalent despite intense radioactivity',
        comparisonNote: 'it resembles the lanthanide-like trivalent actinides more than the highly multivalent early actinides',
        compoundsLine: 'curium oxides, halides, Cm3+ salts, target materials, and source-related compounds',
        physicalLead: 'a dense highly radioactive metal more commonly handled through its oxides and salts than as bare metal',
        physicalNote: 'self-heating and strong alpha emission dominate storage, target fabrication, and containment',
        reactivityLead: 'an actinide with mostly Cm3+ chemistry in oxides, halides, and coordination compounds',
        occurrenceLead: 'artificial production in reactors or specialized actinide-processing streams',
        occurrenceNote: 'curium is absent as a practical natural resource and is accessed only through nuclear production',
        isotopeLead: 'curium isotopes such as Cm-242, Cm-244, and related heavy nuclides',
        isotopeDetail: 'different curium isotopes vary strongly in half-life and heat generation, affecting target and source use',
        isotopeUse: 'neutron-source preparation, heavy-element target production, and nuclear research',
        productionLead: 'multiple neutron-capture and decay steps in reactor fuel followed by separation',
        productionRoutes: 'extended irradiation, reprocessing, actinide partitioning, and oxide purification',
        appliedLead: 'research targets, source materials, and advanced actinide science',
        appliedSystems: 'curium oxides, Cm3+ salts, target pellets, and source-related compounds',
        significanceNote: 'its importance lies in providing intense alpha-emitting materials and precursor targets for heavier elements',
        hazardNote: 'hazards include intense radioactivity, self-heating, and contamination from finely divided curium compounds',
    }),
    makeSeed({
        id: 'berkelium',
        name: 'Berkelium',
        symbol: 'Bk',
        atomicNumber: 97,
        atomicMass: '[247]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f9 7s2',
        oxidationStates: '+3, +4',
        summaryLine: 'Berkelium is a synthetic actinide whose Bk(III) and Bk(IV) chemistry is important mainly for target preparation and research on heavier elements.',
        importanceLine: 'Its chemistry links minor-actinide separations to the atom-at-a-time production of the heaviest nuclei.',
        heroFacts: ['Synthetic actinide', 'Bk3+ dominates with accessible Bk4+', 'Used as target material', 'Important in superheavy-element synthesis'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Target synthesis', 'Use of a prepared isotope target to create heavier elements by irradiation.'),
            (0, seedFactories_1.term)('Actinide separation', 'Chemical isolation of individual heavy elements from a mixed radioactive matrix.'),
            (0, seedFactories_1.term)('Oxidation-state control', 'Use of redox chemistry to separate closely related elements.'),
        ],
        classificationLead: 'a synthetic actinide with mainly Bk3+ chemistry and limited but useful Bk4+ behavior',
        comparisonNote: 'it is chemically significant because Bk4+ can aid separations and target preparation for still heavier elements',
        compoundsLine: 'berkelium oxides, halides, Bk3+ salts, Bk4+ species, and irradiation targets',
        physicalLead: 'a highly radioactive metallic solid known primarily through research-scale oxide or salt materials',
        physicalNote: 'sample sizes are tiny and practical work centers on target fabrication and isotope containment',
        reactivityLead: 'an actinide with mostly trivalent behavior plus selected tetravalent chemistry under controlled conditions',
        occurrenceLead: 'artificial reactor production only',
        occurrenceNote: 'berkelium is encountered solely through irradiation and radiochemical isolation',
        isotopeLead: 'berkelium isotopes such as Bk-247 and Bk-249',
        isotopeDetail: 'Bk-249 is especially important because it serves as a target precursor for heavier-element synthesis',
        isotopeUse: 'superheavy-element targets, actinide research, and radiochemical studies',
        productionLead: 'high-flux irradiation followed by radiochemical separation',
        productionRoutes: 'multiple neutron captures, decay steps, target processing, and ion-exchange purification',
        appliedLead: 'research targets, oxidation-state studies, and superheavy-element production',
        appliedSystems: 'Bk-249 targets, berkelium oxides, berkelium halides, and research salts',
        significanceNote: 'its value is scientific rather than commercial because target-grade berkelium opens access to heavier nuclei',
        hazardNote: 'hazards are radiological and operational, with tiny quantities requiring precise contamination control',
    }),
    makeSeed({
        id: 'californium',
        name: 'Californium',
        symbol: 'Cf',
        atomicNumber: 98,
        atomicMass: '[251]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f10 7s2',
        oxidationStates: '+2, +3, +4',
        summaryLine: 'Californium is a synthetic actinide best known for Cf-252, an intense neutron emitter used in specialized industrial and scientific applications.',
        importanceLine: 'Its chemistry links trivalent actinide behavior to neutron sources, target preparation, and high-value isotope production.',
        heroFacts: ['Synthetic actinide', 'Cf-252 is a strong neutron source', 'Mostly Cf3+ chemistry', 'Used in specialized instruments'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Neutron source', 'A material that emits neutrons for analysis, startup, or research.'),
            (0, seedFactories_1.term)('Spontaneous fission', 'Nuclear decay in which a heavy nucleus splits without external triggering.'),
            (0, seedFactories_1.term)('Source encapsulation', 'Containment of a radioactive source inside engineered packaging.'),
        ],
        classificationLead: 'a synthetic actinide whose chemistry is mostly trivalent but whose isotopes make it disproportionately important',
        comparisonNote: 'its scientific and industrial importance is driven more by neutron emission than by unusual bulk chemistry',
        compoundsLine: 'californium oxides, halides, Cf3+ salts, and sealed neutron-source materials',
        physicalLead: 'a highly radioactive metal encountered almost entirely as tiny sealed or processed source materials',
        physicalNote: 'physical handling is inseparable from source design, heat generation, and shielding',
        reactivityLead: 'an actinide dominated by Cf3+ compounds with limited higher or lower oxidation-state chemistry',
        occurrenceLead: 'artificial production in intense neutron-flux environments',
        occurrenceNote: 'californium is produced only in reactors or specialized irradiation campaigns',
        isotopeLead: 'californium isotopes such as Cf-249, Cf-251, and especially Cf-252',
        isotopeDetail: 'Cf-252 is notable because spontaneous fission makes it one of the most useful compact neutron sources',
        isotopeUse: 'neutron radiography, reactor startup, elemental analysis, and research sources',
        productionLead: 'extended neutron irradiation followed by complex actinide separations',
        productionRoutes: 'high-flux reactor campaigns, decay management, solvent extraction, and source fabrication',
        appliedLead: 'sealed neutron sources, target materials, and nuclear research',
        appliedSystems: 'Cf-252 sources, californium oxides, research salts, and analytical neutron-emission systems',
        significanceNote: 'its importance comes from enabling compact neutron-source applications that few other isotopes can match',
        hazardNote: 'hazards are severe because intense radiation fields, source handling, and contamination control all matter simultaneously',
    }),
    makeSeed({
        id: 'einsteinium',
        name: 'Einsteinium',
        symbol: 'Es',
        atomicNumber: 99,
        atomicMass: '[252]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f11 7s2',
        oxidationStates: '+2, +3',
        summaryLine: 'Einsteinium is a highly radioactive synthetic actinide used mainly in fundamental chemistry and as a precursor for making heavier elements.',
        importanceLine: 'Its chemistry links late-actinide coordination to target scarcity, self-damage, and the pursuit of the periodic table’s heaviest members.',
        heroFacts: ['Synthetic late actinide', 'Es3+ dominates chemistry', 'Used in heavy-element research', 'Self-damage is significant'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Self-damage', 'Radiation-induced structural damage within a radioactive material.'),
            (0, seedFactories_1.term)('Late actinide', 'One of the heavier actinides with more contracted 5f chemistry.'),
            (0, seedFactories_1.term)('Precursor target', 'A prepared isotope used to make heavier species after irradiation.'),
        ],
        classificationLead: 'a late actinide whose chemistry is mostly trivalent and studied only in extremely small radioactive samples',
        comparisonNote: 'its value lies in how late-actinide behavior changes under intense self-irradiation and target scarcity',
        compoundsLine: 'einsteinium oxides, halides, Es3+ salts, and heavy-element precursor targets',
        physicalLead: 'a highly radioactive solid that damages itself over time through intense decay',
        physicalNote: 'sample size, heat generation, and radiation damage dominate all physical considerations',
        reactivityLead: 'a late actinide with primarily Es3+ coordination chemistry and limited lower-valent behavior',
        occurrenceLead: 'artificial production in high-flux reactors or specialized nuclear events',
        occurrenceNote: 'einsteinium is not naturally available in practical amounts and exists only through nuclear production',
        isotopeLead: 'einsteinium isotopes such as Es-253 and related short-lived nuclides',
        isotopeDetail: 'all isotopes are radioactive and available only in tiny quantities',
        isotopeUse: 'fundamental actinide chemistry, target preparation, and nuclear-structure studies',
        productionLead: 'multiple neutron-capture sequences followed by difficult radiochemical purification',
        productionRoutes: 'high-flux irradiation, decay management, ion exchange, and microgram-scale isolation',
        appliedLead: 'heavy-element synthesis research and late-actinide chemistry',
        appliedSystems: 'einsteinium oxides, research salts, microgram targets, and spectroscopy samples',
        significanceNote: 'its significance is entirely scientific because its scarcity makes even microgram quantities valuable',
        hazardNote: 'hazards are radiological and compounded by self-heating, self-damage, and extremely limited sample availability',
    }),
    makeSeed({
        id: 'fermium',
        name: 'Fermium',
        symbol: 'Fm',
        atomicNumber: 100,
        atomicMass: '[257]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f12 7s2',
        oxidationStates: '+2, +3',
        summaryLine: 'Fermium is a very heavy synthetic actinide whose chemistry is known only through atom-scale or microgram-scale studies.',
        importanceLine: 'Its chemistry helps define the late-actinide transition toward more compact 5f behavior under extreme experimental constraints.',
        heroFacts: ['Very heavy actinide', 'Known only in tiny amounts', 'Mostly Fm3+ chemistry', 'Important in late-actinide research'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Atom-at-a-time chemistry', 'Chemical study performed on extremely small numbers of atoms.'),
            (0, seedFactories_1.term)('Late-actinide contraction', 'Progressive change in size and bonding across the heaviest actinides.'),
            (0, seedFactories_1.term)('Microgram-scale research', 'Research using millionths of a gram because larger quantities are unavailable.'),
        ],
        classificationLead: 'a late synthetic actinide whose known chemistry is restricted to very small samples and mainly trivalent species',
        comparisonNote: 'its chemistry is valuable because it shows how actinides approach more lanthanide-like trivalence at the end of the series',
        compoundsLine: 'fermium oxides, halides, Fm3+ salts, and tracer-scale research compounds',
        physicalLead: 'an intensely radioactive solid never handled as an ordinary bulk material',
        physicalNote: 'its physical profile is inferred mostly through microgram-scale research and nuclear measurements',
        reactivityLead: 'a late actinide dominated by Fm3+ chemistry with limited access to divalent states',
        occurrenceLead: 'artificial nuclear production only',
        occurrenceNote: 'fermium is encountered solely in specialized production and research campaigns',
        isotopeLead: 'short-lived fermium isotopes such as Fm-257',
        isotopeDetail: 'all isotopes are radioactive and available in tiny quantities',
        isotopeUse: 'late-actinide chemistry, nuclear-structure work, and heavy-element target studies',
        productionLead: 'high-neutron-flux production followed by ultratrace chemical separation',
        productionRoutes: 'multiple neutron captures, decay chains, and microchemistry-scale purification',
        appliedLead: 'fundamental research rather than commercial technology',
        appliedSystems: 'tracer-scale salts, oxide residues, and nuclear research targets',
        significanceNote: 'its main value is in testing theories of heavy-element bonding and nuclear stability',
        hazardNote: 'hazards are radiological, but the dominant operational challenge is working with vanishingly small amounts',
    }),
    makeSeed({
        id: 'mendelevium',
        name: 'Mendelevium',
        symbol: 'Md',
        atomicNumber: 101,
        atomicMass: '[258]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f13 7s2',
        oxidationStates: '+2, +3',
        summaryLine: 'Mendelevium is a synthetic late actinide whose chemistry is known from atom-scale experiments and notable Md(II)/Md(III) behavior.',
        importanceLine: 'Its chemistry links late-actinide redox trends to microchemistry methods and fundamental electronic-structure tests.',
        heroFacts: ['Synthetic late actinide', 'Md2+ and Md3+ are relevant', 'Atom-scale chemistry', 'Fundamental research element'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Redox pair', 'Two oxidation states linked by electron transfer.'),
            (0, seedFactories_1.term)('Microchemistry', 'Chemical work with extremely small sample sizes.'),
            (0, seedFactories_1.term)('Carrier-free', 'A radioactive sample without large amounts of inactive carrier material.'),
        ],
        classificationLead: 'a late synthetic actinide whose chemistry is notable for the balance between Md3+ and Md2+ states',
        comparisonNote: 'its accessible divalent chemistry helps mark the changing electronic structure near the end of the actinide series',
        compoundsLine: 'mendelevium oxides, halides, Md3+ salts, Md2+ species, and tracer-scale compounds',
        physicalLead: 'a highly radioactive solid known only through ultratrace chemical experiments',
        physicalNote: 'sample scarcity means physical behavior is inferred indirectly from radiochemical studies',
        reactivityLead: 'a late actinide with redox chemistry that can access both trivalent and divalent states under suitable conditions',
        occurrenceLead: 'artificial production in particle accelerators or specialized irradiation campaigns',
        occurrenceNote: 'mendelevium does not occur naturally and is created only for research',
        isotopeLead: 'short-lived mendelevium isotopes such as Md-258 and related nuclides',
        isotopeDetail: 'all known isotopes are radioactive and available only in extremely small amounts',
        isotopeUse: 'redox studies, nuclear-structure research, and late-actinide trend analysis',
        productionLead: 'target irradiation followed by carrier-free radiochemical separation',
        productionRoutes: 'particle bombardment, rapid separations, and ultratrace analytical workflows',
        appliedLead: 'fundamental redox and structural research rather than commercial use',
        appliedSystems: 'carrier-free ions, tracer salts, and atom-scale reaction systems',
        significanceNote: 'its importance comes from revealing how late-actinide electronic structure changes near the end of the series',
        hazardNote: 'hazards are radiological, while sample scarcity and short half-lives dominate the experimental challenge',
    }),
    makeSeed({
        id: 'nobelium',
        name: 'Nobelium',
        symbol: 'No',
        atomicNumber: 102,
        atomicMass: '[259]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f14 7s2',
        oxidationStates: '+2, +3',
        summaryLine: 'Nobelium is a late actinide notable for comparatively stable No(II) chemistry, which distinguishes it from many earlier actinides.',
        importanceLine: 'Its chemistry links the filled 5f shell to unusual divalent behavior and the closing stages of the actinide series.',
        heroFacts: ['Filled 5f shell', 'No2+ is relatively stable', 'Late actinide', 'Studied atom by atom'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Filled shell', 'An electron shell or subshell containing its full complement of electrons.'),
            (0, seedFactories_1.term)('Divalent state', 'An oxidation state of +2.'),
            (0, seedFactories_1.term)('Series closure', 'The chemical transition associated with the end of an element series.'),
        ],
        classificationLead: 'a late actinide distinguished by unusually stable divalent chemistry for so heavy an element',
        comparisonNote: 'its behavior differs from earlier actinides because No2+ becomes surprisingly favorable alongside No3+',
        compoundsLine: 'nobelium halides, No2+ and No3+ salts, and tracer-scale late-actinide compounds',
        physicalLead: 'a highly radioactive solid examined only through ultratrace experiments',
        physicalNote: 'its physical identity is secondary to the redox evidence gathered from atom-scale chemistry',
        reactivityLead: 'a late actinide whose chemistry highlights the balance between divalent and trivalent states',
        occurrenceLead: 'artificial nuclear production only',
        occurrenceNote: 'nobelium exists exclusively as a laboratory-created radioactive element',
        isotopeLead: 'short-lived nobelium isotopes such as No-255 and No-259',
        isotopeDetail: 'all nobelium isotopes are radioactive and available only in minuscule amounts',
        isotopeUse: 'late-actinide redox studies and nuclear-structure research',
        productionLead: 'particle-induced production followed by atom-scale chemical separation',
        productionRoutes: 'accelerator synthesis, rapid transport, and microchemical identification',
        appliedLead: 'fundamental late-actinide chemistry and nuclear research',
        appliedSystems: 'tracer ions, late-actinide salts, and atom-scale experimental systems',
        significanceNote: 'its importance lies in showing how actinide chemistry changes as the 5f shell fills',
        hazardNote: 'hazards are radiological, but the main practical limit is the tiny amount and short lifetime of nobelium samples',
    }),
    makeSeed({
        id: 'lawrencium',
        name: 'Lawrencium',
        symbol: 'Lr',
        atomicNumber: 103,
        atomicMass: '[266]',
        group: 'Actinide series',
        period: '7',
        block: 'f',
        category: 'Actinide',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f14 7s2 7p1',
        oxidationStates: '+3',
        summaryLine: 'Lawrencium is the last actinide and a synthetic heavy element whose chemistry closes the 5f series while raising questions about the f-block to d-block transition.',
        importanceLine: 'Its chemistry links the end of the actinides to modern heavy-element electronic-structure studies and atom-scale separations.',
        heroFacts: ['Last actinide', 'Synthetic element', 'Lr3+ dominates chemistry', 'Important for series-boundary studies'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Series boundary', 'A point where the chemistry of one element family shifts into another.'),
            (0, seedFactories_1.term)('Electronic-structure study', 'Investigation of how electrons are arranged and how that affects properties.'),
            (0, seedFactories_1.term)('Heavy-element chemistry', 'Chemistry involving the heaviest radioactive elements, often at ultratrace scale.'),
        ],
        classificationLead: 'the final actinide, usually treated as a trivalent heavy element marking the end of the 5f series',
        comparisonNote: 'it is scientifically important because it sits at the transition between classic actinide behavior and the next region of the table',
        compoundsLine: 'lawrencium halides, Lr3+ salts, and atom-scale heavy-element research compounds',
        physicalLead: 'a short-lived highly radioactive solid known only through atom-at-a-time studies',
        physicalNote: 'its physical properties are inferred mainly from electronic-structure calculations and ultratrace experiments',
        reactivityLead: 'a heavy-element chemistry dominated by the Lr3+ state in rapid separation experiments',
        occurrenceLead: 'artificial synthesis only',
        occurrenceNote: 'lawrencium is created in accelerators and never encountered naturally',
        isotopeLead: 'lawrencium isotopes such as Lr-256 and Lr-266',
        isotopeDetail: 'all isotopes are radioactive, and the element is studied only through short-lived nuclides',
        isotopeUse: 'series-boundary chemistry, nuclear-structure work, and atom-scale separations',
        productionLead: 'heavy-ion synthesis followed by rapid chemical identification',
        productionRoutes: 'accelerator production, recoil transport, and ultrafast microchemical separation',
        appliedLead: 'fundamental heavy-element research rather than practical technology',
        appliedSystems: 'atom-scale ions, tracer salts, and sequence-defining heavy-element experiments',
        significanceNote: 'its importance is conceptual because it closes the actinide series and tests modern theories of heavy-element structure',
        hazardNote: 'hazards are radiological, but the overriding operational issue is the short-lived atom-scale nature of every experiment',
    }),
];
