"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.postZincElementSeeds = void 0;
const seedFactories_1 = require("@/content/subjects/chemistry/seedFactories");
function facts(a, b, c, d, e) {
    return [a, b, c, d, e];
}
function makeSeed(config) {
    return {
        ...config,
        sections: {
            classification: (0, seedFactories_1.classificationSection)(config.name, config.sections.classification),
            electronic: (0, seedFactories_1.electronicSection)(config.name, config.sections.electronic),
            physical: (0, seedFactories_1.physicalSection)(config.name, config.sections.physical),
            reactivity: (0, seedFactories_1.reactivitySection)(config.name, config.sections.reactivity),
            occurrence: (0, seedFactories_1.occurrenceSection)(config.name, config.sections.occurrence),
            isotopes: (0, seedFactories_1.isotopeSection)(config.name, config.sections.isotopes),
            production: (0, seedFactories_1.productionSection)(config.name, config.sections.production),
            applied: (0, seedFactories_1.appliedSection)(config.name, config.sections.applied),
        },
    };
}
exports.postZincElementSeeds = [
    makeSeed({
        id: 'gallium',
        name: 'Gallium',
        symbol: 'Ga',
        atomicNumber: 31,
        atomicMass: '69.723',
        group: '13',
        period: '4',
        block: 'p',
        category: 'Post-transition metal',
        roomState: 'Solid',
        electronConfiguration: '[Ar]3d10 4s2 4p1',
        oxidationStates: '+1, +3',
        summaryLine: 'Gallium is a low-melting post-transition metal whose trivalent chemistry and semiconductor compounds make it important in optoelectronics, power devices, and specialty alloys.',
        importanceLine: 'Its chemistry links heavy group-13 behavior to compound semiconductors, liquid-metal handling, and byproduct technology-metal recovery.',
        heroFacts: ['Melts near room temperature', 'Ga3+ chemistry dominates', 'Key semiconductor metal', 'Recovered mainly as a byproduct'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Gallium arsenide', 'A compound semiconductor, GaAs, important in fast electronics and optoelectronics.'),
            (0, seedFactories_1.term)('Gallium nitride', 'A wide-band-gap semiconductor used in LEDs and power electronics.'),
            (0, seedFactories_1.term)('Eutectic alloy', 'A low-melting alloy composition that solidifies at a single temperature.'),
        ],
        sections: {
            classification: facts('a group-13 post-transition metal with dominant trivalent chemistry', 'group 13, period 4, p-block', '[Ar]3d10 4s2 4p1', 'it forms Ga3+ compounds and important polarized covalent semiconductors', 'its chemistry is more metallic than boron and more low-melting than aluminum'),
            electronic: facts('an [Ar]3d10 4s2 4p1 valence arrangement', 'it forms mostly Ga3+ compounds and polarized covalent bonds in semiconductors and halides', '+1 and +3, with +3 dominant', 'Ga2O3, GaAs, GaN, and gallium halides', 'the filled 3d shell and heavy p-block behavior support both metallic bonding and semiconductor chemistry'),
            physical: facts('a soft silvery metal that melts only slightly above room temperature', 'it has an unusually low melting point for a true metal and readily wets some surfaces', 'relatively weak metallic bonding helps explain softness and easy melting', 'high-purity gallium metal, low-melting alloys, and wafer-scale semiconductor compounds', 'liquid gallium can attack or embrittle some materials, so container choice matters'),
            reactivity: facts('a moderately reactive metal that oxidizes in air and dissolves under acidic or basic conditions', 'it forms oxides, halides, and semiconductor compounds rather than the violently basic chemistry of alkali metals', 'stabilization of Ga3+ and strong oxide or semiconductor bonding drives the chemistry', 'oxides, nitrides, arsenides, halides, and organogallium precursors', 'bulk metal is manageable, but high-purity process chemicals and some compounds require tighter control'),
            occurrence: facts('trace substitution in bauxite, zinc ores, coal, and industrial residues', 'it is economically important mainly as a dispersed byproduct element', 'bauxite liquors, zinc-processing streams, and combustion-related residues are the main practical reservoirs', 'gallium distribution is controlled more by separation technology than by rich primary ores', 'native gallium is absent because oxidized mineral-bound forms are more stable'),
            isotopes: facts('gallium-69 and gallium-71', 'both principal naturally occurring isotopes are stable', 'isotopic composition influences average mass and can support analytical or materials studies', 'stable-isotope measurements are useful in high-precision chemical analysis', 'routine gallium chemistry is not strongly shaped by radiological isotope issues'),
            production: facts('recovery from Bayer-process liquors and zinc-processing streams', 'industrial gallium supply depends on selective separation from much larger aluminum and zinc process flows', 'solvent extraction, ion exchange, cementation, and electrolytic finishing are common refining routes', 'high purity is essential for electronic-grade gallium and requires removal of many trace metals', 'supply depends strongly on byproduct economics and electronics demand'),
            applied: facts('compound semiconductors, LEDs, photovoltaics, radio-frequency devices, and low-melting alloys', 'gallium metal, gallium oxide, GaAs, GaN, and eutectic alloys', 'gallium is important because it enables optoelectronics and advanced power electronics', 'modern demand rose with compound-semiconductor technology rather than bulk metallurgy', 'hazards are modest for the metal but more significant for reactive precursors and high-purity manufacturing streams'),
        },
    }),
    makeSeed({
        id: 'germanium',
        name: 'Germanium',
        symbol: 'Ge',
        atomicNumber: 32,
        atomicMass: '72.630',
        group: '14',
        period: '4',
        block: 'p',
        category: 'Metalloid',
        roomState: 'Solid',
        electronConfiguration: '[Ar]3d10 4s2 4p2',
        oxidationStates: '-4, +2, +4',
        summaryLine: 'Germanium is a metalloid whose semiconductor behavior and infrared-optical uses make it important in electronics, optics, and specialty materials.',
        importanceLine: 'Its chemistry connects group-14 covalency to semiconductor physics, oxide materials, and the history of early transistor technology.',
        heroFacts: ['Classic semiconductor metalloid', 'Important infrared material', 'Ge4+ chemistry is common', 'Recovered from zinc and coal streams'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Germania', 'Germanium dioxide, GeO2, the main oxide of germanium.'),
            (0, seedFactories_1.term)('Semiconductor doping', 'Addition of impurities to control electrical properties in a semiconductor crystal.'),
            (0, seedFactories_1.term)('Infrared optics', 'Optical systems designed to transmit or detect infrared radiation.'),
        ],
        sections: {
            classification: facts('a group-14 metalloid with strongly covalent and semiconducting behavior', 'group 14, period 4, p-block', '[Ar]3d10 4s2 4p2', 'it forms covalent networks and oxidized compounds in which Ge4+ is especially important', 'its chemistry is more metallic than silicon yet less metallic than tin'),
            electronic: facts('an [Ar]3d10 4s2 4p2 valence arrangement', 'it forms predominantly covalent bonds in elemental, oxide, halide, and semiconductor materials', '-4, +2, and +4, with +4 strongly favored in many compounds', 'GeO2, GeCl4, covalent Ge-Ge frameworks, and doped semiconductor lattices', 'filled 3d and valence p chemistry support semiconducting behavior and tetravalent bonding'),
            physical: facts('a hard gray metalloid with semiconducting electrical properties', 'its conductivity is intermediate between metals and insulators and is highly sensitive to impurity level and temperature', 'a diamond-like covalent network explains brittleness and semiconducting behavior', 'single-crystal germanium, germanium dioxide glass additives, and infrared optical components', 'brittle crystal handling and contamination control are important in device fabrication'),
            reactivity: facts('a moderately reactive metalloid whose chemistry is governed largely by oxidation to Ge4+ compounds', 'it reacts with halogens and oxidizing conditions to form stable covalent oxides and halides', 'strong Ge-O and Ge-halogen bonding drive much of the accessible chemistry', 'oxides, chlorides, organogermanium compounds, and semiconductor-processing intermediates', 'bulk germanium is manageable, but dusts and reactive halide intermediates require routine precautions'),
            occurrence: facts('trace substitution in zinc ores, sulfides, coal, and some copper-related residues', 'it is relatively scarce in concentrated ores and is commonly obtained as a dispersed byproduct', 'zinc-processing streams, coal ash, and complex sulfide residues are the major practical reservoirs', 'economic occurrence depends on recovery from low-concentration sources rather than rich germanium ores', 'free germanium does not occur naturally because oxide and sulfide forms are more stable'),
            isotopes: facts('germanium-70, 72, 73, 74, and 76', 'multiple naturally occurring isotopes are stable, with germanium-76 especially important in rare-event physics', 'isotopic composition matters in precision metrology and detector science', 'enriched germanium-76 is important in double-beta-decay experiments', 'ordinary germanium chemistry is not radiologically dominated'),
            production: facts('recovery from zinc smelting streams, coal-related residues, and chloride-processing routes', 'production is shaped mainly by selective separation from low-level mixed feedstocks rather than simple ore reduction', 'chloride chemistry and subsequent hydrolysis or reduction are common refining strategies', 'very high purity is required for electronics and detector uses', 'supply depends heavily on byproduct recovery and specialized optical or semiconductor demand'),
            applied: facts('infrared optics, fiber-optic materials, semiconductor devices, detectors, and specialty catalysts', 'germanium metal, germanium dioxide, germanium tetrachloride, and doped semiconductor materials', 'germanium is important because it combines semiconducting behavior with infrared transparency', 'it played a historic role in early transistor technology before silicon became dominant', 'hazards are usually moderate and tied to dusts, chlorides, and high-purity process chemicals'),
        },
    }),
    makeSeed({
        id: 'arsenic',
        name: 'Arsenic',
        symbol: 'As',
        atomicNumber: 33,
        atomicMass: '74.921595',
        group: '15',
        period: '4',
        block: 'p',
        category: 'Metalloid',
        roomState: 'Solid',
        electronConfiguration: '[Ar]3d10 4s2 4p3',
        oxidationStates: '-3, +3, +5',
        summaryLine: 'Arsenic is a toxic group-15 metalloid whose oxidation-state chemistry, mineral occurrence, and semiconductor compounds make it important in environmental science and materials chemistry.',
        importanceLine: 'Its chemistry links pnictogen bonding to water-quality science, toxicology, sulfide mineralogy, and compound semiconductors such as gallium arsenide.',
        heroFacts: ['Toxic metalloid', 'As3+ and As5+ are environmentally important', 'Common in sulfide minerals', 'Used in selected semiconductors'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Arsenopyrite', 'An iron arsenic sulfide mineral and a major arsenic-bearing ore phase.'),
            (0, seedFactories_1.term)('Arsenate', 'An As(V) oxyanion family often behaving in some ways like phosphate.'),
            (0, seedFactories_1.term)('Arsenite', 'An As(III) oxyanion family often more mobile and more toxic than arsenate.'),
        ],
        sections: {
            classification: facts('a group-15 metalloid with strong covalent bonding and major environmental importance', 'group 15, period 4, p-block', '[Ar]3d10 4s2 4p3', 'it forms covalent compounds and environmentally significant oxyanions in both +3 and +5 states', 'its chemistry is more metallic than phosphorus yet more nonmetal-like than antimony in many oxides'),
            electronic: facts('an [Ar]3d10 4s2 4p3 valence arrangement', 'it forms covalent bonds, network solids, and multiple oxidation states tied to pnictogen lone-pair chemistry', '-3, +3, and +5', 'arsenides, As2O3, arsenate species, and compound semiconductors such as GaAs', 'lone-pair effects and accessible oxidation-state changes make arsenic chemically versatile but environmentally consequential'),
            physical: facts('a brittle gray metalloid with several allotropes', 'it shows semimetallic conductivity rather than the ductile behavior of true metals', 'covalent bonding and allotropy explain brittleness and semimetallic properties', 'gray arsenic, arsenic trioxide, and arsenide-containing semiconductor materials', 'arsenic dusts and compounds require careful containment because toxicity matters even when reactivity is moderate'),
            reactivity: facts('a moderately reactive metalloid dominated by oxidation, sulfide formation, and oxyanion speciation', 'it forms oxides, sulfides, halides, and environmentally mobile arsenite or arsenate species', 'stabilization of covalent oxides and sulfur-containing minerals drives much of its chemistry', 'arsenides, arsenic oxides, sulfides, oxyanions, and selected semiconductor intermediates', 'toxicity, dust exposure, and water contamination are the major practical hazards'),
            occurrence: facts('arsenopyrite, realgar, orpiment, sulfide ores, and contaminated groundwaters or sediments', 'it is typically dispersed in sulfide-mineral systems rather than mined chiefly as a stand-alone bulk commodity', 'ore-associated sulfides, smelter residues, and geochemically mobilized waters are major reservoirs', 'redox state and sorption strongly control how arsenic moves through natural waters and soils', 'native elemental arsenic is uncommon because sulfide and oxide-associated forms are usually more stable'),
            isotopes: facts('stable arsenic-75 together with radioactive arsenic isotopes used in tracing and medicine', 'arsenic-75 is the only stable isotope', 'radioisotopes support tracer work and specialized nuclear-medical studies', 'radioarsenic nuclides are used in selected labeling or analytical contexts', 'routine arsenic chemistry is dominated by toxicology and environmental control rather than isotope complexity'),
            production: facts('recovery during roasting and smelting of arsenic-bearing sulfide ores and concentrates', 'arsenic is commonly managed as a byproduct or contaminant stream rather than as a large standalone metal market', 'oxidative roasting, capture as arsenic trioxide, and stabilization in controlled waste or product streams are common', 'safe production requires control of volatile oxides, sulfur-bearing gases, and toxic dusts', 'economics are strongly shaped by environmental regulation and the need to stabilize arsenic safely'),
            applied: facts('compound semiconductors, specialty alloys, glass treatment, and selected chemical intermediates', 'gallium arsenide, arsenic oxides, arsenides, and trace alloy additions', 'arsenic is scientifically important because its speciation controls toxicity and because GaAs is technologically valuable', 'arsenic compounds were historically used far more broadly in pigments, medicines, and pesticides before many restrictions', 'major hazards center on chronic toxicity, carcinogenicity, contaminated dusts, and water-quality impacts'),
        },
    }),
    makeSeed({
        id: 'selenium',
        name: 'Selenium',
        symbol: 'Se',
        atomicNumber: 34,
        atomicMass: '78.971',
        group: '16',
        period: '4',
        block: 'p',
        category: 'Nonmetal',
        roomState: 'Solid',
        electronConfiguration: '[Ar]3d10 4s2 4p4',
        oxidationStates: '-2, +4, +6',
        summaryLine: 'Selenium is a chalcogen nonmetal known for allotropy, photoconductive behavior, trace nutritional importance, and toxicity at elevated exposure.',
        importanceLine: 'Its chemistry connects sulfur-family trends to redox-active oxyanions, glass and electronics technology, and trace biological chemistry.',
        heroFacts: ['Chalcogen with several allotropes', 'Photoconductive element', 'Trace nutrient in biology', 'Recovered mainly as a copper-refining byproduct'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Selenide', 'A compound containing selenium in the formal -2 oxidation state.'),
            (0, seedFactories_1.term)('Selenate', 'A selenium(VI) oxyanion family chemically analogous in some ways to sulfate.'),
            (0, seedFactories_1.term)('Photoconductivity', 'A change in electrical conductivity triggered by incident light.'),
        ],
        sections: {
            classification: facts('a group-16 nonmetal whose chemistry combines chalcogen redox behavior with marked allotropy and semiconducting tendencies', 'group 16, period 4, p-block', '[Ar]3d10 4s2 4p4', 'it forms covalent compounds, selenides, and oxidized oxyanion species across several common states', 'its chemistry is more metallic and more photoconductive than sulfur but less metallic than tellurium'),
            electronic: facts('an [Ar]3d10 4s2 4p4 valence arrangement', 'it forms two-electron bonds, chain or ring allotropes, and oxidized oxyanions characteristic of chalcogens', '-2, +4, and +6', 'selenides, SeO2, selenite and selenate species, and semiconductor-related selenium compounds', 'lone-pair effects and variable redox behavior make selenium useful in both inorganic and biological systems'),
            physical: facts('a brittle nonmetallic solid existing in several allotropes', 'it can show photoconductivity and semiconducting behavior unusual for a simple nonmetal', 'catenated covalent structures explain allotropy, brittleness, and electronic behavior', 'gray selenium, red selenium allotropes, and selenium-containing glass or electronic materials', 'powders and process streams require control because selenium compounds can be toxic and odorous'),
            reactivity: facts('a moderately reactive nonmetal spanning reduced selenides to strongly oxidized oxyanions', 'it reacts with metals, halogens, and oxidants to form selenides, halides, oxides, and oxyanion species', 'redox flexibility and stable Se-O bonding drive much of the chemistry', 'selenides, selenium dioxide, selenite and selenate salts, and organoselenium compounds', 'many selenium compounds demand exposure control because the difference between nutrient and toxic dose can be small'),
            occurrence: facts('trace substitution in sulfide ores, copper anode slimes, soils, waters, and biological materials', 'it is relatively scarce in concentrated ores and obtained mainly as a byproduct of sulfide metallurgy', 'copper-refining residues and selenium-bearing sulfide minerals are major practical reservoirs', 'selenium cycles through soils and food webs because trace biological uptake is important', 'free elemental selenium is uncommon because mineral-bound and oxidized forms are generally favored'),
            isotopes: facts('several stable isotopes including selenium-74, 76, 77, 78, 80, and 82', 'multiple naturally occurring isotopes are stable or extremely long lived', 'isotopic composition can record environmental cycling, ore formation, and biological processing', 'stable-isotope work is useful in geochemistry, environmental science, and biochemistry', 'routine selenium chemistry is shaped more by speciation and toxicology than by radiological isotope issues'),
            production: facts('recovery from copper-refining anode slimes and related sulfide-metallurgy residues', 'industrial selenium supply depends on selective byproduct recovery rather than on large primary selenium mines', 'oxidation, reduction, and purification steps convert mixed slimes into elemental selenium or selenium chemicals', 'purity control is important for glass, electronics, and catalyst applications', 'supply is coupled tightly to copper refining and other sulfide-metallurgy industries'),
            applied: facts('glass decolorizing or coloring, photoconductive devices, metallurgy, catalysts, and trace nutritional chemistry', 'elemental selenium, selenium dioxide, metal selenides, and selected organoselenium compounds', 'selenium is important because it combines redox chemistry with photoconductivity and biological trace function', 'selenium became industrially important in glassmaking, rectifiers, and photocopy-era electronics before many roles shifted', 'hazards center on toxic exposure, odorous compounds, and the need to manage selenium within a narrow beneficial-versus-harmful range'),
        },
    }),
    makeSeed({
        id: 'bromine',
        name: 'Bromine',
        symbol: 'Br',
        atomicNumber: 35,
        atomicMass: '79.904',
        group: '17',
        period: '4',
        block: 'p',
        category: 'Halogen',
        roomState: 'Liquid',
        electronConfiguration: '[Ar]3d10 4s2 4p5',
        oxidationStates: '-1, +1, +3, +5',
        summaryLine: 'Bromine is a volatile halogen notable as the only common liquid nonmetal, with rich redox chemistry spanning bromide salts, oxidants, and organobromine compounds.',
        importanceLine: 'Its chemistry links halogen trends to brine extraction, brominating agents, flame-retardant chemistry, and atmospheric processes.',
        heroFacts: ['Only common liquid nonmetal', 'Recovered from brines', 'Forms bromide and oxidized bromine species', 'Important in organic bromination'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Bromide', 'A compound or ion containing bromine in the formal -1 oxidation state.'),
            (0, seedFactories_1.term)('Hypobromite', 'An oxidized bromine species in low positive oxidation state.'),
            (0, seedFactories_1.term)('Bromination', 'Introduction of bromine into an inorganic or organic substrate.'),
        ],
        sections: {
            classification: facts('a period-4 halogen nonmetal with strongly oxidizing elemental chemistry', 'group 17, period 4, p-block', '[Ar]3d10 4s2 4p5', 'it readily gains one electron to form bromide but also forms oxidized oxybromine species', 'its chemistry is less aggressive than chlorine yet more forceful and less metallic than iodine'),
            electronic: facts('an [Ar]3d10 4s2 4p5 valence arrangement', 'it forms one strongly polarized bond in many compounds and stabilizes the bromide ion readily', '-1, +1, +3, and +5 in common chemistry', 'Br2, bromide salts, bromine oxides or oxyanions, and organobromine compounds', 'high electron affinity and accessible oxidized states give bromine both halide and oxidizing-agent chemistry'),
            physical: facts('a red-brown volatile liquid at room temperature', 'it is uniquely liquid among the common nonmetallic elements in introductory chemistry', 'molecular Br2 with relatively strong intermolecular forces for a halogen explains the liquid state', 'sealed bromine ampoules, bromine-containing brines, and bromide salts', 'vapors are corrosive and toxic, so containment and ventilation are essential'),
            reactivity: facts('a reactive halogen oxidant that also serves as a brominating reagent in inorganic and organic chemistry', 'it reacts with metals, alkenes, reducing agents, and many organic substrates while forming bromide or brominated products', 'formation of stable bromide and polarized Br-X bonds drives the chemistry', 'bromides, bromates, hypobromite systems, and organobromine reagents or intermediates', 'liquid bromine and its vapors are highly irritating and corrosive and require careful handling'),
            occurrence: facts('dissolved bromide in seawater, underground brines, and evaporite-related waters', 'it is much less abundant than chloride but sufficiently concentrated in some brines for economic recovery', 'marine and subsurface brines are the major practical reservoirs', 'bromine cycling is important in marine chemistry and some atmospheric processes', 'free bromine is absent naturally because bromide is the stable reduced form in most environments'),
            isotopes: facts('bromine-79 and bromine-81', 'both principal naturally occurring isotopes are stable and occur in nearly equal abundance', 'their near-equal abundance gives bromine distinctive isotopic patterns in mass spectrometry', 'stable-isotope signatures and isotopic patterns are useful in analytical and environmental chemistry', 'bromine handling is governed far more by corrosive oxidizing chemistry than by isotope concerns'),
            production: facts('oxidative release of bromine from bromide-rich brines followed by stripping and purification', 'industrial production depends on brines because bromide is too dilute in ordinary waters for economical extraction', 'air or chlorine oxidation of bromide-bearing brines is a common route to elemental bromine', 'drying, distillation, and materials compatibility are crucial because bromine is volatile and corrosive', 'supply depends on brine composition, co-produced salts, and demand for bromine chemicals'),
            applied: facts('organic synthesis, flame-retardant chemistry, water treatment, dense fluids, and pharmaceutical or photographic intermediates', 'bromide salts, bromine itself, bromates, organobromine compounds, and brominated specialty fluids', 'bromine is important because its reactivity is strong enough for useful oxidation and substitution chemistry without matching fluorine or chlorine in extremity', 'modern bromine chemistry expanded with drilling fluids, organic synthesis, and earlier flame-retardant applications', 'hazards center on toxic corrosive vapor, strong oxidizing behavior, and environmental concerns for some organobromine compounds'),
        },
    }),
    makeSeed({
        id: 'krypton',
        name: 'Krypton',
        symbol: 'Kr',
        atomicNumber: 36,
        atomicMass: '83.798',
        group: '18',
        period: '4',
        block: 'p',
        category: 'Noble gas',
        roomState: 'Gas',
        electronConfiguration: '[Ar]3d10 4s2 4p6',
        oxidationStates: '0, +2',
        summaryLine: 'Krypton is a noble gas recovered from air whose inertness, emission behavior, and rare compound chemistry make it useful in lighting, lasers, and spectroscopy.',
        importanceLine: 'Its chemistry links closed-shell stability to atmospheric separation, electrical discharge, and the boundary between inert gases and rare noble-gas compounds.',
        heroFacts: ['Trace atmospheric noble gas', 'Recovered from liquid air', 'Bright discharge emission', 'Forms only rare compounds'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Excimer', 'A short-lived excited dimer or complex important in some gas-discharge lasers.'),
            (0, seedFactories_1.term)('Cryogenic air separation', 'Low-temperature fractionation used to isolate rare atmospheric gases.'),
            (0, seedFactories_1.term)('Noble-gas compound', 'A rare compound involving a normally inert group-18 element under unusual conditions.'),
        ],
        sections: {
            classification: facts('a group-18 noble gas with a closed valence shell and extremely limited ordinary reactivity', 'group 18, period 4, p-block', '[Ar]3d10 4s2 4p6', 'it remains monatomic and resists common bond formation under ambient conditions', 'its chemistry is more inert than halogens and comparable to other heavier noble gases, though rare compounds are known'),
            electronic: facts('an [Ar]3d10 4s2 4p6 closed-shell valence arrangement', 'it remains largely monatomic and participates chemically only under unusual excitation or strongly oxidizing conditions', '0 and rare positive states in exotic compounds', 'gas-phase Kr atoms, electrical discharges, excimer systems, and rare krypton fluoride chemistry', 'the filled shell explains both ordinary inertness and the special circumstances required to form krypton compounds'),
            physical: facts('a colorless monatomic gas', 'it is denser than argon and forms cryogenic liquids under low-temperature conditions', 'weak dispersion forces between monatomic atoms control its condensed-phase behavior', 'discharge tubes, laser gas mixtures, and cryogenic atmospheric-gas fractions', 'practical hazards are mainly oxygen displacement and compressed-gas handling'),
            reactivity: facts('chemically inert under ordinary conditions but capable of rare fluoride chemistry under forcing conditions', 'it is used mainly where nonreactive atmospheres or discharge behavior are needed rather than for bulk synthesis', 'high ionization energy and closed-shell stability make ordinary reaction pathways unfavorable', 'rare krypton fluorides, excimer systems, and discharge-plasma behavior define the frontier of krypton chemistry', 'operational concerns are physical and cryogenic rather than corrosive or strongly exothermic in most uses'),
            occurrence: facts('trace amounts in the atmosphere and in cosmic materials', 'it is much rarer in air than argon but recoverable through large-scale air-separation infrastructure', 'the atmosphere is the dominant practical reservoir for commercial krypton', 'environmental cycling is limited because krypton is chemically inert', 'free elemental krypton persists because noble-gas atoms are thermodynamically and kinetically resistant to reaction'),
            isotopes: facts('multiple stable isotopes including krypton-78, 80, 82, 83, 84, and 86', 'several naturally occurring isotopes are stable, giving krypton analytical and geochemical value', 'isotope patterns can record atmospheric processes, nuclear effects, and tracer histories', 'krypton isotopes are useful in environmental tracing, groundwater dating, and specialized analytical work', 'isotopic science is more important for krypton than ordinary synthesis chemistry'),
            production: facts('fractional distillation of liquid air followed by purification from other noble gases', 'commercial recovery depends on processing very large volumes of air because krypton is only a trace atmospheric constituent', 'additional separation from xenon and other rare gases is part of high-purity production', 'purity control is crucial for lighting, lasers, and isotope-related applications', 'supply is tied to the economics of large cryogenic air-separation plants'),
            applied: facts('lighting, flash lamps, specialty lasers, insulating-gas uses, and isotope-tracer science', 'krypton gas, krypton-containing discharge mixtures, excimer-laser systems, and rare krypton compounds', 'krypton is important because inertness and distinctive emission behavior can be exploited simultaneously', 'its technological visibility grew through lighting and laser applications rather than through bulk compound chemistry', 'hazards are usually limited to pressure, cryogenic handling, and oxygen displacement in confined spaces'),
        },
    }),
];
