"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.superheavyElementSeeds = void 0;
const seedFactories_1 = require("@/content/subjects/chemistry/seedFactories");
function facts(a, b, c, d, e) {
    return [a, b, c, d, e];
}
function buildSections(config) {
    return {
        classification: facts(config.classificationLead, `group ${config.group}, period ${config.period}, ${config.block}-block`, config.electronConfiguration, `it is discussed through ${config.compoundsLine}`, config.comparisonNote),
        electronic: facts(`an ${config.electronConfiguration} valence arrangement shaped strongly by relativistic effects`, config.reactivityLead, config.oxidationStates, config.compoundsLine, 'the chemistry is interpreted through calculations and atom-at-a-time experiments rather than bulk samples'),
        physical: facts(config.physicalLead, config.physicalNote, 'short half-lives mean predicted properties are often more important than direct bulk measurement', config.appliedSystems, config.hazardNote),
        reactivity: facts(config.reactivityLead, `it forms or is expected to form ${config.compoundsLine}`, 'surface interactions, volatility trends, and relativistic stabilization dominate the chemistry', config.appliedSystems, config.hazardNote),
        occurrence: facts(config.occurrenceLead, config.occurrenceNote, 'synthetic production and fast transport determine every practical encounter with the element', config.productionRoutes, config.significanceNote),
        isotopes: facts(config.isotopeLead, config.isotopeDetail, 'every known isotope is radioactive and identified through decay chains or correlation experiments', config.isotopeUse, 'all work is constrained by short half-lives and atom-count-scale experiments'),
        production: facts(config.productionLead, config.productionRoutes, 'fusion-evaporation reactions, rapid separation, and decay correlation define practical production', config.appliedSystems, config.significanceNote),
        applied: facts(config.appliedLead, config.appliedSystems, config.significanceNote, config.comparisonNote, config.hazardNote),
    };
}
function makeSeed(config) {
    const sections = buildSections(config);
    return {
        ...config,
        sections: {
            classification: (0, seedFactories_1.classificationSection)(config.name, sections.classification),
            electronic: (0, seedFactories_1.electronicSection)(config.name, sections.electronic),
            physical: (0, seedFactories_1.physicalSection)(config.name, sections.physical),
            reactivity: (0, seedFactories_1.reactivitySection)(config.name, sections.reactivity),
            occurrence: (0, seedFactories_1.occurrenceSection)(config.name, sections.occurrence),
            isotopes: (0, seedFactories_1.isotopeSection)(config.name, sections.isotopes),
            production: (0, seedFactories_1.productionSection)(config.name, sections.production),
            applied: (0, seedFactories_1.appliedSection)(config.name, sections.applied),
        },
    };
}
exports.superheavyElementSeeds = [
    makeSeed({
        id: 'rutherfordium',
        name: 'Rutherfordium',
        symbol: 'Rf',
        atomicNumber: 104,
        atomicMass: '[267]',
        group: '4',
        period: '7',
        block: 'd',
        category: 'Transition metal',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f14 6d2 7s2',
        oxidationStates: '+4',
        summaryLine: 'Rutherfordium is the first transactinide element, expected to behave as a group-4 metal with chemistry analogous to hafnium and zirconium.',
        importanceLine: 'Its chemistry links periodic continuity into the superheavy region with relativistic effects and atom-at-a-time chromatography.',
        heroFacts: ['First transactinide', 'Group-4 analog', 'Known from atom-at-a-time chemistry', 'Short-lived synthetic element'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Transactinide', 'An element beyond the actinide series, typically in the superheavy region.'),
            (0, seedFactories_1.term)('Gas-phase chromatography', 'A method used to identify volatile heavy-element compounds one atom at a time.'),
            (0, seedFactories_1.term)('Relativistic effect', 'A heavy-element effect on electron energies that changes chemical behavior.'),
        ],
        classificationLead: 'a synthetic group-4 transition element whose chemistry is interpreted mainly as a heavy hafnium analog',
        comparisonNote: 'its observed and predicted chemistry largely extends zirconium-hafnium trends into period 7',
        compoundsLine: 'rutherfordium chlorides, bromides, oxides, and adsorption or volatility species studied atom by atom',
        physicalLead: 'a short-lived synthetic metal with no bulk sample available for ordinary physical measurement',
        physicalNote: 'its physical identity is inferred from calculations, periodic trends, and single-atom experiments',
        reactivityLead: 'a transition-metal chemistry expected to favor Rf(IV) halides and oxides',
        occurrenceLead: 'synthetic nuclei formed only in heavy-ion fusion experiments',
        occurrenceNote: 'rutherfordium has no natural occurrence and exists only during accelerator production',
        isotopeLead: 'short-lived radioisotopes such as Rf-261 through Rf-267',
        isotopeDetail: 'all rutherfordium isotopes are radioactive and identified through decay chains',
        isotopeUse: 'chemical identification, decay correlation, and tests of group-4 periodicity',
        productionLead: 'fusion of lighter nuclei in accelerator targets',
        productionRoutes: 'heavy-ion bombardment, recoil transport, and fast gas- or solution-phase chemistry',
        appliedLead: 'fundamental superheavy-element chemistry and periodic-table testing rather than technology',
        appliedSystems: 'single-atom halide species, oxide-related adsorption systems, and rapid chromatography experiments',
        significanceNote: 'its importance lies in proving that recognizable transition-metal chemistry survives into the superheavy region',
        hazardNote: 'hazards are radiological, but practical work is dominated by tiny atom counts and short half-lives',
    }),
    makeSeed({
        id: 'dubnium',
        name: 'Dubnium',
        symbol: 'Db',
        atomicNumber: 105,
        atomicMass: '[268]',
        group: '5',
        period: '7',
        block: 'd',
        category: 'Transition metal',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f14 6d3 7s2',
        oxidationStates: '+5',
        summaryLine: 'Dubnium is a synthetic group-5 element whose chemistry is studied through volatile halides and oxyhalides that connect it to niobium and tantalum.',
        importanceLine: 'Its chemistry links superheavy-element identification to group-5 oxide and halide patterns under relativistic conditions.',
        heroFacts: ['Synthetic group-5 element', 'Db(V) is the key state', 'Studied through halides and oxyhalides', 'Atom-at-a-time chemistry'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Oxyhalide', 'A compound containing both oxygen and halide ligands.'),
            (0, seedFactories_1.term)('Adsorption experiment', 'A method for probing chemical identity by how atoms interact with surfaces.'),
            (0, seedFactories_1.term)('Periodicity test', 'An experiment checking whether a heavy element follows expected group chemistry.'),
        ],
        classificationLead: 'a synthetic group-5 transition element whose chemistry extends niobium-tantalum patterns into the superheavy region',
        comparisonNote: 'it is most often compared with tantalum because both favor high-valent oxide and halide chemistry',
        compoundsLine: 'dubnium chlorides, bromides, oxychlorides, and single-atom adsorption species',
        physicalLead: 'a short-lived synthetic metal known only from atom-scale production',
        physicalNote: 'predicted metallic properties matter less than fast chemical behavior in separation systems',
        reactivityLead: 'a high-valent transition-metal chemistry centered on Db(V) halides and oxyhalides',
        occurrenceLead: 'synthetic production only in accelerator experiments',
        occurrenceNote: 'dubnium exists only for seconds or less in carefully timed chemical systems',
        isotopeLead: 'radioisotopes such as Db-268 and neighboring short-lived nuclides',
        isotopeDetail: 'all isotopes are radioactive and characterized through correlated decay events',
        isotopeUse: 'single-atom chemistry, decay-chain confirmation, and group-5 comparison studies',
        productionLead: 'heavy-ion fusion followed by immediate transport into chemical apparatus',
        productionRoutes: 'target irradiation, recoil capture, rapid volatilization, and chromatography',
        appliedLead: 'fundamental chemistry and nuclear-structure research',
        appliedSystems: 'volatile halides, oxyhalide-like species, and adsorption experiments',
        significanceNote: 'its importance lies in showing that recognizable group-5 chemistry remains measurable at the single-atom level',
        hazardNote: 'hazards are radiological, but the experimental challenge is dominated by production rate and lifetime limits',
    }),
    makeSeed({
        id: 'seaborgium',
        name: 'Seaborgium',
        symbol: 'Sg',
        atomicNumber: 106,
        atomicMass: '[269]',
        group: '6',
        period: '7',
        block: 'd',
        category: 'Transition metal',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f14 6d4 7s2',
        oxidationStates: '+6',
        summaryLine: 'Seaborgium is a synthetic group-6 element expected to resemble tungsten and molybdenum through high-valent oxide, halide, and carbonyl chemistry.',
        importanceLine: 'Its chemistry links the superheavy region to classic group-6 volatility and coordination motifs tested one atom at a time.',
        heroFacts: ['Synthetic group-6 element', 'High-valent chemistry is central', 'Compared with tungsten', 'Studied one atom at a time'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Carbonyl', 'A complex containing carbon monoxide ligands bound to a metal.'),
            (0, seedFactories_1.term)('Volatility trend', 'A pattern in how easily compounds vaporize across a chemical family.'),
            (0, seedFactories_1.term)('Single-atom experiment', 'A chemical experiment performed with extremely small numbers of atoms.'),
        ],
        classificationLead: 'a synthetic group-6 transition element whose chemistry is interpreted as a very heavy tungsten analogue',
        comparisonNote: 'it provides one of the clearest tests of whether tungsten-like oxide and carbonyl chemistry persists at the edge of the table',
        compoundsLine: 'seaborgium oxychlorides, volatile oxide species, and predicted carbonyl-type complexes',
        physicalLead: 'a short-lived synthetic metallic element without bulk physical samples',
        physicalNote: 'chemical volatility and adsorption behavior matter far more than direct bulk-property measurement',
        reactivityLead: 'a transition-metal chemistry expected to favor high-valent oxide and halide species',
        occurrenceLead: 'synthetic production in heavy-ion fusion facilities',
        occurrenceNote: 'seaborgium is never found naturally and is encountered only in accelerator experiments',
        isotopeLead: 'short-lived isotopes such as Sg-269 and neighboring nuclides',
        isotopeDetail: 'all seaborgium isotopes are radioactive and tracked through decay chains',
        isotopeUse: 'single-atom chemistry and tests of group-6 periodicity',
        productionLead: 'fusion-evaporation production with rapid recoil transport',
        productionRoutes: 'accelerator bombardment, gas-jet transfer, and volatility or adsorption experiments',
        appliedLead: 'fundamental superheavy chemistry rather than practical technology',
        appliedSystems: 'oxide-related volatile species, adsorption systems, and predicted carbonyl chemistry',
        significanceNote: 'its importance lies in connecting superheavy chemistry to familiar tungsten-type ligand systems',
        hazardNote: 'hazards are radiological, while the main operational limits are lifetimes and atom numbers',
    }),
    makeSeed({
        id: 'bohrium',
        name: 'Bohrium',
        symbol: 'Bh',
        atomicNumber: 107,
        atomicMass: '[270]',
        group: '7',
        period: '7',
        block: 'd',
        category: 'Transition metal',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f14 6d5 7s2',
        oxidationStates: '+7',
        summaryLine: 'Bohrium is a synthetic group-7 element expected to continue rhenium and technetium chemistry into the superheavy region.',
        importanceLine: 'Its chemistry is important because it tests whether group-7 volatility and high-oxidation-state motifs survive strong relativistic effects.',
        heroFacts: ['Synthetic group-7 element', 'High oxidation states expected', 'Compared with rhenium', 'Known through a few atom-at-a-time studies'],
        glossaryExtras: [
            (0, seedFactories_1.term)('High oxidation state', 'An oxidation state near the upper end of what an element can sustain.'),
            (0, seedFactories_1.term)('Chromatographic identification', 'Recognition of an element through its movement in a separation system.'),
            (0, seedFactories_1.term)('Fusion product', 'A nucleus formed in a heavy-ion fusion reaction.'),
        ],
        classificationLead: 'a synthetic group-7 transition element predicted to resemble rhenium in high-valent chemistry',
        comparisonNote: 'it is studied as the next step after rhenium-technetium chemistry, but only through single atoms',
        compoundsLine: 'bohrium oxyhalides, oxide species, and adsorption intermediates',
        physicalLead: 'a short-lived synthetic metal without accessible bulk physical characterization',
        physicalNote: 'chemical identity is inferred from volatility, transport, and decay rather than macroscopic properties',
        reactivityLead: 'a heavy transition-metal chemistry expected to favor high oxidation states and volatile oxyspecies',
        occurrenceLead: 'accelerator-made nuclei only',
        occurrenceNote: 'bohrium has no natural presence and is generated only in controlled fusion experiments',
        isotopeLead: 'radioisotopes such as Bh-270 and related nuclides',
        isotopeDetail: 'all isotopes are radioactive and extremely short lived',
        isotopeUse: 'decay-chain assignments and sparse chemical comparison studies',
        productionLead: 'heavy-ion fusion followed by fast physical and chemical separation',
        productionRoutes: 'target irradiation, recoil transport, and time-critical adsorption experiments',
        appliedLead: 'fundamental periodicity research',
        appliedSystems: 'single-atom oxide or oxyhalide species and surface-interaction experiments',
        significanceNote: 'its importance is conceptual because it extends group-7 chemistry into a region of very limited experimental access',
        hazardNote: 'hazards are radiological, though tiny production rates dominate the practical difficulty',
    }),
    makeSeed({
        id: 'hassium',
        name: 'Hassium',
        symbol: 'Hs',
        atomicNumber: 108,
        atomicMass: '[269]',
        group: '8',
        period: '7',
        block: 'd',
        category: 'Transition metal',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f14 6d6 7s2',
        oxidationStates: '+8',
        summaryLine: 'Hassium is a synthetic group-8 element notable because hassium tetroxide chemistry provides a rare direct comparison with osmium.',
        importanceLine: 'Its chemistry links superheavy-element research to one of the clearest experimentally observed analogies between a transactinide and its lighter group partner.',
        heroFacts: ['Synthetic group-8 element', 'HsO4 chemistry is important', 'Compared with osmium', 'One of the better-studied transactinides'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Tetroxide', 'An oxide containing four oxygen atoms per metal center, such as OsO4 or HsO4.'),
            (0, seedFactories_1.term)('Group analogy', 'A comparison between an element and the lighter members of its periodic group.'),
            (0, seedFactories_1.term)('Volatile oxide', 'An oxide that is sufficiently volatile to be studied in gas-phase systems.'),
        ],
        classificationLead: 'a synthetic group-8 transition element whose chemistry most clearly parallels osmium',
        comparisonNote: 'hassium is one of the strongest examples of recognizable group behavior in the superheavy region because HsO4-like chemistry is experimentally accessible',
        compoundsLine: 'hassium tetroxide and related volatile oxide species studied in gas-phase systems',
        physicalLead: 'a short-lived synthetic metal known through a handful of chemically characterized atoms',
        physicalNote: 'its physical profile is inferred from calculations and the behavior of volatile oxide species',
        reactivityLead: 'a heavy transition-metal chemistry centered on high-valent volatile oxide formation',
        occurrenceLead: 'synthetic fusion products only',
        occurrenceNote: 'hassium exists only during accelerator experiments and rapid chemical transport',
        isotopeLead: 'short-lived isotopes such as Hs-269 and neighboring nuclides',
        isotopeDetail: 'all isotopes are radioactive and identified through decay correlation',
        isotopeUse: 'gas-phase oxide chemistry and validation of group-8 periodicity',
        productionLead: 'fusion synthesis followed by rapid oxide-generation and chromatography experiments',
        productionRoutes: 'accelerator bombardment, recoil transport, oxidation, and gas-phase separation',
        appliedLead: 'fundamental chemical identification in the superheavy region',
        appliedSystems: 'HsO4-like volatile species and chromatography surfaces',
        significanceNote: 'its importance comes from providing one of the clearest experimental windows into superheavy transition-metal chemistry',
        hazardNote: 'hazards are radiological, but the chemistry is limited by extremely small atom counts and short lifetimes',
    }),
    makeSeed({
        id: 'meitnerium',
        name: 'Meitnerium',
        symbol: 'Mt',
        atomicNumber: 109,
        atomicMass: '[278]',
        group: '9',
        period: '7',
        block: 'd',
        category: 'Transition metal',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f14 6d7 7s2',
        oxidationStates: '+1, +3',
        summaryLine: 'Meitnerium is a synthetic group-9 element whose chemistry is largely predicted from relativistic calculations and trends from iridium and rhodium.',
        importanceLine: 'It matters because it pushes the periodic-table question from observed chemistry into the boundary where prediction guides experiment.',
        heroFacts: ['Synthetic group-9 element', 'Chemistry mostly predicted', 'Compared with iridium', 'Short-lived heavy nucleus'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Calculated chemistry', 'Chemistry inferred from theory when direct experiments are extremely limited.'),
            (0, seedFactories_1.term)('Relativistic stabilization', 'Energy lowering of specific orbitals in heavy elements due to relativistic effects.'),
            (0, seedFactories_1.term)('Heavy-ion fusion', 'Production of a heavy nucleus by colliding lighter nuclei at high energy.'),
        ],
        classificationLead: 'a synthetic group-9 transition element whose chemical behavior is still known mostly from theory',
        comparisonNote: 'it is expected to continue iridium-like noble-metal tendencies, but experimental data remain extremely sparse',
        compoundsLine: 'predicted halides, adsorption species, and noble-metal-like surface interactions',
        physicalLead: 'a very short-lived synthetic metal without direct bulk characterization',
        physicalNote: 'most physical and chemical properties remain theoretical because only tiny numbers of atoms are produced',
        reactivityLead: 'a heavy transition-metal chemistry expected to show noble-metal tendencies and limited high-valent species',
        occurrenceLead: 'synthetic production only',
        occurrenceNote: 'meitnerium exists solely in accelerator experiments and survives briefly',
        isotopeLead: 'radioisotopes such as Mt-278 and related heavy nuclides',
        isotopeDetail: 'all isotopes are radioactive and too short lived for extensive chemistry',
        isotopeUse: 'decay studies and limited periodic-trend testing',
        productionLead: 'heavy-ion fusion at very low production rates',
        productionRoutes: 'accelerator bombardment, recoil separation, and decay-chain detection',
        appliedLead: 'fundamental nuclear and theoretical chemistry research',
        appliedSystems: 'predicted adsorption species and decay-correlation experiments',
        significanceNote: 'its importance is in testing the predictive power of heavy-element theory where direct chemistry is barely accessible',
        hazardNote: 'hazards are radiological, though the dominant limitation is the scarcity of atoms rather than chemical exposure',
    }),
    makeSeed({
        id: 'darmstadtium',
        name: 'Darmstadtium',
        symbol: 'Ds',
        atomicNumber: 110,
        atomicMass: '[281]',
        group: '10',
        period: '7',
        block: 'd',
        category: 'Transition metal',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f14 6d8 7s2',
        oxidationStates: '0, +2',
        summaryLine: 'Darmstadtium is a synthetic group-10 element expected to show noble-metal chemistry related to platinum and palladium, though experiments remain very limited.',
        importanceLine: 'Its chemistry is important because it probes how far platinum-group characteristics persist when relativistic effects become extreme.',
        heroFacts: ['Synthetic group-10 element', 'Noble-metal behavior expected', 'Compared with platinum', 'Chemistry still very limited'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Noble-metal behavior', 'Resistance to oxidation combined with distinctive coordination and surface chemistry.'),
            (0, seedFactories_1.term)('Surface interaction', 'Chemical behavior inferred from how atoms adsorb to solid surfaces.'),
            (0, seedFactories_1.term)('Periodic persistence', 'The extent to which group trends remain valid in very heavy elements.'),
        ],
        classificationLead: 'a synthetic group-10 transition element expected to behave as a very heavy platinum-group metal',
        comparisonNote: 'it is chemically interesting because platinum-group trends may persist, but the available evidence is extremely sparse',
        compoundsLine: 'predicted volatile species, adsorption states, and noble-metal-like atomic interactions',
        physicalLead: 'a very short-lived synthetic metal without bulk samples',
        physicalNote: 'direct physical data are absent, so chemistry relies on theory and limited atomic observations',
        reactivityLead: 'a chemistry expected to be relatively noble, with surface and adsorption behavior more accessible than solution chemistry',
        occurrenceLead: 'accelerator-made nuclei only',
        occurrenceNote: 'darmstadtium has no natural occurrence and is observed only in rare fusion events',
        isotopeLead: 'radioisotopes such as Ds-281 and neighboring nuclides',
        isotopeDetail: 'all isotopes are radioactive and identified through short decay chains',
        isotopeUse: 'periodicity testing and nuclear-structure studies',
        productionLead: 'heavy-ion fusion with very low atom yields',
        productionRoutes: 'accelerator irradiation, recoil separation, and decay-event analysis',
        appliedLead: 'fundamental heavy-element theory and nuclear research',
        appliedSystems: 'predicted adsorption experiments and short-lived atomic studies',
        significanceNote: 'its importance lies in testing whether platinum-group chemistry remains meaningful at element 110',
        hazardNote: 'hazards are radiological, but the main experimental challenge is obtaining enough atoms for any chemistry at all',
    }),
    makeSeed({
        id: 'roentgenium',
        name: 'Roentgenium',
        symbol: 'Rg',
        atomicNumber: 111,
        atomicMass: '[282]',
        group: '11',
        period: '7',
        block: 'd',
        category: 'Transition metal',
        roomState: 'Solid',
        electronConfiguration: '[Rn]5f14 6d10 7s1',
        oxidationStates: '+1, +3',
        summaryLine: 'Roentgenium is a synthetic group-11 element expected to continue coinage-metal trends with strong relativistic modification.',
        importanceLine: 'Its chemistry connects copper-silver-gold behavior to the superheavy regime, where surface interactions and theory dominate.',
        heroFacts: ['Synthetic coinage-metal analogue', 'Relativistic effects are strong', 'Compared with gold', 'Known mainly from theory'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Coinage metal', 'A group-11 metal such as copper, silver, or gold.'),
            (0, seedFactories_1.term)('Adsorption surface', 'A surface used to probe how single atoms interact chemically.'),
            (0, seedFactories_1.term)('Relativistic trend', 'A periodic trend altered by high nuclear charge and relativistic electron motion.'),
        ],
        classificationLead: 'a synthetic group-11 transition element expected to resemble an extreme heavy analogue of gold',
        comparisonNote: 'its chemistry is interpreted through coinage-metal trends strongly altered by relativistic effects',
        compoundsLine: 'predicted halides, surface-bound atomic species, and noble-metal-like adsorption states',
        physicalLead: 'a short-lived synthetic metal without direct macroscopic characterization',
        physicalNote: 'chemical expectations come mainly from theory and sparse atomic observations',
        reactivityLead: 'a heavy coinage-metal chemistry expected to favor low oxidation states and noble surface behavior',
        occurrenceLead: 'synthetic fusion products only',
        occurrenceNote: 'roentgenium is produced only in accelerator experiments',
        isotopeLead: 'radioisotopes such as Rg-282 and neighboring nuclides',
        isotopeDetail: 'all isotopes are radioactive and defined by decay-chain measurements',
        isotopeUse: 'nuclear-structure work and theoretical tests of group-11 chemistry',
        productionLead: 'fusion-evaporation production with immediate decay detection',
        productionRoutes: 'accelerator bombardment, recoil separation, and short-lived atom studies',
        appliedLead: 'fundamental heavy-element chemistry and nuclear physics',
        appliedSystems: 'predicted adsorption experiments and atom-scale species',
        significanceNote: 'its importance is conceptual because it probes whether gold-like chemistry persists at element 111',
        hazardNote: 'hazards are radiological, while experimental scarcity limits chemistry more than exposure risk',
    }),
    makeSeed({
        id: 'copernicium',
        name: 'Copernicium',
        symbol: 'Cn',
        atomicNumber: 112,
        atomicMass: '[285]',
        group: '12',
        period: '7',
        block: 'd',
        category: 'D-block metal',
        roomState: 'Unknown',
        electronConfiguration: '[Rn]5f14 6d10 7s2',
        oxidationStates: '+2, +4',
        summaryLine: 'Copernicium is a synthetic group-12 element whose closed-shell-like electronic structure may make it unusually volatile and weakly metallic.',
        importanceLine: 'Its chemistry matters because it tests how far zinc-cadmium-mercury trends persist when relativistic effects strongly stabilize outer electrons.',
        heroFacts: ['Synthetic group-12 element', 'Relativistic stabilization is strong', 'Possibly unusually volatile', 'Chemistry partly measured'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Closed-shell-like behavior', 'Behavior associated with especially stable filled outer shells.'),
            (0, seedFactories_1.term)('Volatile metal', 'A metal or metallic compound that vaporizes comparatively easily.'),
            (0, seedFactories_1.term)('Atom-scale transport', 'Movement of single atoms through a measurement system.'),
        ],
        classificationLead: 'a synthetic group-12 element whose chemistry may be more volatile and less metallic than simple trend extrapolation suggests',
        comparisonNote: 'it continues zinc-cadmium-mercury trends but may depart from them because the 7s shell is strongly stabilized',
        compoundsLine: 'copernicium adsorption states, predicted halides, and volatile atomic species',
        physicalLead: 'a short-lived synthetic element whose condensed-matter state is inferred rather than directly measured',
        physicalNote: 'volatility and surface interaction are more accessible than conventional bulk measurements',
        reactivityLead: 'a heavy d-block chemistry expected to favor weak metallic bonding and limited accessible oxidation states',
        occurrenceLead: 'synthetic production only',
        occurrenceNote: 'copernicium is encountered exclusively in accelerator experiments and short transport systems',
        isotopeLead: 'radioisotopes such as Cn-285 and neighboring nuclides',
        isotopeDetail: 'all isotopes are radioactive and known through fast-decay studies',
        isotopeUse: 'adsorption experiments, nuclear-structure work, and theoretical benchmarking',
        productionLead: 'heavy-ion fusion followed by time-critical atom transport',
        productionRoutes: 'accelerator synthesis, recoil separation, and single-atom surface experiments',
        appliedLead: 'fundamental heavy-element chemistry rather than applications',
        appliedSystems: 'adsorption experiments, predicted halides, and volatility studies',
        significanceNote: 'its importance lies in testing whether group-12 chemistry becomes quasi-noble or unusually weakly metallic at element 112',
        hazardNote: 'hazards are radiological, but the chemistry is chiefly limited by tiny yields and short lifetimes',
    }),
    makeSeed({
        id: 'nihonium',
        name: 'Nihonium',
        symbol: 'Nh',
        atomicNumber: 113,
        atomicMass: '[286]',
        group: '13',
        period: '7',
        block: 'p',
        category: 'Post-transition metal',
        roomState: 'Unknown',
        electronConfiguration: '[Rn]5f14 6d10 7s2 7p1',
        oxidationStates: '+1, +3',
        summaryLine: 'Nihonium is a synthetic heavy p-block element expected to show strong inert-pair effects and chemistry closer to Tl(I) than to lighter group-13 elements.',
        importanceLine: 'Its chemistry links superheavy p-block behavior to relativistic stabilization, volatile species, and the changing meaning of group analogies.',
        heroFacts: ['Synthetic group-13 element', 'Strong inert-pair effect expected', 'Nh(I) may be important', 'Heavy p-block chemistry'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Inert-pair effect', 'The reluctance of ns2 electrons in heavy p-block elements to participate in bonding.'),
            (0, seedFactories_1.term)('Heavy p-block element', 'A p-block element where relativistic and inert-pair effects are especially strong.'),
            (0, seedFactories_1.term)('Single-atom p-block chemistry', 'Chemical study of one-atom-at-a-time compounds of very heavy p-block elements.'),
        ],
        classificationLead: 'a synthetic group-13 post-transition element expected to behave more like an extreme thallium analogue than like aluminum',
        comparisonNote: 'its chemistry is especially important for testing how strongly the inert-pair effect reshapes the p-block at very high atomic number',
        compoundsLine: 'predicted nihonium halides, hydroxides, adsorption species, and low-valent atomic forms',
        physicalLead: 'a short-lived synthetic heavy p-block element with no macroscopic physical sample',
        physicalNote: 'predicted metallic or weakly metallic character is inferred from theory and atom-scale experiments',
        reactivityLead: 'a heavy p-block chemistry expected to emphasize Nh(I) and limited higher-valent species',
        occurrenceLead: 'synthetic accelerator production only',
        occurrenceNote: 'nihonium has no natural occurrence and is generated one nucleus at a time',
        isotopeLead: 'radioisotopes such as Nh-286 and related nuclides',
        isotopeDetail: 'all isotopes are radioactive and identified through decay chains',
        isotopeUse: 'periodicity testing and nuclear-structure studies',
        productionLead: 'heavy-ion fusion with rapid transport and identification',
        productionRoutes: 'accelerator bombardment, recoil separation, and single-atom detection',
        appliedLead: 'fundamental chemistry and the study of relativistic p-block trends',
        appliedSystems: 'predicted halides, adsorption experiments, and atom-scale p-block species',
        significanceNote: 'its importance lies in showing how the simple group-13 pattern changes near the bottom of the periodic table',
        hazardNote: 'hazards are radiological, while chemistry is limited mainly by production rate and isotope lifetime',
    }),
    makeSeed({
        id: 'flerovium',
        name: 'Flerovium',
        symbol: 'Fl',
        atomicNumber: 114,
        atomicMass: '[289]',
        group: '14',
        period: '7',
        block: 'p',
        category: 'Post-transition metal',
        roomState: 'Unknown',
        electronConfiguration: '[Rn]5f14 6d10 7s2 7p2',
        oxidationStates: '+2, +4',
        summaryLine: 'Flerovium is a synthetic group-14 element predicted to show very strong inert-pair effects and unexpectedly weak metallic or volatile behavior.',
        importanceLine: 'Its chemistry matters because it probes whether group-14 trends continue toward lead or break into much more weakly bonded behavior.',
        heroFacts: ['Synthetic group-14 element', 'Strong inert-pair effect expected', 'May be unusually volatile', 'Compared with lead'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Volatility anomaly', 'A case where a heavy element is more volatile than simple trends would predict.'),
            (0, seedFactories_1.term)('Weak metallic bonding', 'Metallic bonding that is reduced relative to lighter congeners.'),
            (0, seedFactories_1.term)('Group-14 trend', 'The chemical progression from carbon through silicon, tin, and lead.'),
        ],
        classificationLead: 'a synthetic group-14 heavy p-block element expected to show much stronger inert-pair behavior than lead',
        comparisonNote: 'its chemistry may depart strikingly from ordinary metallic group-14 expectations because Fl(II) could dominate',
        compoundsLine: 'predicted flerovium halides, adsorption species, and low-valent p-block compounds',
        physicalLead: 'a short-lived synthetic element whose condensed behavior may be weakly metallic and comparatively volatile',
        physicalNote: 'surface interactions and adsorption studies are more informative than any inaccessible bulk sample',
        reactivityLead: 'a heavy p-block chemistry expected to emphasize low-valent states and relatively weak bonding',
        occurrenceLead: 'synthetic production in accelerator facilities only',
        occurrenceNote: 'flerovium is created one atom at a time and studied through rapid physical-chemical detection',
        isotopeLead: 'radioisotopes such as Fl-289 and related nuclides',
        isotopeDetail: 'all isotopes are radioactive and are identified by their correlated decay sequences',
        isotopeUse: 'testing p-block periodicity and studying heavy-nucleus stability',
        productionLead: 'heavy-ion fusion followed by rapid surface and decay measurements',
        productionRoutes: 'accelerator synthesis, recoil transport, adsorption studies, and decay correlation',
        appliedLead: 'fundamental heavy-element research rather than practical use',
        appliedSystems: 'single-atom adsorption experiments and predicted halide chemistry',
        significanceNote: 'its importance lies in challenging simple expectations about how metallic the bottom of group 14 should be',
        hazardNote: 'hazards are radiological, but experimental work is constrained mainly by low yields and short-lived isotopes',
    }),
    makeSeed({
        id: 'moscovium',
        name: 'Moscovium',
        symbol: 'Mc',
        atomicNumber: 115,
        atomicMass: '[290]',
        group: '15',
        period: '7',
        block: 'p',
        category: 'Post-transition metal',
        roomState: 'Unknown',
        electronConfiguration: '[Rn]5f14 6d10 7s2 7p3',
        oxidationStates: '+1, +3',
        summaryLine: 'Moscovium is a synthetic heavy pnictogen expected to display strong inert-pair effects and chemistry more metallic than bismuth.',
        importanceLine: 'Its chemistry extends group-15 trends into a region where relativistic effects strongly reshape oxidation-state preferences.',
        heroFacts: ['Synthetic group-15 element', 'Heavy pnictogen behavior', 'Strong inert-pair effect expected', 'Chemistry largely predicted'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Pnictogen', 'An element of group 15 of the periodic table.'),
            (0, seedFactories_1.term)('Oxidation-state preference', 'A favored oxidation state under ordinary chemical conditions.'),
            (0, seedFactories_1.term)('Relativistic p-block chemistry', 'Heavy p-block chemistry strongly altered by relativistic effects.'),
        ],
        classificationLead: 'a synthetic group-15 post-transition element expected to show more metallic behavior and lower oxidation states than lighter pnictogens',
        comparisonNote: 'it is studied as a heavy bismuth analogue whose chemistry may favor Mc(I) or Mc(III) more strongly than simple trends suggest',
        compoundsLine: 'predicted moscovium halides, hydroxides, adsorption species, and low-valent pnictogen compounds',
        physicalLead: 'a short-lived synthetic heavy p-block element with no direct bulk characterization',
        physicalNote: 'the element is assessed through calculations and a very small number of atom-scale experiments',
        reactivityLead: 'a heavy pnictogen chemistry expected to prefer lower oxidation states because of strong inert-pair stabilization',
        occurrenceLead: 'synthetic production only',
        occurrenceNote: 'moscovium is created solely in accelerator fusion experiments',
        isotopeLead: 'radioisotopes such as Mc-290 and neighboring nuclides',
        isotopeDetail: 'all isotopes are radioactive and defined by their decay chains',
        isotopeUse: 'nuclear-structure studies and periodicity tests',
        productionLead: 'heavy-ion fusion followed by fast transport and detection',
        productionRoutes: 'accelerator synthesis, recoil separation, and atom-scale decay analysis',
        appliedLead: 'fundamental p-block and nuclear research',
        appliedSystems: 'predicted halides, adsorption experiments, and short-lived single-atom species',
        significanceNote: 'its importance lies in how it reshapes expectations for group-15 chemistry at extreme atomic number',
        hazardNote: 'hazards are radiological, though the main limit is experimental scarcity rather than direct exposure',
    }),
    makeSeed({
        id: 'livermorium',
        name: 'Livermorium',
        symbol: 'Lv',
        atomicNumber: 116,
        atomicMass: '[293]',
        group: '16',
        period: '7',
        block: 'p',
        category: 'Post-transition metal',
        roomState: 'Unknown',
        electronConfiguration: '[Rn]5f14 6d10 7s2 7p4',
        oxidationStates: '+2, +4',
        summaryLine: 'Livermorium is a synthetic heavy chalcogen expected to show strong relativistic stabilization and oxidation-state preferences unlike sulfur or selenium.',
        importanceLine: 'Its chemistry links chalcogen trends to heavy p-block metallicity, low-valent behavior, and the uncertain boundary between nonmetal and metal.',
        heroFacts: ['Synthetic heavy chalcogen', 'Low oxidation states may be favored', 'Chemistry mostly theoretical', 'Heavy p-block behavior'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Chalcogen', 'An element of group 16 of the periodic table.'),
            (0, seedFactories_1.term)('Low-valent behavior', 'Preference for lower oxidation states than group trends might suggest.'),
            (0, seedFactories_1.term)('Metal-nonmetal boundary', 'The region where elements show mixed metallic and nonmetallic character.'),
        ],
        classificationLead: 'a synthetic group-16 heavy p-block element expected to be much more metallic and lower-valent than lighter chalcogens',
        comparisonNote: 'its chemistry is expected to depart strongly from sulfur and oxygen, and even from tellurium or polonium, because of heavy-element effects',
        compoundsLine: 'predicted livermorium halides, hydrides, adsorption species, and low-valent chalcogen compounds',
        physicalLead: 'a short-lived synthetic heavy element whose physical state and bonding are inferred rather than directly measured',
        physicalNote: 'calculations suggest a more metallic character than simple chalcogen analogies would imply',
        reactivityLead: 'a heavy chalcogen chemistry expected to favor lower oxidation states and relatively soft bonding',
        occurrenceLead: 'synthetic production only',
        occurrenceNote: 'livermorium exists only as a laboratory-made heavy nucleus',
        isotopeLead: 'radioisotopes such as Lv-293 and related nuclides',
        isotopeDetail: 'all isotopes are radioactive and observed through decay correlations',
        isotopeUse: 'nuclear-structure work and heavy p-block periodicity tests',
        productionLead: 'heavy-ion fusion with very small atom yields',
        productionRoutes: 'accelerator production, recoil separation, and short-lived atom studies',
        appliedLead: 'fundamental superheavy p-block chemistry',
        appliedSystems: 'predicted halides, adsorption systems, and decay-linked atom-scale studies',
        significanceNote: 'its importance lies in showing how far the chalcogen family changes when relativistic effects dominate',
        hazardNote: 'hazards are radiological, but the overriding challenge is the inability to accumulate appreciable quantities',
    }),
    makeSeed({
        id: 'tennessine',
        name: 'Tennessine',
        symbol: 'Ts',
        atomicNumber: 117,
        atomicMass: '[294]',
        group: '17',
        period: '7',
        block: 'p',
        category: 'Halogen',
        roomState: 'Unknown',
        electronConfiguration: '[Rn]5f14 6d10 7s2 7p5',
        oxidationStates: '-1, +1, +3, +5',
        summaryLine: 'Tennessine is a synthetic superheavy halogen whose chemistry may be much less purely halogen-like than chlorine, bromine, or iodine.',
        importanceLine: 'Its chemistry links the halogen group to strong spin-orbit and relativistic effects that may weaken the classic halogen pattern.',
        heroFacts: ['Synthetic halogen', 'Heavy-element effects are extreme', 'Halogen behavior may be weakened', 'Atom-scale chemistry only'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Spin-orbit coupling', 'Interaction between electron spin and motion that becomes strong in heavy atoms.'),
            (0, seedFactories_1.term)('Halogen analogue', 'An element compared with other group-17 elements.'),
            (0, seedFactories_1.term)('Surface chemistry probe', 'A method for inferring chemistry from interactions with surfaces.'),
        ],
        classificationLead: 'a synthetic group-17 element expected to retain some halogen character but with much softer and less oxidizing behavior than lighter congeners',
        comparisonNote: 'it tests whether the halogen family remains recognizable when strong spin-orbit and relativistic effects reshape the valence shell',
        compoundsLine: 'predicted tennessine halides, adsorption species, and low-valent heavy-halogen compounds',
        physicalLead: 'a short-lived synthetic heavy p-block element with no bulk sample and only predicted condensed-state properties',
        physicalNote: 'its chemistry is inferred through theory because direct experiments are still extremely limited',
        reactivityLead: 'a heavy halogen chemistry expected to be less strongly oxidizing and more metallic than iodine or astatine',
        occurrenceLead: 'synthetic production only',
        occurrenceNote: 'tennessine is created exclusively in accelerator fusion experiments',
        isotopeLead: 'radioisotopes such as Ts-294 and neighboring nuclides',
        isotopeDetail: 'all isotopes are radioactive and identified through decay chains',
        isotopeUse: 'group-17 periodicity tests and superheavy-nucleus studies',
        productionLead: 'heavy-ion fusion with rapid recoil detection',
        productionRoutes: 'accelerator bombardment, recoil separation, and decay-event analysis',
        appliedLead: 'fundamental halogen-periodicity research',
        appliedSystems: 'predicted halides, adsorption experiments, and atom-scale superheavy chemistry',
        significanceNote: 'its importance comes from testing whether the halogens remain a coherent family at the very bottom of the table',
        hazardNote: 'hazards are radiological, though experiments are chiefly limited by production and lifetime constraints',
    }),
    makeSeed({
        id: 'oganesson',
        name: 'Oganesson',
        symbol: 'Og',
        atomicNumber: 118,
        atomicMass: '[294]',
        group: '18',
        period: '7',
        block: 'p',
        category: 'Noble gas',
        roomState: 'Unknown',
        electronConfiguration: '[Rn]5f14 6d10 7s2 7p6',
        oxidationStates: '0, +2',
        summaryLine: 'Oganesson is the heaviest known element and a superheavy group-18 element predicted to be far less idealized as a noble gas than helium through radon.',
        importanceLine: 'Its chemistry is important because it tests the limits of the noble-gas concept itself when relativistic effects become overwhelming.',
        heroFacts: ['Heaviest known element', 'Group-18 member', 'May not behave like a simple noble gas', 'Known only from a few atoms'],
        glossaryExtras: [
            (0, seedFactories_1.term)('Noble-gas concept', 'The idea that filled-shell group-18 elements are especially unreactive.'),
            (0, seedFactories_1.term)('Extreme relativistic chemistry', 'Chemical behavior in which relativistic effects profoundly alter periodic expectations.'),
            (0, seedFactories_1.term)('Periodic limit test', 'An experiment probing whether familiar family patterns still hold at the end of the table.'),
        ],
        classificationLead: 'the heaviest known group-18 element, predicted to be much more polarizable and less ideally inert than lighter noble gases',
        comparisonNote: 'it is chemically fascinating because it may weaken or redefine the very idea of a noble gas at the bottom of the periodic table',
        compoundsLine: 'predicted oganesson compounds, adsorption species, and highly polarizable closed-shell interactions',
        physicalLead: 'a synthetic element known from only a few atoms, with all physical properties inferred theoretically',
        physicalNote: 'predictions suggest much stronger interatomic interactions than those of lighter noble gases',
        reactivityLead: 'a group-18 chemistry expected to be more reactive and more easily polarized than radon or xenon',
        occurrenceLead: 'synthetic production only in rare accelerator events',
        occurrenceNote: 'oganesson does not occur naturally and has been observed only through a handful of decay sequences',
        isotopeLead: 'short-lived oganesson isotopes such as Og-294',
        isotopeDetail: 'all isotopes are radioactive and extremely short lived',
        isotopeUse: 'nuclear-structure studies and the testing of the noble-gas concept at extreme atomic number',
        productionLead: 'heavy-ion fusion followed by recoil and decay correlation',
        productionRoutes: 'accelerator bombardment, recoil separation, and ultra-low-statistics detection',
        appliedLead: 'fundamental tests of periodicity and heavy-element theory',
        appliedSystems: 'predicted adsorption species, theoretical compounds, and decay-linked atom observations',
        significanceNote: 'its importance is profound because it probes the endpoint of the current periodic table and the limits of group-18 behavior',
        hazardNote: 'hazards are radiological, but the chemistry is entirely constrained by the production of only a few atoms',
    }),
];
