"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.mathematicsAccentSources = exports.mathematicsUnits = exports.mathematicsTopics = exports.mathematicsSubject = void 0;
const createStructuredSubject_1 = require("@/content/subjects/shared/createStructuredSubject");
const topics = [
    {
        id: 'foundations-of-mathematics',
        title: 'Foundations of Mathematics',
        description: 'Numbers, logic, notation, proof, and the core language used across mathematical disciplines.',
        units: [
            { title: 'What Is Mathematics?' },
            { title: 'Sets and Number Systems' },
            { title: 'Mathematical Notation' },
            { title: 'Logic and Statements' },
            { title: 'Patterns and Structure' },
            { title: 'Introduction to Proof' },
        ],
    },
    {
        id: 'arithmetic-and-number-sense',
        title: 'Arithmetic and Number Sense',
        description: 'Operations, fractions, ratios, percentages, and quantitative reasoning with real numbers.',
        units: [
            { title: 'Whole Numbers and Integers' },
            { title: 'Fractions' },
            { title: 'Decimals' },
            { title: 'Ratios and Proportions' },
            { title: 'Percentages' },
            { title: 'Exponents and Roots' },
            { title: 'Order of Operations' },
            { title: 'Estimation and Mental Math' },
        ],
    },
    {
        id: 'pre-algebra',
        title: 'Pre-Algebra',
        description: 'Variables, expressions, simple equations, and the transition from arithmetic to symbolic mathematics.',
        units: [
            { title: 'Variables and Expressions' },
            { title: 'Combining Like Terms' },
            { title: 'Solving One-Step Equations', aliases: ['Solving One Step Equations'] },
            { title: 'Solving Multi-Step Equations', aliases: ['Solving Multi Step Equations'] },
            { title: 'Inequalities' },
            { title: 'Factors and Multiples' },
            { title: 'Introductory Word Problems' },
        ],
    },
    {
        id: 'algebra-i',
        title: 'Algebra I',
        description: 'Linear equations, functions, systems, and foundational symbolic reasoning.',
        units: [
            { title: 'Linear Equations' },
            { title: 'Slope' },
            { title: 'Graphing Lines' },
            { title: 'Functions Basics' },
            { title: 'Systems of Equations' },
            { title: 'Linear Inequalities' },
            { title: 'Exponents in Algebra' },
            { title: 'Polynomials Introduction' },
        ],
    },
    {
        id: 'algebra-ii',
        title: 'Algebra II',
        description: 'Quadratics, polynomials, rational expressions, exponentials, logarithms, and more advanced symbolic methods.',
        units: [
            { title: 'Quadratic Expressions' },
            { title: 'Solving Quadratic Equations' },
            { title: 'Graphing Quadratic Functions' },
            { title: 'Polynomial Operations' },
            { title: 'Factoring Techniques' },
            { title: 'Rational Expressions' },
            { title: 'Radical Expressions' },
            { title: 'Exponential Functions' },
            { title: 'Logarithmic Functions' },
            { title: 'Complex Numbers' },
        ],
    },
    {
        id: 'geometry',
        title: 'Geometry',
        description: 'Shapes, spatial reasoning, measurement, proof, and the properties of figures in two and three dimensions.',
        units: [
            { title: 'Points, Lines, and Angles' },
            { title: 'Triangles' },
            { title: 'Congruence' },
            { title: 'Similarity' },
            { title: 'Polygons' },
            { title: 'Circles' },
            { title: 'Area' },
            { title: 'Surface Area and Volume' },
            { title: 'Coordinate Geometry' },
            { title: 'Geometric Proofs' },
        ],
    },
    {
        id: 'trigonometry',
        title: 'Trigonometry',
        description: 'Angle relationships, triangle ratios, trigonometric functions, identities, and applications.',
        units: [
            { title: 'Right Triangle Trigonometry' },
            { title: 'Sine, Cosine, and Tangent' },
            { title: 'Inverse Trigonometric Functions' },
            { title: 'Radians' },
            { title: 'Unit Circle' },
            { title: 'Graphs of Trigonometric Functions' },
            { title: 'Trigonometric Identities' },
            { title: 'Solving Trigonometric Equations' },
            { title: 'Applications of Trigonometry' },
        ],
    },
    {
        id: 'precalculus',
        title: 'Precalculus',
        description: 'Advanced functions, analytic methods, and preparation for calculus.',
        units: [
            { title: 'Function Transformations' },
            { title: 'Composite and Inverse Functions' },
            { title: 'Polynomial and Rational Functions' },
            { title: 'Exponential and Logarithmic Review' },
            { title: 'Trigonometric Review' },
            { title: 'Sequences and Series' },
            { title: 'Conic Sections' },
            { title: 'Parametric Equations' },
            { title: 'Polar Coordinates' },
        ],
    },
    {
        id: 'calculus',
        title: 'Calculus',
        description: 'Limits, derivatives, integrals, and the analysis of change and accumulation.',
        units: [
            { title: 'Limits' },
            { title: 'Continuity' },
            { title: 'Derivatives' },
            { title: 'Applications of Derivatives' },
            { title: 'Integrals' },
            { title: 'Fundamental Theorem of Calculus' },
            { title: 'Applications of Integrals' },
            { title: 'Differential Equations Basics' },
            { title: 'Infinite Series Introduction' },
        ],
    },
    {
        id: 'linear-algebra',
        title: 'Linear Algebra',
        description: 'Vectors, matrices, systems, transformations, and the algebra of higher-dimensional spaces.',
        units: [
            { title: 'Vectors' },
            { title: 'Matrices' },
            { title: 'Matrix Operations' },
            { title: 'Systems of Linear Equations' },
            { title: 'Determinants' },
            { title: 'Vector Spaces' },
            { title: 'Linear Transformations' },
            { title: 'Eigenvalues and Eigenvectors' },
        ],
    },
    {
        id: 'probability-and-statistics',
        title: 'Probability and Statistics',
        description: 'Data analysis, uncertainty, distributions, inference, and the mathematical treatment of random phenomena.',
        units: [
            { title: 'Descriptive Statistics' },
            { title: 'Data Visualization' },
            { title: 'Probability Basics' },
            { title: 'Counting Methods' },
            { title: 'Conditional Probability' },
            { title: 'Random Variables' },
            { title: 'Common Distributions' },
            { title: 'Sampling' },
            { title: 'Confidence Intervals' },
            { title: 'Hypothesis Testing' },
            { title: 'Correlation and Regression' },
        ],
    },
    {
        id: 'discrete-mathematics',
        title: 'Discrete Mathematics',
        description: 'Counting, graphs, recursion, algorithms, and mathematical structures used in computing and combinatorics.',
        units: [
            { title: 'Logic Review' },
            { title: 'Set Operations' },
            { title: 'Counting Principles' },
            { title: 'Combinatorics' },
            { title: 'Recursion' },
            { title: 'Sequences' },
            { title: 'Graph Theory' },
            { title: 'Algorithms Basics' },
            { title: 'Number Theory Introduction' },
        ],
    },
];
const built = (0, createStructuredSubject_1.createStructuredSubject)({
    id: 'mathematics',
    title: 'Mathematics',
    description: 'Local-first mathematics content spanning arithmetic, algebra, geometry, trigonometry, calculus, statistics, and discrete structures.',
    tagline: 'Read, review, and quiz through a broad mathematics study sequence.',
    accent: 'nitrogen',
    practitionerPlural: 'mathematicians',
    topics,
    accentCycle: createStructuredSubject_1.defaultSubjectAccentCycle,
});
exports.mathematicsSubject = built.subject;
exports.mathematicsTopics = built.topics;
exports.mathematicsUnits = built.units;
exports.mathematicsAccentSources = built.accentSources;
