/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/subject/[subjectId]`, params: Router.UnknownInputParams & { subjectId: string | number; } } | { pathname: `/subject/[subjectId]/topic/[topicId]`, params: Router.UnknownInputParams & { subjectId: string | number;topicId: string | number; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]`, params: Router.UnknownInputParams & { subjectId: string | number;topicId: string | number;unitId: string | number; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]/chapter/[chapterId]`, params: Router.UnknownInputParams & { subjectId: string | number;topicId: string | number;unitId: string | number;chapterId: string | number; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]/chapter/[chapterId]/flashcards`, params: Router.UnknownInputParams & { subjectId: string | number;topicId: string | number;unitId: string | number;chapterId: string | number; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]/chapter/[chapterId]/quiz`, params: Router.UnknownInputParams & { subjectId: string | number;topicId: string | number;unitId: string | number;chapterId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/subject/[subjectId]`, params: Router.UnknownOutputParams & { subjectId: string; } } | { pathname: `/subject/[subjectId]/topic/[topicId]`, params: Router.UnknownOutputParams & { subjectId: string;topicId: string; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]`, params: Router.UnknownOutputParams & { subjectId: string;topicId: string;unitId: string; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]/chapter/[chapterId]`, params: Router.UnknownOutputParams & { subjectId: string;topicId: string;unitId: string;chapterId: string; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]/chapter/[chapterId]/flashcards`, params: Router.UnknownOutputParams & { subjectId: string;topicId: string;unitId: string;chapterId: string; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]/chapter/[chapterId]/quiz`, params: Router.UnknownOutputParams & { subjectId: string;topicId: string;unitId: string;chapterId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | `/subject/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/subject/${Router.SingleRoutePart<T>}/topic/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/subject/${Router.SingleRoutePart<T>}/topic/${Router.SingleRoutePart<T>}/unit/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/subject/${Router.SingleRoutePart<T>}/topic/${Router.SingleRoutePart<T>}/unit/${Router.SingleRoutePart<T>}/chapter/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/subject/${Router.SingleRoutePart<T>}/topic/${Router.SingleRoutePart<T>}/unit/${Router.SingleRoutePart<T>}/chapter/${Router.SingleRoutePart<T>}/flashcards${`?${string}` | `#${string}` | ''}` | `/subject/${Router.SingleRoutePart<T>}/topic/${Router.SingleRoutePart<T>}/unit/${Router.SingleRoutePart<T>}/chapter/${Router.SingleRoutePart<T>}/quiz${`?${string}` | `#${string}` | ''}` | { pathname: `/subject/[subjectId]`, params: Router.UnknownInputParams & { subjectId: string | number; } } | { pathname: `/subject/[subjectId]/topic/[topicId]`, params: Router.UnknownInputParams & { subjectId: string | number;topicId: string | number; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]`, params: Router.UnknownInputParams & { subjectId: string | number;topicId: string | number;unitId: string | number; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]/chapter/[chapterId]`, params: Router.UnknownInputParams & { subjectId: string | number;topicId: string | number;unitId: string | number;chapterId: string | number; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]/chapter/[chapterId]/flashcards`, params: Router.UnknownInputParams & { subjectId: string | number;topicId: string | number;unitId: string | number;chapterId: string | number; } } | { pathname: `/subject/[subjectId]/topic/[topicId]/unit/[unitId]/chapter/[chapterId]/quiz`, params: Router.UnknownInputParams & { subjectId: string | number;topicId: string | number;unitId: string | number;chapterId: string | number; } };
    }
  }
}
